### ISSUE TITLE
Trezor one issues

### ISSUE THREAD

**Issue by meggert9** [blockstack/stacks-wallet#100]
My Trezor one is asking me to confirm a btc amount to an address I don't recognize on the physical device when I go through the process of trying to send STX to another public STX address. I would have thought the device would show me the amount of STX I entered in the wallet and the public address I put in for the recipient address. I cancelled the transaction for now because this doesn't make sense to me.

Using stacks wallet 3.0 on macOS, and Trezor One with most recent firmware update.

**Comment by timstackblock** [comment]
Yes there is a small amount of bitcoin that has to be sent to fuel the transaction. You have a bitcoin address that you fill up in your STX wallet and when you make a transaction that is being used and sent to another address. Your transaction was valid please try it again. 

cc @yknl

**Comment by meggert9** [comment]
Yeah, I was aware of the bitcoin gas and thought that that might be the reason I was seeing an amount in BTC, but that isn't really explained in the documentation. The concept of gas is explained, but not really in the context of when you are confirming a transaction on your hardware wallet (excerpt from documentation below)

  _Step 5 from https://docs.blockstack.org/org/wallet-use.html
  5. Select Continue.

  If you do not have enough Bitcoin to fuel the transaction, the system notifies you. If you don’t have 
  enough Bitcoin, you must Top Up. Otherwise, the system prompts you to connect to your hardware 
  wallet. Your hardware wallet will prompt you for additional information and actions._

The Trezor software prompts with 'Check recipient address on your device and follow further instructions'. Device itself then prompts for OP_RETURN code and if I confirm that, I get another prompt to confirm the BTC amount and the address I don't recognize. Documentation doesn't mention the OP_RETURN code or the fact that you will not be confirming the STX amount or STX public address on the Trezor device. 

So from the user's point of view, you click 'Continue' in the Stacks wallet, connect hardware wallet, then get 'Check recipient address on your device and follow further instructions'. You then get asked to confirm OP_RETURN code. If you just go ahead and do that, you are asked to confirm a small amount of BTC to what looks like a random address. So neither of these things match up well with 'check recipient address', and all I see from the Blockstack document is 'Your hardware wallet will prompt you for additional information and actions', which seems too vague to me. It looks like the confirmation is done within the Stacks wallet (steps 6 and 7 in documentation), but some users (myself included) may not make it to those steps due to confusion about what they are seeing on the hardware device.

For now I'm going to hold off on finishing the process even though it was just going to be a test amount. I'm interested in hearing more of your thoughts on this first. Also, is the process cleaner with any of the other supported hardware wallets? I'm assuming it has to do with the fact that there isn't actually a Blockstack app on the Trezor one

**Comment by meggert9** [comment]
@moxiegirl Thanks for the response. So the integration with Trezor (no Blockstack specific app) is why I am seeing BTC and the random address on the device? I should just go ahead and confirm those, and will then have an opportunity to confirm the amount (in STX) and public STX address in the Stacks wallet software after?

Just to be clear, that step I posted that mentioned 'top up' was from the section for Sending Stacks, not specific instructions for topping up. So anyone that is going through the process of sending STX with the Trezor One will probably run into this. I understand your point about all the different updates/versions/firmwares for hardware devices, but I'm not exactly sure how the manufacturer's documentation would be helpful in this case because I think the issue arises from confusion about the interaction between Stacks Wallet and the hardware wallet. I don't imagine their documentation would really have info about that ( or at least I couldn't find anything) as the software development to interact with the Trezor device is done on the Blockstack side. 

Yeah, I think some kind of note could be helpful so users are not thrown off by what they may see on the device. One thing I have seen many places is to never confirm a transaction on the device to an address that you don't recognize.

**Comment by meggert9** [comment]
Was hoping to get some kind of confirmation on my last message before proceeding. Any thoughts? Thanks

**Comment by yknl** [comment]
@meggert9 you will see a confirmation screen on the Stacks wallet after you sign the transaction on your Trezor.

**Comment by meggert9** [comment]
@yknl I sent another email to support but I will include it here as well:
I decided to go ahead and confirm the BTC amount (.000055 BTC for 1 STX) and address on the hardware wallet this morning, and then I was prompted to confirm a second BTC amount (.00049186 BTC) to a different address. I decided to cancel for now because that seems like a large amount of BTC to send just 1 STX ( along with my initial hesitation because I never heard back). Using BTC conversion of 1 BTC to $9343 USD, that's over $5 to send 1 STX (currently trading around $0.22 USD). Just hoping to get some clarification about whether this all seems correct.

After seeing your above message, I decided I would go ahead an confirm the second BTC amount (this time it was .0004806), but then there is a third confirmation "Really send .00061308 BTC from your wallet? Fee included: 0.00007748 BTC". So a fee on top of the .000055 and .0004806 gets the total to .00061308 BTC (which seems really high, and I don't know where these number are coming from). I confirmed the amount just so I could see if I would then get to the confirmation in the Stacks wallet. There I see amount to send of 1 STX and a fee of .00018748 (which seems a bit more in line). I guess my main question would be what is going on with the Trezor confirmations (amounts and addresses)? Should I just disregard those completely and go by what I see in the Stacks wallet? Thanks

**Comment by meggert9** [comment]
@yknl I went ahead and confirmed on the Stacks wallet and now that I see the transaction details, I think I figured out what I was missing. BTX amounts were split out into what was going out to other address as well as what was being sent back to my BTC address (for gas). Is that accurate?

**Comment by yknl** [comment]
Yes that's correct.

**Comment by markmhx** [comment]
I'm closing this out since the questions raised here appear to have been addressed.
