### ISSUE TITLE
Ability to send out BTC from fuel address

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#101]
Before the BTC for transaction fees requirement is phased out in Stacks v2, the wallet should allow users to send out all of the BTC in the fuel address.

**Comment by muneeb-ali** [comment]
This has been coming up lately. A 'BTC sweep" function for wallet 1.0 can help a lot as people switch over to Stacks 2.0.

**Comment by markmhx** [comment]
This has been released
