### ISSUE TITLE
Track balance via locally stored transaction history

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#107]
Currently, the wallet relies on the Blockstack explorer API for transaction history and pending balance tracking. This sometimes results in an out-of-sync pending balance amount which allows users to accidentally send invalid transactions.

**Comment by markmhx** [comment]
@kyranjamie thoughts here on how to better handle this in the new wallet?

**Comment by kyranjamie** [comment]
We'll be relying on the sidecar. Hopefully a WebSocket with a more current, accurate balance would be a good solution.

Tracking the balance changes locally might be a solution, but it could also present further inaccuracies/issues.

**Comment by markmhx** [comment]
@yknl agree that WebSockets here with the Sidecar should help resolve this UX concern?

**Comment by yknl** [comment]
The problem was mostly due to the delay in STX transactions being reflected on a Stacks node. We won't see this problem in Stacks 2.0. I don't think a websocket connection with the Blockchain API is necessary. As long as the wallet updates the account status before any outgoing transactions we wouldn't have a problem.
