### ISSUE TITLE
Ledger Nano X support

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#109]

**Comment by markmhx** [comment]
I'm closing this out since we're incorporating the request into plans for the new Stacks Wallet.

**Comment by jorgedavila25** [comment]
Hi @markmhx 

Where can I learn about this new Stacks Wallet? I too would like to move my STX to my ledger nano x. Is there a product roadmap or blog I can inform myself with? Thanks in advance

**Comment by markmhx** [comment]
The new wallet can be found here as a "developer preview" for testing: https://www.blockstack.org/testnet-wallet

Note that its production release timing corresponds to that of the Stacks 2.0 Mainnet as detailed here: https://blog.blockstack.org/stacks-2-feat-complete-dec-15/
