### ISSUE TITLE
"Allocation" Should be a more obvious button so as not to confuse users into thinking the allocation is not showing

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/stacks-wallet#113]
Often people reach out to support demanding to know where the rest of the tokens are, and they miss the allocation button. The button should be made more obvious.

![image](https://user-images.githubusercontent.com/52256509/67884532-c3918880-fb24-11e9-8240-c6e7f5be191d.png)

**Comment by markmhx** [comment]
I'm closing this out since we're removing this allocation tab entirely in the new wallet.
