### ISSUE TITLE
Sent more stacks out of wallet than I have at that address

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#114]
**Describe the bug**
I has 2 microstacks in my wallet and was able to send out 3 microstacks

**To Reproduce**
1. Go to the wallet
2. Click on send and do 2 send transactions for 1 microstack each, when you have a total 2 microstacks in your wallet. 
3. Scroll down to look at the pending transaction and you will notice that the Pending section disappears. This is one bug all by itself.
4. Then attempt to send more microstacks and the wallet will allow you to with out stopping you.

**Expected behavior**
This should not be allow

**Screenshots**
Pending balance of 0 does not appear

<img width="941" alt="Screen Shot 2019-10-31 at 1 56 11 PM" src="https://user-images.githubusercontent.com/49165468/67974175-50e9e100-fbe8-11e9-8316-f185aefea776.png">

Wallet says I have 2 microstacks when I do not.
<img width="936" alt="Screen Shot 2019-10-31 at 1 56 37 PM" src="https://user-images.githubusercontent.com/49165468/67974202-63fcb100-fbe8-11e9-988f-1881e1369beb.png">

I am able to send more microstacks and have a negative pending balance in my wallet
<img width="946" alt="Screen Shot 2019-10-31 at 1 59 09 PM" src="https://user-images.githubusercontent.com/49165468/67974248-7d9df880-fbe8-11e9-9f48-92a08fd7f859.png">

<img width="340" alt="Screen Shot 2019-10-31 at 2 15 46 PM" src="https://user-images.githubusercontent.com/49165468/67974533-fef58b00-fbe8-11e9-876f-b6a0e5080410.png">

**Desktop (please complete the following information):**
 - OS: Version 10.14.4
 - Browser N/A
 - Version 3.01

**Additional context**

**Comment by yknl** [comment]
@timstackblock does this happen before v3.0.1 or is it newly introduced?

**Comment by timstackblock** [comment]
This was an old bug that we fixed and it is happening again
