### ISSUE TITLE
Ledger no longer has the Browser support option but we still prompt the user during setup

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#117]
**Describe the bug**
Wallet prompt user to, Make sure you have "Browser Support" set to no.

**To Reproduce**
1. Go to the wallet and setup a connection with a Ledger hard wallet
2. Click on all the options to setup the wallet
3. Go to the last screen and you will notice that the user is prompted to Make sure you have "Browser Support" set to no.
4. We no longer have this option in Ledger it has be removed
**Expected behavior**
I think we should change the verbage or remove this screen 

**Screenshots**
<img width="928" alt="Screen Shot 2019-11-11 at 8 22 42 AM" src="https://user-images.githubusercontent.com/49165468/68590576-e2651880-045c-11ea-8bab-c67325dc245c.png">

**Desktop (please complete the following information):**
 - all operating systems
 -Only Ledger hardwallets

**Additional context**

**Comment by whiteyhat** [comment]
This is horrible because it locks the wallet and it does not let users to withdraw

**Comment by yknl** [comment]
@whiteyhat this doesn't lock you out of your wallet. It is only showing you text that you can skip. If your device doesn't have this option you can simply click continue.

**Comment by whiteyhat** [comment]
Then what is going on here?

**Comment by yknl** [comment]
@whiteyhat Looks like you're using a comma `,` instead of a period `.` for the decimal point. Currently the wallet is not localized for EU.

**Comment by whiteyhat** [comment]
Oh. What does the EU localization mean. It does not let me use it if I am in EU?

**Comment by whiteyhat** [comment]
If I am in EU I can not used the wallet?

**Comment by yknl** [comment]
@whiteyhat you can use the wallet anywhere. Localization means number formats and etc.

**Comment by diego-G** [comment]
I have the same issue. I cannot use my Ledger Nano S. The app doesn't move forward when I press continue.

**Comment by markmhx** [comment]
@yknl is it correct that users should generally be able to proceed here, and anyone who can't faces a different problem than lacking browser support per se? (And consequently we can close out this issue?)

@diego-G It sounds like you've hit the problem reported with https://github.com/blockstack/stacks-wallet/issues/124, correct?
