### ISSUE TITLE
Seed phrase overlaps button at bottom of page on Windows

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#119]
**Describe the bug**
Seed phrase overlaps button at bottom of page on Windows

**To Reproduce**
1. Create a new wallet
2. Click on software wallet
3. Scroll down to click "ive written down my seed phrase"

**Expected behavior**
Button should not be under the seed phrase and should be fully visible

**Screenshots**
![image (7)](https://user-images.githubusercontent.com/49165468/70078310-79db0880-15d0-11ea-92f0-4313571fba78.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser n/a
 - Version 3.0.1

**Comment by markmhx** [comment]
I'm closing this out since it's getting resolved with the new wallet design.
