### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by naszam** [blockstack/stacks-wallet#120]
I would like to know when the Stacks Wallet version for Linux will be released, or if there is a way to install the wallet on linux (ubuntu) already.

**Comment by giorgionetg** [comment]
I guess you have to download the package. Something like cloning this repository and then:

`npm install`

Second step is running the project:

`npm start`

And if everything works you have to build for your OS... But I don't expect it works if there are some kind of library that doesn't work on linux. From a fast check it should work. But I don't know if it could be a great idea put a lot of money if you don't know how it works.... Right? I have to test...

**Comment by naszam** [comment]
I'll give a try, Thanks!

**Comment by naszam** [comment]
I've tried to install on Ubuntu 18.04.
When running
`npm run package-all`
it fails the following:
`npm ERR!     yarn build && electron-builder build -mw
`

**Comment by dantrevino** [comment]
```bash
yarn
yarn package-linux
```
builds linux binaries deb, snap, appimage, but they all seg fault

**Comment by naszam** [comment]
I've just tried again on Ubuntu 18.04.  
When running  
`npm run package-linux`   
I get
`npm ERR! stacks-wallet-1@3.0.0 package-linux:` `yarn build && electron-builder build --linux`

**Comment by blockpac** [comment]
Interested in this as well

**Comment by ryanarndtcm** [comment]
to install on Linux, download the source code and build it from the CLI 

https://github.com/blockstack/stacks-wallet/releases/tag/v3.0.0

cc @yknl

**Comment by naszam** [comment]
@ryanarndtcm 
I'm trying to install it on Ubuntu 18.04. 
When I run:
`$ npm install`
I get:
`prebuild-install WARN install No prebuilt binaries found (target=12.14.1 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/dev/Downloads/stacks-wallet-3.0.0/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
compilation terminated.
hidapi.target.mk:109: recipe for target 'Release/obj.target/hidapi/hidapi/linux/hid.o' failed
make: *** [Release/obj.target/hidapi/hidapi/linux/hid.o] Error 1
make: Leaving directory '/home/dev/Downloads/stacks-wallet-3.0.0/node_modules/node-hid/build'
`

**Comment by ryanarndtcm** [comment]
thanks Nazsam. @yknl will need to take a look as the wallet engineer. I have tagged him on this post.

**Comment by dantrevino** [comment]
I have no issue getting a build and several binaries,but none of them work.  

The release deb segfaults, 
```
 dan@chaos:/opt/Stacks Wallet>  ./stacks-wallet-1 
[1]    13586 segmentation fault (core dumped)  ./stacks-wallet-1
```
AppImage does the same

```
 ./Stacks\ Wallet\ 3.0.0.AppImage          
[1]    16091 segmentation fault (core dumped)  ./Stacks\ Wallet\ 3.0.0.AppImage
```

snap doesnt show up in user menu, and segfaults
```
/snap/stacks-wallet-1/current
[1]    20817 segmentation fault (core dumped)  ./stacks-wallet-1
```

**Comment by yknl** [comment]
Linux is not officially supported currently. You can try running it in development if the default electron builds aren't working. This is however very much at your own risk.

`npm install`
`npm run dev`

**Comment by dantrevino** [comment]
Whose ears do we have to pull to get it supported?  Every craptastic crypto project out there has a linux wallet but Stacks.  We continue to support closed-source, proprietary operating systems as first class citizens for a public, open source crypto project.  Seems outta whack from my perspective. @jeffdomke ?

**Comment by diwakergupta** [comment]
@dantrevino if the community wants it, we'd more than welcome help and PRs!

PBC bandwidth is limited and there are always important things we're unable to prioritize -- does not mean we don't care about them.

**Comment by whoabuddy** [comment]
I've tried once and failed, so I thought I would throw up some notes as I go along. I would be very happy to be able to run a Stacks wallet on Linux (specifically, Ubuntu/Debian)!

-----

@naszam You are missing a dependency, I was able to resolve it with `sudo apt-get install libudev-dev` which should fix this portion:

```
CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o  
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory  
 #include <libudev.h>  
compilation terminated.
```

-----

I ran into some other issues on my system (LM19) because I already had `node` and `npm` but didn't have `yarn` installed, too. [Per the yarn documentation](https://classic.yarnpkg.com/en/docs/install/#debian-stable) install it this way instead of using the `cmdtest` package included with Debian/Ubuntu. (Also, if you have `cmdtest` installed already, uninstall it first).

```bash
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install --no-install-recommends yarn
```

I am running some additional tests as I go along, and if I can get it resolved, I will post a walk-through on how I got there and/or additional details here if relevant.

I also want to look at this from the perspective of a clean install (on a VM) if I can get it running, so we can hash out exactly what's missing for dependencies and settings.

**Comment by whoabuddy** [comment]
@dantrevino @yknl @naszam 

After a (long) day of testing, I finally figured it out and have the Stacks wallet running on Linux Mint 19. The instructions below should work for any Ubuntu / Debian installation but I have not tested it any further.

**_Please follow the instructions below at your own risk, I am not responsible for anything, just a guy who got it to work and documented the process._** :sunglasses: 

-----

## Proof or it didn't happen

![Screenshot from 2020-03-21 12-44-15](https://user-images.githubusercontent.com/9038904/77236140-04904500-6b79-11ea-9a5d-4d2afa826503.png)

![Screenshot from 2020-03-21 12-47-51](https://user-images.githubusercontent.com/9038904/77236143-0bb75300-6b79-11ea-865d-68534decec3c.png)

## Prerequisites

There was one package I needed to resolve an error during build, install the `libudev-dev` package.

```bash
sudo apt-get install libudev-dev
```

You should have `node`, `npm`, and `yarn` installed. Note that we will use `yarn` throughout this process as `npm` caused more errors/headaches for me in the beginning.

```bash
node -v
npm -v
yarn -v
```

If you do not have node/npm installed, then please follow the relevant documentation.

If you do not have yarn installed, first make sure you __do not__ have the `cmdtest` package installed. If you do, uninstall it, then follow the commands below:

```bash
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install --no-install-recommends yarn
```

With `yarn` installed, add the `electron-builder` package.

```bash
yarn add electron-builder --dev
```

## Package.json changes

There were three main changes I made so this would work for me, based on:

1. There was a license warning that was easy enough to fix
2. Creating a .deb packages require an email address
3. The linux "target" included rpm, and I don't have rpm installed (fails at rpmbuild)

Based on those criteria, I updated the following:

```json
"author": {
    "name": "Blockstack PBC",
    "url": "https://www.blockstack.org",
    "email": "hello@stackstoken.com"
  },
```

```json
"linux": {
      "target": [
        "deb"
      ],
```

```json
"license": "GPL-3.0-only",
```

This way I am only targeting a .deb package which is my goal on Ubuntu/Debian. I also think it's worth looking at separating the builds by package rather than distro, i.e. `yarn-deb`, `yarn-rpm`, `yarn-snap`, `yarn-linux-all`, or similar.

## The actual build 

```bash
yarn
yarn-linux
```

For me these finished in 3676.34s and 1508.43s respectively, so maybe plan something else to do while waiting? (~86min total if you don't like math)

## Running the program

It's on my menu with a default Electron icon, and it runs as expected. I walked through all of ths screens and set it up without a hardware wallet, so someone else will have to test using one for new creation and/or restoring a wallet. 

## Resources

yarn install: https://classic.yarnpkg.com/en/docs/install/#debian-stable
electron-builder install: https://www.electron.build/#installation

## Final thoughts

I can push some of these changes into a PR, but I'd love to see if it works for others first, so test it out and let me know if any issues!

**Comment by naszam** [comment]
@whoabuddy Just tried following your instructions. I get the following error:
```
secp256k1.target.mk:153: recipe for target 'Release/obj.target/secp256k1/native/addon.o' failed
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
make: Leaving directory '/home/dev/bks-wallet/node_modules/tiny-secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dev/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/home/dev/.nvm/versions/node/v12.16.1/bin/node" "/home/dev/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev/bks-wallet/node_modules/tiny-secp256k1
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```
Tried also with node v12.14

**Comment by naszam** [comment]
Now, I'm trying to fix it following the issue:
https://github.com/nodejs/node-gyp/issues/1694

probably is due to a version of protagonist

**Comment by naszam** [comment]
Nope! same Error, any idea?

**Comment by naszam** [comment]
Now, trying this:

> Follow these steps to resolve the issue.
> 
> 1: Make sure you have build-tools installed.
> 2: Update node-gyp
> 3: Delete package-lock.json and node modules folder and run npm install again.
> 4: Deleting ~/.node-gyp folder and run npm install again.
> 
> Source: https://codeforgeek.com/make-failed-with-exit-code-2/

**Comment by naszam** [comment]
Using node v10 seems to work fine regarding that error but I get the following:
```
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
/home/dev/bks-wallet/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^
TypeError: t(...).isPlaceholder is not a function
```

**Comment by whoabuddy** [comment]
Hey @naszam, sorry my instructions weren't clear, the working one on linux mint is under a diff branch than master from my repo, and then the PR is a third branch. You would be better off to clone your own and make the suggest changes.

I also plan on testing this from a VM with nothing installed as these were the dependencies _I needed to make it work_ but YMMV. 

My node version is 12.something (not sure off the top of my head). Was there a longer error message generated than what you posted? I feel like that error doesn't give me something to act on (and my node-gyp issues turned out to be something diff anyway).

**Comment by naszam** [comment]
Ok, no worries.
Let me know if you manged to get it working!

**Comment by dantrevino** [comment]
@whoabuddy this all results in the same segfault for me.

**Comment by naszam** [comment]
I've just tried now on a new account on Ubuntu 18.04.
I've followed the instructions to edit package.json, then running:
```
npm install
npm run start 
or
npm run dev
```
Both worked!

**Comment by whoabuddy** [comment]
@naszam and @dantrevino thank you for the valuable feedback, I was hoping my instructions would work for all, but we seem to be running into different issues along the way. I am happy to hear it is working for others, at least!

**Comment by fluidvoice** [comment]
I built using a fresh Ubuntu 19.10 VM with the below actions. Everything built but none of the binaries run. They all core-dumped.
## steps
sudo apt-get install libudev-dev
sudo apt-get install gconf2
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install --no-install-recommends yarn
yarn package-linux
sudo snap install --dangerous stacks-wallet-1_3.0.0_amd64.snap 
```
brad@vm:~/blockstack/stacks-wallet-3.0.0$ yarn package-linux
yarn run v1.22.4
$ yarn build && electron-builder build --linux
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
[0] Hash: 09d1a1d0476ab4f570a9
[0] Version: webpack 4.20.2
[0] Time: 1313ms
[0] Built at: 06/03/2020 12:44:38 AM
[0]                  Asset      Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  67.2 KiB       0  [emitted]  main
[0] ./app/main.prod.js.map   270 KiB       0  [emitted]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.js] ./app/main.dev.js + 1 modules 6.14 KiB {0} [built]
[0]     | ./app/main.dev.js 3.33 KiB [built]
[0]     | ./app/menu.js 2.79 KiB [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [electron-debug] external "electron-debug" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [source-map-support] external "source-map-support" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 26 hidden modules
[0] yarn build-main exited with code 0
[1] Hash: 98e9f20c6be32911fcd4
[1] Version: webpack 4.20.2
[1] Time: 8849ms
[1] Built at: 06/03/2020 12:44:46 AM
[1]                Asset      Size  Chunks             Chunk Names
[1]     renderer.prod.js  2.15 MiB       0  [emitted]  main
[1] renderer.prod.js.map  4.79 MiB       0  [emitted]  main
[1] Entrypoint main = renderer.prod.js renderer.prod.js.map
[1] [./app/index.js] ./app/index.js + 87 modules 245 KiB {0} [built]
[1]     | ./app/store/persist/getPersistMiddleware.js 890 bytes [built]
[1]     | ./app/index.js 1.36 KiB [built]
[1]     | ./app/containers/root/index.js 682 bytes [built]
[1]     | ./app/store/persist/index.js 3.29 KiB [built]
[1]     | ./app/store/configureStore.dev.js 1.73 KiB [built]
[1]     | ./app/containers/routes/index.js 2.17 KiB [built]
[1]     | ./app/store/configureStore.prod.js 1.4 KiB [built]
[1]     | ./app/store/configureStore.js 377 bytes [built]
[1]     | ./app/store/reducers/wallet.js 5.51 KiB [built]
[1]     | ./app/screens/onboarding/hardware-wallet/index.js 2.51 KiB [built]
[1]     | ./app/screens/onboarding/confirm-seed/index.js 4.82 KiB [built]
[1]     | ./app/common/constants.js 1.24 KiB [built]
[1]     | ./app/screens/dashboard/index.js 3.69 KiB [built]
[1]     | ./app/screens/onboarding/hardware-wallet/trezor.js 1.85 KiB [built]
[1]     | ./app/screens/onboarding/hardware-wallet/ledger.js 2.11 KiB [built]
[1]     |     + 73 hidden modules
[1] [blockstack-ui] external "blockstack-ui" 42 bytes {0} [built]
[1] [connected-react-router] external "connected-react-router" 42 bytes {0} [built]
[1] [electron-store] external "electron-store" 42 bytes {0} [built]
[1] [polished] external "polished" 42 bytes {0} [built]
[1] [react] external "react" 42 bytes {0} [built]
[1] [react-dom] external "react-dom" 42 bytes {0} [built]
[1] [react-hot-loader] external "react-hot-loader" 42 bytes {0} [built]
[1] [react-redux] external "react-redux" 42 bytes {0} [built]
[1] [react-router] external "react-router" 42 bytes {0} [built]
[1] [react-router-redux] external "react-router-redux" 42 bytes {0} [built]
[1] [react-spring] external "react-spring" 42 bytes {0} [built]
[1] [redux] external "redux" 42 bytes {0} [built]
[1] [redux-thunk] external "redux-thunk" 42 bytes {0} [built]
[1] [styled-components] external "styled-components" 42 bytes {0} [built]
[1]     + 197 hidden modules
[1] yarn build-renderer exited with code 0
  • electron-builder  version=22.7.0 os=5.3.0-45-generic
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=node-hid@0.7.3, tiny-secp256k1@1.0.1 platform=linux arch=x64
  • install prebuilt binary  name=node-hid version=0.7.3 platform=linux arch=x64
  • rebuilding native dependency  name=tiny-secp256k1 version=1.0.1
  • packaging       platform=linux arch=x64 electron=2.0.6 appOutDir=release/linux-unpacked
  • building        target=snap arch=x64 file=release/stacks-wallet-1_3.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=release/Stacks Wallet-3.0.0.AppImage
  • Electron 4 and higher is highly recommended for Snap
  • building        target=deb arch=x64 file=release/stacks-wallet-1_3.0.0_amd64.deb
Done in 234.20s.

```

**Comment by blockpac** [comment]
@fluidvoice Thanks for giving this another go! So after building it, the wallet did not work as expected?

**Comment by fluidvoice** [comment]
> @fluidvoice Thanks for giving this another go! So after building it, the wallet did not work as expected?

as I said above "They all core-dumped." so no it did not run at all.  Core-dumped means it crashed.

**Comment by fluidvoice** [comment]
@dantrevino do you have any ideas here?

> I built using a fresh Ubuntu 19.10 VM with the below actions. Everything built but none of the binaries run. They all core-dumped.
> 
> ## steps
> sudo apt-get install libudev-dev
> sudo apt-get install gconf2
> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> sudo apt-get install -y nodejs
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
> echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
> sudo apt-get update && sudo apt-get install --no-install-recommends yarn
> yarn package-linux
> sudo snap install --dangerous stacks-wallet-1_3.0.0_amd64.snap
> 
> ```
> brad@vm:~/blockstack/stacks-wallet-3.0.0$ yarn package-linux
> yarn run v1.22.4
> $ yarn build && electron-builder build --linux
> $ concurrently "yarn build-main" "yarn build-renderer"
> $ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
> $ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
> [0] Hash: 09d1a1d0476ab4f570a9
> [0] Version: webpack 4.20.2
> [0] Time: 1313ms
> [0] Built at: 06/03/2020 12:44:38 AM
> [0]                  Asset      Size  Chunks             Chunk Names
> [0]     ./app/main.prod.js  67.2 KiB       0  [emitted]  main
> [0] ./app/main.prod.js.map   270 KiB       0  [emitted]  main
> [0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
> [0] [./app/main.dev.js] ./app/main.dev.js + 1 modules 6.14 KiB {0} [built]
> [0]     | ./app/main.dev.js 3.33 KiB [built]
> [0]     | ./app/menu.js 2.79 KiB [built]
> [0] [assert] external "assert" 42 bytes {0} [built]
> [0] [child_process] external "child_process" 42 bytes {0} [built]
> [0] [electron] external "electron" 42 bytes {0} [built]
> [0] [electron-debug] external "electron-debug" 42 bytes {0} [built]
> [0] [events] external "events" 42 bytes {0} [built]
> [0] [fs] external "fs" 42 bytes {0} [built]
> [0] [https] external "https" 42 bytes {0} [built]
> [0] [path] external "path" 42 bytes {0} [built]
> [0] [source-map-support] external "source-map-support" 42 bytes {0} [built]
> [0] [util] external "util" 42 bytes {0} [built]
> [0]     + 26 hidden modules
> [0] yarn build-main exited with code 0
> [1] Hash: 98e9f20c6be32911fcd4
> [1] Version: webpack 4.20.2
> [1] Time: 8849ms
> [1] Built at: 06/03/2020 12:44:46 AM
> [1]                Asset      Size  Chunks             Chunk Names
> [1]     renderer.prod.js  2.15 MiB       0  [emitted]  main
> [1] renderer.prod.js.map  4.79 MiB       0  [emitted]  main
> [1] Entrypoint main = renderer.prod.js renderer.prod.js.map
> [1] [./app/index.js] ./app/index.js + 87 modules 245 KiB {0} [built]
> [1]     | ./app/store/persist/getPersistMiddleware.js 890 bytes [built]
> [1]     | ./app/index.js 1.36 KiB [built]
> [1]     | ./app/containers/root/index.js 682 bytes [built]
> [1]     | ./app/store/persist/index.js 3.29 KiB [built]
> [1]     | ./app/store/configureStore.dev.js 1.73 KiB [built]
> [1]     | ./app/containers/routes/index.js 2.17 KiB [built]
> [1]     | ./app/store/configureStore.prod.js 1.4 KiB [built]
> [1]     | ./app/store/configureStore.js 377 bytes [built]
> [1]     | ./app/store/reducers/wallet.js 5.51 KiB [built]
> [1]     | ./app/screens/onboarding/hardware-wallet/index.js 2.51 KiB [built]
> [1]     | ./app/screens/onboarding/confirm-seed/index.js 4.82 KiB [built]
> [1]     | ./app/common/constants.js 1.24 KiB [built]
> [1]     | ./app/screens/dashboard/index.js 3.69 KiB [built]
> [1]     | ./app/screens/onboarding/hardware-wallet/trezor.js 1.85 KiB [built]
> [1]     | ./app/screens/onboarding/hardware-wallet/ledger.js 2.11 KiB [built]
> [1]     |     + 73 hidden modules
> [1] [blockstack-ui] external "blockstack-ui" 42 bytes {0} [built]
> [1] [connected-react-router] external "connected-react-router" 42 bytes {0} [built]
> [1] [electron-store] external "electron-store" 42 bytes {0} [built]
> [1] [polished] external "polished" 42 bytes {0} [built]
> [1] [react] external "react" 42 bytes {0} [built]
> [1] [react-dom] external "react-dom" 42 bytes {0} [built]
> [1] [react-hot-loader] external "react-hot-loader" 42 bytes {0} [built]
> [1] [react-redux] external "react-redux" 42 bytes {0} [built]
> [1] [react-router] external "react-router" 42 bytes {0} [built]
> [1] [react-router-redux] external "react-router-redux" 42 bytes {0} [built]
> [1] [react-spring] external "react-spring" 42 bytes {0} [built]
> [1] [redux] external "redux" 42 bytes {0} [built]
> [1] [redux-thunk] external "redux-thunk" 42 bytes {0} [built]
> [1] [styled-components] external "styled-components" 42 bytes {0} [built]
> [1]     + 197 hidden modules
> [1] yarn build-renderer exited with code 0
>   • electron-builder  version=22.7.0 os=5.3.0-45-generic
>   • loaded configuration  file=package.json ("build" field)
>   • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
> 
> To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
>   • writing effective config  file=release/builder-effective-config.yaml
>   • rebuilding native dependencies  dependencies=node-hid@0.7.3, tiny-secp256k1@1.0.1 platform=linux arch=x64
>   • install prebuilt binary  name=node-hid version=0.7.3 platform=linux arch=x64
>   • rebuilding native dependency  name=tiny-secp256k1 version=1.0.1
>   • packaging       platform=linux arch=x64 electron=2.0.6 appOutDir=release/linux-unpacked
>   • building        target=snap arch=x64 file=release/stacks-wallet-1_3.0.0_amd64.snap
>   • building        target=AppImage arch=x64 file=release/Stacks Wallet-3.0.0.AppImage
>   • Electron 4 and higher is highly recommended for Snap
>   • building        target=deb arch=x64 file=release/stacks-wallet-1_3.0.0_amd64.deb
> Done in 234.20s.
> ```

**Comment by dantrevino** [comment]
> @dantrevino do you have any ideas here?
I haven't been able to consistently get a successful build. When i did have success it was on Ubuntu 18.04. I haven't tried in a while.

**Comment by markmhx** [comment]
For those who haven't heard elsewhere already: the UserX team at PBC is working on a whole new Stacks Wallet with Linux support, and we'd love get your eyes on it during pre-release testing against [Stacks 2.0 Testnet](https://testnet.blockstack.org/):

https://www.blockstack.org/p/stacks-wallet

You can find instructions for installing and using the build on Linux at the above link. If you have a chance, please try it out and let me know whether you run into any problems (either here or in newly submitted issues). 🙏
