### ISSUE TITLE
Stacks v2 compatibility

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#121]
The wallet needs to be compatible with the upcoming v2 of the Stacks Blockchain

1. Stacks wallet should prevent v1.0 transactions from being broadcasted once v2.0 is live.
2. Stacks wallet should support v2.0 transactions.

**Comment by giorgionetg** [comment]
I guess you have to download the package. Something like cloning this repository and then:

`npm install`

Second step is running the project:

`npm start`

And if everything works you have to build for your OS... But I don't expect it works if there are some kind of library that doesn't work on linux. From a fast check it should work. But I don't know if it could be a great idea put a lot of money if you don't know how it works.... Right?

**Comment by markmhx** [comment]
@kyranjamie want to keep this issue open to track your work or cleaner to close out?
