### ISSUE TITLE
transaction history not displaying in 3.0.2

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#123]
**Describe the bug**
log in with a Ledger wallet 
I used address SPK4MEG73CWPSCEQB42B1ZSXMZ7XFFF3PV0CGWQ

**To Reproduce**
1. Go to the transaction tab
2. No history will be displayed
3. Verify in explorer that the wallet has transaction history
4. See error in image below

**Expected behavior**
Transaction history should display

**Screenshots**
<img width="942" alt="Screen Shot 2020-02-06 at 1 57 19 PM" src="https://user-images.githubusercontent.com/49165468/73969157-e207dc80-48e8-11ea-8c8c-c183a46c3a04.png">

**Comment by timstackblock** [comment]
This goes away after a transaction goes through and everything looks normal

<img width="940" alt="Screen Shot 2020-02-06 at 2 02 29 PM" src="https://user-images.githubusercontent.com/49165468/73969517-96a1fe00-48e9-11ea-8475-91ef16f3a65e.png">

**Comment by MrPratowo** [comment]
SP3DZJXJGSYYK76Y9MFJCBCHESJJEJD9073PHDM0Z

**Comment by MrPratowo** [comment]
![image](https://user-images.githubusercontent.com/46632383/75615385-74607080-5b75-11ea-8a24-828eabc9bfa8.png)
