### ISSUE TITLE
Ensure transaction history matches Explorer data

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#126]
**Describe the bug**
A past date of Jan 17th is listed for a transaction that just occurred 

**To Reproduce**
1. Go to your wallet and process a transaction
2. Click on refresh in the wallet after the transaction has updated on the blockchain and is in explorer
3. Compare the date in explorer with the date in the wallet transactions

**Expected behavior**
The date should be displayed as expected in explorer it should not be a past date

**Screenshots**
<img width="1437" alt="Screen Shot 2020-02-07 at 10 08 03 AM" src="https://user-images.githubusercontent.com/49165468/74191453-98d5c680-4c21-11ea-90b1-2535043a7302.png">
<img width="913" alt="Screen Shot 2020-02-07 at 10 08 27 AM" src="https://user-images.githubusercontent.com/49165468/74191454-9a06f380-4c21-11ea-8c3b-98eb5379d712.png">
<img width="909" alt="Screen Shot 2020-02-07 at 10 08 47 AM" src="https://user-images.githubusercontent.com/49165468/74191456-9a06f380-4c21-11ea-82f1-f7c9961bd333.png">

**Desktop (please complete the following information):**
 - OS: mac 10.14.4
 - Browser n/a
 - Version 3.0.2

**

**Comment by markmhx** [comment]
I'm assigning to @kyranjamie so he can make sure this bug doesn't translate to the new wallet. I don't think we'll prioritize a fix for this for the existing wallet unless something urgent related to it arises.

**Comment by kyranjamie** [comment]
Tagged wrong issue 👆 

Duly noted issue.

**Comment by markmhx** [comment]
@kyranjamie might this behavior be ready to test by @timstackblock in the new wallet?

**Comment by timstackblock** [comment]
@markmhx @kyranjamie We haven't gotten the address page functionality in the new explorer yet but it is coming soon. So it would be kind of hard to test this currently because the explorer doesn't show all transactions for the address.

**Comment by markmhx** [comment]
@aulneau @agraebe do we have an ETA for when we'll have an address page on the Explorer?

**Comment by agraebe** [comment]
The latest deployment includes address pages, eg: https://testnet-explorer.blockstack.org/address/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6

**Comment by timstackblock** [comment]
This looks good 

https://testnet-explorer.blockstack.org/address/ST2MQ90MTF6SNZ9KA6BG03BR6RSJ2C3W9GXWB8K16

<img width="1415" alt="Screen Shot 2020-12-03 at 9 14 59 PM" src="https://user-images.githubusercontent.com/49165468/101113203-e7878f00-35ac-11eb-8810-6294c92035b5.png">
<img width="1016" alt="Screen Shot 2020-12-03 at 9 14 50 PM" src="https://user-images.githubusercontent.com/49165468/101113204-e8202580-35ac-11eb-9a5e-d07c50ae1466.png">
