### ISSUE TITLE
No more staking?

### ISSUE THREAD

**Issue by Legalien** [blockstack/stacks-wallet#1270]
I updated my Leather desktop wallet the other day, and it's almost as if staking has been removed from the wallet.

I can't see a way to stake. I can't see a way to check if my stacks are still staked, and I can't see a way to unstake.

What's the deal?

Thanks

**Comment by 314159265359879** [comment]
@Legalien, the stacking contract was recently upgraded to version 4. For now, the current Leather Desktop wallet is not getting support for that, as the team focuses on other work. 

You can still Stack STX using the Leather extension (with or without Ledger device) together with the lockstacks.com app. The experience will be familiar to anyone who has used the desktop wallet prior. 

We do have plans for an upgraded version of the Desktop wallet in the future.

**Comment by Legalien** [comment]
> @Legalien, the stacking contract was recently upgraded to version 4. For now, the current Leather Desktop wallet is not getting support for that, as the team focuses on other work.
> 
> You can still Stack STX using the Leather extension (with or without Ledger device) together with the lockstacks.com app. The experience will be familiar to anyone who has used the desktop wallet prior.
> 
> We do have plans for an upgraded version of the Desktop wallet in the future.

I got it. I did stake through the chrome app. Thanks :)
