### ISSUE TITLE
Unable to View Token Balance

### ISSUE THREAD

**Issue by Ledensy** [blockstack/stacks-wallet#1271]
Bug found testing Leather build undefined, 4.15.1.

**Comment by 314159265359879** [comment]
@Ledensy, Thanks for reporting! Would you mind sharing a screenshot? The Desktop wallet is only expected to display the STX balance. Is that not displayed in your Leather wallet?

The desktop wallet does not support other tokens such as SIP010 tokens or Bitcoin. To see those tokens I recommend using the Leather browser extension instead.

**Comment by markmhendrickson** [comment]
@Ledensy I'm closing for now, but can reopen if you provide a screenshot to help us diagnose the issue. 🙏
