### ISSUE TITLE
[4.15.1] Unlock issue

### ISSUE THREAD

**Issue by alireza1992** [blockstack/stacks-wallet#1275]
Hello team, I have an odd issue with the leather wallet, My staking time is apparently over with https://lockstacks.com/ and it says so , but I am seeing all of my stx as locked in my wallet. Is there a way to confirm/see what is going on and where is my asset?

**Comment by Hinted-tech** [comment]
> Hello team, I have an odd issue with the leather wallet, My staking time is apparently over with https://lockstacks.com/ and it says so , but I am seeing all of my stx as locked in my wallet. Is there a way to confirm/see what is going on and where is my asset?

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Leather Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by StevfoDEV** [comment]
@alireza1992 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LEATHER SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by pete-watters** [comment]
@alireza1992 -  please don't use any of those links as they are spam. If you need help you can contact our support here: https://leather.io/contact 

CC @314159265359879

**Comment by alireza1992** [comment]
Already reported them, thanks for the response, already figured it out
