### ISSUE TITLE
BTC balance shows 0 when BTC should have a balance

### ISSUE THREAD

**Issue by stanbenavides** [blockstack/stacks-wallet#128]
Using  STX MacOS wallet 3.0 on 
MacBook Pro Catalina 10.15.3

Uploaded BTC and frequently when I access the app it shows 0 BTC balance.  Issue also when I access the browser wallet view.

There is no error but I had BTC balance after I used part of it on a previous transfer out of STX, but now it shows 0

Plus previous transactions do not show in the transaction window.

Token balance and Allocations balance are correct.

**Comment by yknl** [comment]
Can you explain what browser wallet view is? 

You can look up the BTC fuel balance on a Bitcoin explorer to verify if you don't think the amount shown in the Stacks wallet is correct.

**Comment by stanbenavides** [comment]
Thank you for your reply
I was talking about the wallet option on your website https://browser.blockstack.org.  I assumed that it refers to my wallet tied to my profile.
However the MacOS App has a different wallet Id than the browser.  That could be one issue.  I did verify my balance on a Bitcoin explore but the question really remains why the MacOS App doesn't show the transactions 1 and the bitcoin balance.  I have left it open incase it takes time to load but that didn't seem to happen.
Is there something I need to do/refresh etc to get it to show?
Thanks

**Comment by yknl** [comment]
browser.blockstack.org is a separate app, there's no link between the BTC wallet there and the fuel address in the Stacks wallet. The Stacks wallet does not show transaction history of BTC, to see your BTC fuel balance click on the settings icon.
