### ISSUE TITLE
Add ability to transfer out BTC from fuel address

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#131]
With Stacks v2.0, BTC will not longer be a requirement. Users should be able to transfer out any remaining BTC in the fuel address.

## Current BTC flow

Authenticated user selects the "Settings" gear in the top-right corner of the wallet:

<img width="752" alt="Screen Shot 2020-08-20 at 11 37 31" src="https://user-images.githubusercontent.com/28991/90753994-942d5180-e2d9-11ea-9fed-fc4804773bcb.png">

They see how much BTC they currently have in the wallet for paying transaction fees, with an option to "Add BTC":

<img width="936" alt="Screen Shot 2020-08-20 at 11 36 52" src="https://user-images.githubusercontent.com/28991/90754037-a9a27b80-e2d9-11ea-9cb0-8f496967ce16.png">

Upon selecting "Add BTC", they are told that BTC is only used to pay fees and warned "You cannot send BTC from this wallet" before proceeding:

<img width="577" alt="Screen Shot 2020-08-20 at 11 36 58" src="https://user-images.githubusercontent.com/28991/90754127-ce96ee80-e2d9-11ea-865b-aac9628cd7a6.png">

They are then shown a QR code and address for depositing BTC:

<img width="582" alt="Screen Shot 2020-08-20 at 11 37 02" src="https://user-images.githubusercontent.com/28991/90754237-eb332680-e2d9-11ea-9395-50fdba1dfb73.png">

## Changes to BTC flow needed

- The user should be able to select "Withdraw BTC" in addition to "Add BTC" from the settings modal. This should prompt them with a message that says "Enter a Bitcoin address to withdraw all [TOTAL AMOUNT IN WALLET] BTC from the Stacks Wallet" with a field for "Bitcoin address" and submission button.
- Upon submission, the form should validate the address entry and if valid, the user should see a simple confirmation message.
- Upon selecting "Add BTC", the "You cannot send BTC from this wallet" copy should no longer be shown since that will no longer be the case.

**Comment by agraebe** [comment]
I'm adding a bit more context and an estimate to this feature request:

**Motivation**
The existing Stacks Wallet lets users deposit BTC (to pay for transaction fees) but doesn't allow users to get that BTC out.

**Solution**
Upgrade the existing wallet with a feature that allows BTC withdrawals.

**Estimate**
Based on the best, most recent estimates, this new feature will be released with the completion of the [current DevX sprint](https://github.com/orgs/blockstack/projects/40), close to **September 22nd**.

**Comment by markmhx** [comment]
The related PR is https://github.com/blockstack/stacks-wallet/pull/228.

@agraebe any updated estimate for this feature's release available?

**Comment by yknl** [comment]
We are now looking at a release of this feature in the coming week. (week of Sept 28)

**Comment by agraebe** [comment]
A new version of the Wallet (v3.1.0) [has been released](https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.0). The release includes this feature request and enables withdrawal of BTC
