### ISSUE TITLE
Add ability to generate a new address when receiving stx

### ISSUE THREAD

**Issue by kkomaz** [blockstack/stacks-wallet#135]
**Is your feature request related to a problem? Please describe.**
It is problematic to use the same stx address when receiving stx from peers.  This exposes my address to others with information about how much stx tokens I have, where I sent it, etc.

**Describe the solution you'd like**
I would like the ability to generate a new address when receiving stx.

Something like the picture below

![Screenshot of Bitcoin com Wallet (5-5-20, 5-09-03 PM)](https://user-images.githubusercontent.com/8473884/81116318-25c3af80-8ef3-11ea-85c6-2163000806c0.png)

**Describe alternatives you've considered**
Use the same address?  no change needed here.

**Additional context**
We want to make STX a utility token where transaction should be comfortably sent without the fear of sharing too much to the other user.

**Comment by markmhx** [comment]
This is now tracked by https://github.com/blockstack/stacks-wallet/issues/402.
