### ISSUE TITLE
Onboarding screens

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#137]
Implement the layouts of the onboarding screens

- [x] Welcome
- [x] Create new wallet
- [x] Restore wallet
- [x] Generating Secret Key
- [x] Your Secret Key
- [x] Save Secret Key
- [x] Verify Secret Key
- [x] Set password
- [ ] Enter password

**Comment by markmhx** [comment]
@kyranjamie Mind linking the related PRs here now under review?

**Comment by kyranjamie** [comment]
There's no PR for these initial screens, [see message in Slack](https://blockstackpbc.slack.com/archives/CD0CTNATW/p1591097877086300).

I haven't received any feedback, so think this can be considered done for now. Reviews welcome at anytime in future.
