### ISSUE TITLE
Include a strict Content Security Policy

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#141]
https://www.electronjs.org/docs/tutorial/security#6-define-a-content-security-policy

**Comment by markmhx** [comment]
@kyranjamie good for sprint 2?

**Comment by kyranjamie** [comment]
The CSP I've landed on is as follows:

`default-src 'none'; font-src 'self'; img-src data:; style-src 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'nonce-6ca3c3e1fcd34bbc8cfaeceaa8106e36'; connect-src *;`

Some limitations I've ran into:

- `ajv` a dependency we're using currently, requires the `script-src 'unsafe-eval'` directive
- styled-components requires the  `style-src 'unsafe-inline'` directive
- Choose your own node functionality requires a wildcard `connect-src *`

**Comment by kyranjamie** [comment]
CSP is being changed further to be more strict, see https://github.com/sindresorhus/conf/issues/126
