### ISSUE TITLE
Add standard CI jobs to Github actions

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#144]
- [x] eslint check
- [x] commitlint checks
- [ ] Unit tests

**Comment by markmhx** [comment]
@kyranjamie Did you put this in QA because you want @timstackblock to test it somehow? Is there a PR to link here?

**Comment by kyranjamie** [comment]
Not sure why I put it here. This is a dev-only feature so don't think it needs QAing.

**Comment by markmhx** [comment]
Ok cool, I see "Unit tests" isn't checked off yet. Is this ready to close or should we send back to dev?

**Comment by kyranjamie** [comment]
@markmhx will address this later when there are tests to run
