### ISSUE TITLE
Encrypt private key on disk

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#145]
Currently the wallet is designed to work without having to reenter your seed phrase by storing an encrypted private key on disk. [See password page in Figma designs.](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=300%3A165).

This task requires 
- [x] implementing a means of securely saving a private key to disk
  - uses encrypt/decrypt methods from blockstack.js
- [x] utilising electron apis to save a configuration file to disk
  - uses [electron-store library](https://github.com/sindresorhus/electron-store/)
- [x] implementing encryption/decryption logic

**Comment by zone117x** [comment]
Here be dragons

**Comment by markmhx** [comment]
@kyranjamie Any update on the proposal document you've circulated internally?
