### ISSUE TITLE
Add BTC fee customization

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/stacks-wallet#146]
I've seen users of the wallet complain about high BTC transaction fees. The currently algorithm might be too careful in picking high fees. Is there a way to let people customize their fee?

I understand that Stacks 1.0 wallet will get deprecated soon with launch of Stacks 2.0 but in the coming months there might a bunch of activity around moving STX and with the increase in BTC price and network congestion the issue is becoming more painful than before.

Here is a related issue: https://github.com/blockstack/blockstack.js/issues/498#issuecomment-406344575

**Comment by fluidvoice** [comment]
I tried building the wallet once (Linux binaries) on Linux but it failed to build. I think I saw this is fixed now though.  If I can get it to build I'll try that monkey-patch.

**Comment by fluidvoice** [comment]
I built the Linux binaries again on Ubuntu 19.10 VM but nothing would run (core dump). So not worth spending more time on I think. Will just wait for 2.0: https://github.com/blockstack/stacks-wallet/issues/120#issuecomment-638206708

**Comment by blockpac** [comment]
@muneeb-ali will Stack Wallet 2.0 have Linux support?

**Comment by markmhx** [comment]
I'm closing this out now that Stacks 2.0 has launched and BTC is no longer required for STX transactions.

Download new wallet here: https://www.hiro.so/wallet/install-desktop
