### ISSUE TITLE
Invalid Transaction - Lost STX

### ISSUE THREAD

**Issue by suspended** [blockstack/stacks-wallet#150]
Tried sending STX to another wallet - TX ID is d3325a625f49a7b23fdaf63a545b935958fa56c96163ad8631026647c9c2f6f8 

However, wallet says the transaction is Invalid but the 5055 STX I sent was not returned to me.

What is happening here?

**Comment by tazeemc** [comment]
Uh oh

**Comment by diwakergupta** [comment]
Seems to be confirmed. Either way please file an issue in blockstack/stacks-wallet repo if you feel something is amiss:

https://explorer.blockstack.org/tx/d3325a625f49a7b23fdaf63a545b935958fa56c96163ad8631026647c9c2f6f8
