### ISSUE TITLE
New Stacks Wallet

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#152]
With Stacking and Ledger support

**Comment by impe83** [comment]
Hi guys for small suggetions for the next version:
- add ETH as an additional fee for transfer token
- indicate the wallet version in the app itself
- have a mobile app version
when is planned the next release?
keep it up with the good work 👍

**Comment by markmhx** [comment]
@impe83 Thanks for your suggestions! 

We don't have a precise release date for the new wallet yet, but we're actively working on it and expect its release to correspond roughly with the launch of the Stacks 2.0 mainnet. 

[See our roadmap for updated details.](https://blockstack.org/roadmap)
