### ISSUE TITLE
Add persistence options to onboarding flow

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#153]
We should provide more options than just copying to the clipboard:

- Write it down
- Download / print
- Other?

**Comment by markmhx** [comment]
@jasperjansz Can you provide a link to the Figma designs you've created for review?

**Comment by jasperjansz** [comment]
@markmhx https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=772%3A21357

**Comment by markmhx** [comment]
That works for those who don't want to copy+paste. We don't want to add a download option as well?
