### ISSUE TITLE
Modify settings to reflect sidecar API configuration and add warning

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#161]
The settings need to indicate somehow that the user isn't configuring the URL for a node per se but rather a sidecar API that proxies a node.

We should also display a warning when configuring a new sidecar API that the user should double check that they trust the API or their STX holdings could be at risk.

![Screen Shot 2020-07-01 at 15.02.54.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/c2130573-c821-444f-b139-34e3b6155064)

**Comment by jasperjansz** [comment]
Designs: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=430%3A741

**Comment by kyranjamie** [comment]
Warning text has been added
