### ISSUE TITLE
stacks wallet hangs on loading

### ISSUE THREAD

**Issue by ali787878** [blockstack/stacks-wallet#166]
I want to send my stacks to binance but it hangs on loading.
I also have 0.0006 bitcoin thai is enough( blockstack site says).
Is there anyone have the same problem.Can you help me?
I need my money.

**Comment by markmhx** [comment]
@ali787878 Sorry for the delay. Are you still finding that the Stacks Wallet hangs while trying to send?

**Comment by richardxlin** [comment]
@markmhx Also seeing this issue on installation/boot up of wallet when attempting to restore a wallet with ledger nano s.

**Comment by markmhx** [comment]
@richardxlin is it possible you're experiencing the problem reported with https://github.com/blockstack/stacks-wallet/issues/124 more specifically?

**Comment by richardxlin** [comment]
@markmhx No, I just installed the wallet on a brand new laptop. I get the loading error on the first use screen. 
![image](https://user-images.githubusercontent.com/4763487/98974484-f4035500-24e2-11eb-9a4b-b96a1680d412.png)

**Comment by markmhx** [comment]
That does look to me like the same issue reported in https://github.com/blockstack/stacks-wallet/issues/124, just at the point of initial wallet authentication, not later during transaction signing (for users who had previously been able to authenticate successfully).
