### ISSUE TITLE
Ask users with BTC balances if they'd like to get the value out

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#167]
The wallet should detect upon update and open whether the user has a positive BTC balance (perhaps above a minimum amount e.g. $5) and ask them to submit their email address if they're interested in getting the value out. We can then use this email address to help them via customer support.

**Comment by markmhx** [comment]
It seems I forgot to assign you at the start of the sprint, though the sprint milestone was added. Feel free to remove from the current sprint if it doesn't fit into your current workload.

**Comment by jasperjansz** [comment]
Design: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1323%3A24546

Taking suggestions on copy tweaks, also for the secondary action. Maybe something definitive like "Discard my Bitcoin"?

**Comment by kyranjamie** [comment]
This task will require:
- deriving BTC addresses
- querying a blockchain explorer for their balance
- submitting their email to some endpoint

With Ledgers, the onboarding flow is to just get your STX addresses. A separate flow will be needed to see if Ledger users of the previous wallet have BTC funds.

**Comment by markmhx** [comment]
@jasperjansz Let's make sure to move this into "Design Review" next time instead of assigning for dev directly

**Comment by markmhx** [comment]
@jasperjansz do you want to update the above designs so the popup is within the context of the old wallet? It's showing in the new one, which is confusing.

**Comment by kyranjamie** [comment]
It isn't necessary to design a separate legacy wallet style modal. Just annotate that is demonstrative and to be built in the old wallet.

**Comment by jasperjansz** [comment]
we don't have old wallet designs

**Comment by yknl** [comment]
@aulneau designed the legacy wallet, he might have the design files

Given that it's a simple modal, it shouldn't be a lot of work. Though we need a server component to receive the submitted email address. 

Is the plan to push out a minor update to the wallet long before the launch of the new version? I don't see any reason for people to get the minor update if it coincides with the major release.

**Comment by markmhx** [comment]
I'm pushing this back to the backlog since we're evaluating this approach internally again.

**Comment by markmhx** [comment]
I'm closing this in lieu of https://github.com/blockstack/stacks-wallet/issues/131 which is under development.
