### ISSUE TITLE
Handle pending transactions within the wallet

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#169]
Work with @jasperjansz to come up with a nice way to present pending transactions once they've been sent.

**Comment by markmhx** [comment]
@kyranjamie got the design guidance you need here? And has it been added to Figma?

**Comment by kyranjamie** [comment]
Yeah we're good

**Comment by markmhx** [comment]
This is awaiting QA upon readiness of the basic testnet release build
