### ISSUE TITLE
Add Terms of Use prompt for new Stacks Wallet

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#171]
Show this prompt every time the user loads the wallet for the first time on a device. Legal needs to review content before release.

**Comment by markmhx** [comment]
@kyranjamie we don't show this anywhere in the new wallet yet, correct?

In the current / old wallet, we show it immediately upon app load. @fjl4 do we need to do that with an "Accept" prompt for legal reasons? Or could we simply provide a non-blocking option in the new wallet to view the Terms of Use?

**Comment by fjl4** [comment]
Yes, we should use an "accept" prompt where the user can't use the app without accepting.

**Comment by markmhx** [comment]
@fjl4 Should we bring over the exact same legal content available in the current wallet? Or modify it for this new release / Stacks 2.0?

**Comment by fjl4** [comment]
I'll need to revise the terms. Let's chat about it briefly.

**Comment by markmhx** [comment]
@kyranjamie want to preliminarily add the current wallet's terms here and we can replace once @fjl4 has a new draft for us?

**Comment by markmhx** [comment]
![Uploading image.png…]()

**Comment by markmhx** [comment]
Reopening since @fjl4 will provide updated content

**Comment by markmhx** [comment]
@kyranjamie new terms content attached here 

[Stacks Wallet TOU 12-21-2020.docx](https://github.com/blockstack/stacks-wallet/files/5726705/Stacks.Wallet.TOU.12-21-2020.docx)

**Comment by kyranjamie** [comment]
@markmhx we're not changing the company name already? 🤔

**Comment by markmhx** [comment]
🤷
