### ISSUE TITLE
[Design] Error state/flow for sending transactions

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#173]
[See original comment in Figma](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES?node-id=442:806#33966451).

We need to think about certain error flows when broadcasting transactions.

![image](https://user-images.githubusercontent.com/1618764/88071422-14925280-cb74-11ea-8fdf-28eea4291e35.png)

Clicking _Confirm and send_, a tx is broadcast to the sidecar API. Consider:

- user's internet connection is down
- there's a service outage with our sidecar API
- the user has sent funds from the same address in a different wallet client; would encounter `InsufficientFunds` error
- somehow we run into nonce errors

There are certainly more errors we could run into. So some generic way of displaying these is needed.

To alleviate any potential troubleshooting or support difficulties, we should allow users to view the actual error being returned from the API.

**Comment by jasperjansz** [comment]
Generic error: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1323%3A22328
Specific error: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1323%3A23239 (replace the copy after "because" with the reason)
