### ISSUE TITLE
Implement zxcvbn password strength indicator

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#180]
Not strong enough: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=300%3A165
Strong: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1323%3A25099

**Comment by kyranjamie** [comment]
Like the simplicity, though do we want to remove all the messages from zxcvbn? Some of them are pretty useful, communicating why it isn't strong enough, and not just that it isn't.

**Comment by markmhx** [comment]
Assigning back to @jasperjansz for clarification

**Comment by jasperjansz** [comment]
yep we can add them https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=300%3A165
