### ISSUE TITLE
Change "sign out" to "reset wallet" and implement confirmation step

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#181]
Copy change: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=220%3A6060
Reset confirmation step: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1323%3A25259

**Comment by kyranjamie** [comment]
Will be completed with reset flow.
