### ISSUE TITLE
Handle 'total' cost of a transfer being larger than available balance

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#196]
I have 0.5STX available and want to transfer the maximum amount. I enter 0.5, but the fees are added on top of that which results in me not having enough balance.

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/2cd957f2-a4b4-4ebe-9980-74472cf352bd)

**Comment by markmhx** [comment]
@kyranjamie is this addressed with the above commit already?

**Comment by markmhx** [comment]
@kyranjamie can we close this issue?
