### ISSUE TITLE
Use users' machine date and time preferences

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#199]
Up for discussion whether this is worth it. If it's trivial it might be a nice enhancement. Feel free to disregard and close this issue

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/39f2ef7f-e5c7-422c-8f39-c0a88643dc55)

For example, I use the European notation of 27 July 2020, 17:00 instead.

**Comment by kyranjamie** [comment]
I don't believe time and date settings specifically are known. These are typically inferred from a user's locale.

Would be worth discussing what level of locale-specific customisation we want to support.

**Comment by markmhx** [comment]
Let's discuss during sprint planning. I'm moving back to ready for design since we need to spec this out more it seems.
