### ISSUE TITLE
Integrate new STX icon for Ledger devices

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#202]
Create a 16x16 gif of the new STX logo

<details>
<summary>Old issue</summary>

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/5c37e742-5f14-4f77-9c46-913e3b4b011b)

https://github.com/Zondax/ledger-blockstack/blob/7d8e7ae60b30e513a3e3804664176c8b9c58e0e8/deps/ledger-zxlib/dockerized_build.mk#L85-L88

https://github.com/Zondax/ledger-blockstack/tree/7d8e7ae60b30e513a3e3804664176c8b9c58e0e8/app/glyphs
</details>

**Comment by jasperjansz** [comment]
![blockstack-white.gif](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/f07a1787-5d71-4487-9253-364e86df361c)

@kyranjamie

**Comment by kyranjamie** [comment]
This appears to just be a white square. Can you share Figma link? @jasperjansz

**Comment by jasperjansz** [comment]
try this
![stx-icon](https://user-images.githubusercontent.com/25477905/94695191-e8463f80-0335-11eb-838f-608f9ccb302d.gif)

**Comment by kyranjamie** [comment]
@markmhx this needs to be included with the ledger application

**Comment by markmhx** [comment]
By application, do you mean the submission for Ledger review? Or the BOLOS application created by Zondax?

**Comment by kyranjamie** [comment]
I was under the impression you upload it with application/submission?

**Comment by markmhx** [comment]
We uploaded Adobe Illustrator files as part of the submission. I believe this GIF needs to be added by Zondax to the BOLOS app, so I've asked @jleni about this in Slack.

**Comment by markmhx** [comment]
I've pinged @jleni about this on Slack

**Comment by kyranjamie** [comment]
Closed by https://github.com/Zondax/ledger-blockstack/pull/35

Will test now

**Comment by kyranjamie** [comment]
![image](https://user-images.githubusercontent.com/1618764/96722743-fffd6a80-13ad-11eb-8bc3-5316b2b3f748.png)

**Comment by markmhx** [comment]
📸

**Comment by markmhx** [comment]
It turns out we'll need to update this icon anyway with the new STX icon as seen at https://www.stx.design/.

<img width="233" alt="Screen Shot 2020-10-23 at 12 45 58" src="https://user-images.githubusercontent.com/28991/96994929-b50a6100-152d-11eb-9c7e-6376299248c1.png">

@jasperjansz can you provide new assets for Ledger integration here?

**Comment by jasperjansz** [comment]
![Ledger icon02](https://user-images.githubusercontent.com/25477905/98117321-d8c49400-1ea9-11eb-958d-0f26b69b3158.gif)
![Ledger icon01](https://user-images.githubusercontent.com/25477905/98117324-d95d2a80-1ea9-11eb-8079-4e3abf60371f.gif)

**Comment by markmhx** [comment]
This is completed
