### ISSUE TITLE
Sign transaction with Ledger flow

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#206]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=300%3A972

**Comment by markmhx** [comment]
@jasperjansz this is relevant only to Stacking, correct? Un-assigning @kyranjamie for now if that's the case since we haven't started on Stacking yet

**Comment by kyranjamie** [comment]
We use the same screen when signing a regular STX transaction as well.
