### ISSUE TITLE
Disconnect Ledger during onboarding 

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#207]

**Comment by jasperjansz** [comment]
If the user disconnects his Ledger during onboarding (or confirming a transaction), the UI should take them back to step 1 of this flow, disabling the button again and unchecking steps

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1625%3A49

**Comment by kyranjamie** [comment]
DOne
