### ISSUE TITLE
User trying to sign a transaction with a different Ledger

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#208]
Would this work? https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=1622%3A24445

Can we know before they click the button or would it be after? @kyranjamie

**Comment by kyranjamie** [comment]
@jasperjansz We can only check address at the very last step.

**Comment by markmhx** [comment]
@kyranjamie do you need this design updated accordingly? I'm not sure how to interpret this having to be at the last step. Presumably that it needs to be an error message shown after clicking "Confirm transaction" here?

**Comment by kyranjamie** [comment]
Correct.

Though, requesting a ledger's address is a separate device action. So, if we do want to show this specific error message, we'd require the user to: 1) Confirm their address, 2) Sign the transactions. 

Presume we don't want to do the first every time, so maybe this is an edge case we can ignore for now.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=2005%3A24496
