### ISSUE TITLE
Incorrect balance after transaction, fee not subtracted from wallet STX total only the  STX sent

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#209]
**Describe the bug**
Incorrect balance after transaction, if a user has 1 STX then sends .000001 STX and the fee of .00018 STX. The wallet shows the fee amount in the transaction history but the wallet Balance does not show that .000181 STX was subtracted from the wallet total.

The total currently displays  .999999 STX. 

The total reflect 1.0000 STX - .000001 STX = .999999 

when it should show 0.999999 - 0.000181 =. 999818

https://testnet-explorer.blockstack.org/txid/0x749a3769e1f2b954fa092fa911e07996346268a7d66df3dc4eac30d2685197e1?wallet=true

**To Reproduce**
1. Go to wallet
2. Send your self 1 STX through the faucet
3. Once the balance updates in your wallet send out .000001
4. See error in the balance

**Expected behavior**
The wallet should decrement the balance with the fee as well as the amount sent, this is currently NOT happening

**Screenshots**

<img width="1021" alt="Screen Shot 2020-08-04 at 2 56 36 PM" src="https://user-images.githubusercontent.com/49165468/89333804-81711680-d663-11ea-9928-5184dca97de2.png">

**Comment by timstackblock** [comment]
@kyranjamie is this going to be fixed

**Comment by timstackblock** [comment]
This is also still broken in the latest build as of Sept 18th

**Comment by kyranjamie** [comment]
![image](https://user-images.githubusercontent.com/1618764/93791612-bf86c180-fc34-11ea-958d-4281b050ddd5.png)

Sure it isn't working @timstackblock ?

**Comment by kyranjamie** [comment]
I've reintroducing polling every 15 seconds to update status of pending txs, so if websocket is connected you'll get immediate update, if it isn't, it'll still get correct balance eventually.

**Comment by timstackblock** [comment]
Thanks this is now fixed
