### ISSUE TITLE
Buy STX button doesnt work

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#211]
**Describe the bug**
Buy STX button doesn't work

**To Reproduce**
1. Go to the STX wallet
2. Click on the button that says BUY STX

**Expected behavior**
The button should open the appropriate link 

**Screenshots**
<img width="404" alt="Screen Shot 2020-08-04 at 3 26 11 PM" src="https://user-images.githubusercontent.com/49165468/89336623-ae272d00-d667-11ea-97d4-cc7fe2901241.png">

**Comment by jasperjansz** [comment]
Given that:
- users of the Wallet will be experienced with crypto
- familiar with CMC
- We don't want to create or maintain a webpage like this
- We don't want to maintain a list of exchanges in the Wallet UI

Think we can just link here: https://coinmarketcap.com/currencies/blockstack/markets

Thoughts?

**Comment by markmhx** [comment]
That sounds like a good plan for now at least

**Comment by kyranjamie** [comment]
Done. @timstackblock assigning back to you, will get a new build to you later this week

**Comment by timstackblock** [comment]
Sounds good

**Comment by whoabuddy** [comment]
This is working for me with the Linux build `v4.0.0-beta.3`, should this issue be closed?

**Comment by kyranjamie** [comment]
Yes, it can. Thanks for your feedback @whoabuddy
