### ISSUE TITLE
No reset button in new wallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#212]
The new wallet has no way to reset the wallet

**Is your feature request related to a problem? Please describe.**
We need a reset button in the new wallet like we had in the previous wallet

**Describe the solution you'd like**
<img width="950" alt="Screen Shot 2020-08-04 at 4 32 24 PM" src="https://user-images.githubusercontent.com/49165468/89342004-2abe0980-d670-11ea-882b-db62bbb29081.png">

**Comment by timstackblock** [comment]
I cannot test login without this feature because once I login I cannot reset the wallet to retest other scenarios. Even when I use the quit option or delete the app and reinstall I can never get back to the original starting point.

**Comment by kyranjamie** [comment]
Will add this soon. For now you can kill the config.json file `rm ~/Library/Application\ Support/Electron/config.json`

**Comment by markmhx** [comment]
Un-assigning @kyranjamie  for now since it's non-urgent / not in a sprint yet and the CLI command works to QA for now

**Comment by kyranjamie** [comment]
Feature has been added
