### ISSUE TITLE
Add memo field for sending

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#216]
- Memo field
- Can only have X byte length message

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=438%3A13363

**Comment by jeffdomke** [comment]
@diwakergupta i heard you say this is an important feature. Why?

**Comment by diwakergupta** [comment]
> @diwakergupta i heard you say this is an important feature. Why?

The memo field is currently being heavily used by some exchanges and their users. We should make sure nothing breaks for either of those parties as we transition from Stacks 1.0 to 2.0, and that there's no surprising behavior or unexpected loss of functionality.

Note that I care less about the prioritization, just that memos are supported. So as long as it's planned, I'm good.

**Comment by markmhx** [comment]
Good call on this; I don't actually see them in the designs yet.

**Comment by jasperjansz** [comment]
memo field design: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=438%3A13363
