### ISSUE TITLE
Create package files with Docker

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#217]
Owning to removal of 32-bit support in MacOS Catalina, it's not possible to create a Windows build of the wallet.

Use Docker to create a release files, see issue https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2362#issuecomment-668309279

**Comment by markmhx** [comment]
I'm not sure I understand the implications here re: Windows support?

**Comment by kyranjamie** [comment]
We need to be able to create Windows builds, and I'm unable to do so without a VM/Docker.

**Comment by markmhx** [comment]
Got it, so this doesn't have any UX implications

**Comment by markmhx** [comment]
@kyranjamie is this still relevant?

**Comment by kyranjamie** [comment]
Nope
