### ISSUE TITLE
Update designs to allow only one Stacking lock-up at a time

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#222]
Currently the designs allow the user to lock up several batches of STX in parallel. However, this capability won't be possible on a chain-level so we need to modify them to message and enforce only one lock-up at any given time.

**Comment by markmhx** [comment]
@jasperjansz adding this to the current sprint since you mentioned you'd already gotten through your workload and have capacity

**Comment by jasperjansz** [comment]
I propose we simply remove the 'Earn Bitcoin rewards' card when a user is already stacking:

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=435%3A2153

**Comment by kyranjamie** [comment]
Completed in https://github.com/blockstack/stacks-wallet/pull/262
