### ISSUE TITLE
Add Ledger/USB connection guidance for Linux builds to Ledger screen

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#231]
![Screenshot from 2020-09-11 11-24-38](https://user-images.githubusercontent.com/1618764/92912254-83c44e80-f421-11ea-9a4d-a3ee9bf69c42.png)

I'm new to the world of udev rules, this turns out to be an issue with permission of the mounted USB device. This can be fixed by running chmod or configuring your `/etc/udev/rules.d/` directory. [Electrum maintains a directory of these rules for hw wallets, including Ledgers.](https://github.com/spesmilo/electrum/tree/master/contrib/udev).

**Comment by markmhx** [comment]
Let's add a message conditionally for Linux builds only with guidance on how to set permissions to get Ledger to work here
