### ISSUE TITLE
When I enter my ledger 24 digit seed phrase directly into the software wallet it DOES NOT give me the same wallet address

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#235]
**Describe the bug**
Take the 24 word seed phrase you received with the hardwallet and enter it into the software wallets 24 seed phrase box. The decryption should always be the same. The user should see the same wallet address when they enter the wallet. This is NOT the case, we spoke about this in our stand-ups but it doesn't seem to work.
 
**To Reproduce**
1. Go to the wallet login with your ledger
2. Click on receive view the address and record it
3. Reset the wallet
4. Add the 24 word seed phrase in the soft wallet text box the wallet should open with the same address
5. You will see a different address when you enter the wallet

**Expected behavior**
We wanted to see the same address

**Comment by kyranjamie** [comment]
Cannot replicate this @timstackblock 

I did the following:

- Signed in with Ledger, recorded address
- Cleared wallet
- Signed in with Ledger seed phrase
- Immediately had balance, transaction and same address as on ledger Ledger

Are you certain your Ledger has the same seed as you put in? You can reset your device with the same seed phrase to make sure.

**Comment by timstackblock** [comment]
@markmhx  @kyranjamie 

This is still failing for me I tested this with 2 different Nano ledger hard wallets and saw the same results.
 I created a brand new seed phrase just to test this. The seed phrase below is a TEST wallet so feel free to restore it on your ledger.

Using the same seed phrase I see 2 different results.
TEST SEED PHRASE  NANO LEDGER S 
Address with ledger
ST3HNB2BXW3ZWGFQHNRWJ140G36PWKGTA3EZHCKQR
Address with soft wallet
ST31D2RX462WZ2GNB724D1B8AX65WWW42WZTDPWH0

SEED PHRASE
Prevent
Moral
Hen
Apology
Wide
Cram
Man
Bulk
Merge
Kangaroo
Month
Gossip
Number
Task
Pumkin
Try
Tornado
Deliver
Purity
Obscure
Bacon
Tongue
Meadow
Celery

SCREEN SHOTS OF BUG

 SOFTWALLET with the above seed phrase displays address ST31D2RX462WZ2GNB724D1B8AX65WWW42WZTDPWH0

<img width="1021" alt="Screen Shot 2020-09-15 at 11 01 36 AM" src="https://user-images.githubusercontent.com/49165468/93228131-28f16680-f743-11ea-98f8-eb3eebf3c2f0.png">
<img width="1018" alt="Screen Shot 2020-09-15 at 11 02 01 AM" src="https://user-images.githubusercontent.com/49165468/93228129-28f16680-f743-11ea-8e3f-28e08a8957c9.png">



Hard wallet is open with this address ST3HNB2BXW3ZWGFQHNRWJ140G36PWKGTA3EZHCKQR

![20200915_105859](https://user-images.githubusercontent.com/49165468/93229095-378c4d80-f744-11ea-9627-bdfaea236f06.jpg)
![20200915_105914](https://user-images.githubusercontent.com/49165468/93229085-33603000-f744-11ea-8d69-16c5d8c4a88d.jpg)
![20200915_110000](https://user-images.githubusercontent.com/49165468/93229090-3529f380-f744-11ea-8a65-f07d87c1191f.jpg)

**Comment by markmhx** [comment]
I'm also unable to recreate this with my Ledger Nano S. The same address gets pulled up either via manual entry or authorizing with the device.

@timstackblock could https://github.com/blockstack/stacks-wallet/issues/238 be implicated in this possibly? I see you've listed out your seed phrase with capitalization above whereas mine are all in lowercase from the Ledger device.

**Comment by timstackblock** [comment]
The two addresses in #238 are both different than the one I am getting with the ledger. Not sure what is causing the difference but I will keep digging.

**Comment by kyranjamie** [comment]
Using the seedphrase above, in lowercase `prevent moral hen apology wide cram man bulk merge kangaroo month gossip number task pumkin try tornado deliver purity obscure bacon tongue meadow celery`

I get the address: `ST3BCWXYH7MG73ZQK41DWKB7BHCTW2SPQCKC2J08B`

Can confirm this is accurate with cli

```
❯ blockstack-cli make_keychain -t "prevent moral hen apology wide cram man bulk merge kangaroo month gossip number task pumkin try tornado deliver purity obscure bacon tongue meadow celery"
{
  "mnemonic": "prevent moral hen apology wide cram man bulk merge kangaroo month gossip number task pumkin try tornado deliver purity obscure bacon tongue meadow celery",
  "keyInfo": {
    "privateKey": "49359fae5c86b607fddf86daaf5ea33af12a0c5eff23569394ca289e5814c1b601",
    "address": "ST3BCWXYH7MG73ZQK41DWKB7BHCTW2SPQCKC2J08B",
    "btcAddress": "n16kEkpnhMcodTHkxrAtn8KTxH4n2KKjrm",
    "index": 0
  }
}
```

I looked at the implementation of the legacy wallet. It uses `bip39.validateMnemonic()`, accord to that fn, this mnemonic is invalid

```
> bip.validateMnemonic('prevent moral hen apology wide cram man bulk merge kangaroo month gossip number task pumkin try tornado deliver purity obscure bacon tongue meadow celery')
false
```

**Comment by timstackblock** [comment]
Reset your ledger restore it with that seed phrase you will get a different address, this is the issue.

**Comment by kyranjamie** [comment]
I've started to restore this on my wallet. `pumkin` !== `pumpkin`.

**Comment by timstackblock** [comment]
You are correct the issue was the pumpkin !== to pumkin, thanks for checking on this. 

But this has uncovered another bug. When you used the seed phrase above I did not give you the password to access the wallet. It prompted you to  enter a password. You were able to enter any random password and access the wallet.  I have reproduced the issue below in this video.

http://somup.com/cYQD2tXCQz

**Comment by kyranjamie** [comment]
I kinda [explained this here](https://github.com/blockstack/stacks-wallet/issues/239#issuecomment-693265921).

The password is to encrypt the mnemonic on _your local machine_. It isn't used as part of the mnemonic generation. And, even if it were, using another password would just generate another wallet.

**Comment by timstackblock** [comment]
Got it but there still seems to be an issue. It doesn't seem to be encrypting it on my local machine. 

I am able to use multiple different passwords on my wallet. I can see why you can get into the wallet using a different machine but shouldn't there be password verification since I am on the same local machine?

**Comment by timstackblock** [comment]
closing this for #240
