### ISSUE TITLE
Using the same ledger with the OLD wallet and the new wallet generate 2 different addresses

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#237]
**Describe the bug**
Create a wallet using your ledger in the OLD wallet record the address, use the same ledger to create a wallet in the new stacks V2 wallet record the address. The address is different for both even though you are using the same ledger
**To Reproduce**
1. Go to old wallet select I have a ledger
2. A wallet is generate record your address
3. Go to the new wallet select I have a ledger
4. Record the address that is generate
5. Notice the wallets address are different

**Expected behavior**
I was expecting both wallet addresses to be exactly the same this is not the case

**Comment by markmhx** [comment]
This testing may need testnet genesis block assistance per https://github.com/blockstackpbc/devops/issues/490

**Comment by markmhx** [comment]
@timstackblock will this be testable pre-mainnet, perhaps with https://github.com/blockstackpbc/devops/issues/544, or will we have to test against mainnet?
