### ISSUE TITLE
Add bip39 mnemonic validation to Secret Key entry upon sign in

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#239]
**Describe the bug**
If a user gets 24 words and paste them into the soft wallet the wallet will open. This time I took a 12 word seed phrase and pasted it in 2 times. The wallet opened without issue, it seems as if it is creating a new wallet here instead of verifying if there is an existing wallet with the seed phrase. I can enter anything in for the password and I am taken into the wallet. This seems like a security issue, @markmhx what are your thoughts

VIDEO OF THE ISSUE
http://somup.com/cYQoomXgEC

**To Reproduce**
1. Go to the wallet click I have an existing wallet
2. Paste in these 12 words, 2 times to make 24 words  : Enable army radio upgrade athlete vibrant input expect repeat survey near track
3. I am then asked to enter a password, I can enter anything at all and then I go into the wallet and you will see that a new wallet was generated with the random seed phrase
4. Are we verifying that a wallet already exist or just generating a new wallet here, should we be able to do this?

**Expected behavior**
I would expect the wallet to reject the random seed phrase as no wallet with this seed phrase exist or atleast fail at the password screen as there is not password associated with this address.

**Comment by kyranjamie** [comment]
I'm not sure what we can do here. A 12-word seed phrase pasted twice is a valid 24-word phrase.

When restoring a wallet like this, the password you enter doesn't have to be the same as you used last time. It's just the password used to encrypt your seed phrase.

Note, it is possible to add a password to a mnemonic, [see spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed) where the password is used as a salt, meaning the same password _is_ needed to resolve the same key. This is not being used. Though, even if we were, you could still add any password. It'd just create another address.

We are not verifying a wallet exists, as by this I presume you mean it has funds? What if I want to restore a wallet I haven't used yet? How can the wallet determine what a "random seed phrase" is?

Note that when generating a wallet, nothing actually happens. We tell the users they've "created a wallet", but no state is changed anywhere. It's better to think in a way where, all possible wallets already exists. Generating a wallet is just finding a key for one of them.

**Comment by markmhx** [comment]
I agree with @kyranjamie here that it seems like expected behavior.

@timstackblock what happens in the current wallet? Do we handle this any differently?

**Comment by timstackblock** [comment]
The old wallet has several steps of validation that this new wallet build does seem to follow. I do not agree that this is expected behavior. The stacks wallet V1 wallet will not let you insert any random sequence of word that just so happen to decrypt into a valid Stack address, see the screen shots below.


**The new wallet will allow the random 12 word seed phrase, it then allows the user to enter a new password, it should actually be validating the password since I selected the option that I HAVE an existing wallet. Instead it lets me enter any password and goes into the wallet. This seems very broken to me, and also seems unsecure.**

<img width="1019" alt="Screen Shot 2020-09-16 at 8 30 08 AM" src="https://user-images.githubusercontent.com/49165468/93337522-3d8f3680-f7f7-11ea-9703-7bc45788e4a4.png">

<img width="1016" alt="Screen Shot 2020-09-16 at 8 30 17 AM" src="https://user-images.githubusercontent.com/49165468/93337518-3d8f3680-f7f7-11ea-9257-bd81ccbf6644.png">

**The old wallet will NOT accept this random 12 word seed phrase that I repeat 2 times, and gives an error message.**


<img width="915" alt="Screen Shot 2020-09-16 at 8 25 08 AM" src="https://user-images.githubusercontent.com/49165468/93337524-3e27cd00-f7f7-11ea-95b4-1415c9a5af81.png">

**Comment by markmhx** [comment]
Add bip39 mnemonic validation
