### ISSUE TITLE
Linux/Gnome context menus not opening

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#241]
When opening the context menu on a transaction item, using Fedora 23, it closes immediately prevent it from being used.

**Comment by markmhx** [comment]
@kyranjamie is this ready for QA? I see there has been more related commit activity since we first pushed into QA

**Comment by kyranjamie** [comment]
Yeah this is ready, these 👆  msgs are only owing to force pushed rebases I believe.

**Comment by markmhx** [comment]
@timstackblock mind taking a look?

**Comment by timstackblock** [comment]
Sorry @markmhx I did not update this ticket, I took a look last week and I cannot get context menus to open in the app.

**Comment by kyranjamie** [comment]
Only on Linux @timstackblock.

Surprised with this one as I actually fixed it when I created the issue 🤔

**Comment by timstackblock** [comment]
Yes only on linux

**Comment by markmhx** [comment]
@timstackblock to check on Ubuntu

**Comment by timstackblock** [comment]
Right clicking in Ubuntu when I am not in the wallet gives me a useable context menu.

<img width="872" alt="Screen Shot 2020-11-05 at 2 07 25 PM" src="https://user-images.githubusercontent.com/49165468/98285325-666ab700-1f70-11eb-826c-68e5875eab19.png">

Right clicking in Ubuntu when I am inside the stacks wallet does not give me a useable context menu all I can do is inspect element, no copy or paste options

<img width="816" alt="Screen Shot 2020-11-05 at 2 07 38 PM" src="https://user-images.githubusercontent.com/49165468/98285426-8601df80-1f70-11eb-94c5-726539d7e2dd.png">

**Comment by timstackblock** [comment]
Mac OS does the same thing so this is NOT a bug 

<img width="1017" alt="Screen Shot 2020-11-05 at 3 22 44 PM" src="https://user-images.githubusercontent.com/49165468/98292581-ea29a100-1f7a-11eb-8c28-d2bba5f929a2.png">

**Comment by markmhx** [comment]
@kyranjamie @jasperjansz should the user be able to right-click and paste a key value here?

**Comment by kyranjamie** [comment]
Yes, they should. 

This issue was always relating to whether the context menu worked on *transaction items*. But this is good feedback, cause there should definitely be std copy, cut, paste actions.

**Comment by markmhx** [comment]
Should we spin up a separate issue for the copy and paste action here?
