### ISSUE TITLE
NULL appears in the pop up when sending stacks with the softwallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#246]
**Describe the bug**

**To Reproduce**
1. Go to login using the softwallet
2. send stacks
3. when the screen pops up to enter your password you will see the works NULL

**Expected behavior**
The word NULL should not display 

**Screenshots**
<img width="486" alt="Screen Shot 2020-09-17 at 4 56 43 PM" src="https://user-images.githubusercontent.com/49165468/93527576-1162db00-f907-11ea-836d-97bb44291d5c.png">
<img width="1009" alt="Screen Shot 2020-09-17 at 4 56 33 PM" src="https://user-images.githubusercontent.com/49165468/93527578-1162db00-f907-11ea-903e-e2bf51824036.png">

**Comment by kyranjamie** [comment]
Hey @timstackblock make sure [you're using the latest build here](https://github.com/blockstack/stacks-wallet/runs/1129224981)

**Comment by timstackblock** [comment]
Thanks @kyranjamie
