### ISSUE TITLE
Stacks Wallet 2.0 app icons

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#247]
The previous wallet used an unpadded Blockstack logo as the app icon, which results in an app icon larger than all its surrounding icons (MacOS).

The new wallet needs an application [icon, ideally inline with the MacOS Big Sur app icon guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

[Here's a figma template with the Big Sur rulers](https://www.figma.com/file/ddzopOSknzKKU8EveMHVpk/macOS-Big-Sur-Icon-Template-Community?node-id=0%3A1).

You can find some more information on the [assets required for each platform on the Electron builder website](https://www.electron.build/configuration/configuration)

Considerations, especially around icon padding, need to be taken for other platforms, though we can likely reuse the icons.

Hope you like my attempt we'll use in the meantime

![image](https://user-images.githubusercontent.com/1618764/93579478-cd231980-f99e-11ea-8a84-eb6f386b8e7a.png)

**Comment by markmhx** [comment]
We need to update this icon with the new Stacks logo.

**Comment by kyranjamie** [comment]
We need two variants: mainnet and testnet wallet versions, just an alternate colour something similar to Chrome, Chromium, Chrome Beta, Nightly etc

**Comment by jasperjansz** [comment]
Got 2 alts here: https://www.figma.com/file/os7gDXGBZCT08FlZyweYua/Wallet-icon?node-id=0%3A1
