### ISSUE TITLE
[4.0.0-beta.2] Bug: commit link in the wallet doesn't work

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#251]
Bug found testing Stacks Wallet build 06530c6, Mon Sep 21 16:21:32 UTC 2020.

<img width="1430" alt="Screen Shot 2020-09-22 at 10 05 01 AM" src="https://user-images.githubusercontent.com/49165468/93893190-5b5b1080-fcbb-11ea-9762-1da670e4b775.png">

**Comment by kyranjamie** [comment]
Removed this element
