### ISSUE TITLE
[4.0.0-beta.2] Bug: infinite spinner when clicking max amount button on send screen

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#252]
Video of bug http://somup.com/cYQ32IXLHa

Bug found testing Stacks Wallet build 06530c6, Mon Sep 21 16:21:32 UTC 2020.

<img width="848" alt="Screen Shot 2020-09-22 at 10 13 24 AM" src="https://user-images.githubusercontent.com/49165468/93894147-65c9da00-fcbc-11ea-90c0-b37abbc8569e.png">

**Comment by markmhx** [comment]
@kyranjamie do we have an outstanding PR for this issue to link?

**Comment by markmhx** [comment]
This appears resolved to me

![image](https://user-images.githubusercontent.com/28991/99077083-7f044e00-25bc-11eb-84e0-1ea0890799c3.png)
