### ISSUE TITLE
Support 12-word Secret Keys for sign in

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#253]
In the new wallet, it's important that we support 12-word Secret Keys in addition to 24-word ones so that existing Trezor users can easily migrate to software mode upon the release of Stacks 2.0, when Trezor support is likely unavailable anymore.

We should simply allow 12-word key entry upon sign in at the very least. Additionally, we may want to add the following guidance to the UX for any user who enters such a 12-word key:

- Perhaps only conditionally if there is no balance, the user should be advised that they may have intended to use a separate 24-word key to check their STX investment as made previously with CoinList. This guidance would help prevent users from using a 12-word key they generated in the browser for Blockstack apps to check their separate STX investment, only to get scared by not seeing any or many funds associated with the 12-word key.
- The user should be pointed to App.co if they're looking to use their key with Blockstack apps, not just manage their STX holdings.
- The user should be advised to handle their 12-word key with care when entering it into the web browser at any time, always checking the webpage URL first to ensure they aren't getting phished.

The new wallet should continue generating just 24-word keys. Only sign in should support both 12 and 24-word keys.

**Comment by markmhx** [comment]
@jasperjansz I'm assigning this to you for design so you can consider the guidance points in particular and just how you may want to handle them in the UI.

**Comment by markmhx** [comment]
@timstackblock and @yknl have researched Trezor key extraction some more and it appears that it is actually possible for Trezor users to extract 24-word seeds and not just 12-word ones. So we wouldn't need this change for Trezor migration per se, but we may want to support it for other purposes.

Since those other purposes aren't as high priority, I'm moving this out of the sprint.

**Comment by markmhx** [comment]
@kyranjamie I believe you mentioned that @timstackblock could QA this functionality alongside a Stacking fix or change? Mind linking that here?

**Comment by kyranjamie** [comment]
Can be tested alongside https://github.com/blockstack/stacks-wallet/pull/375

**Comment by Postscape** [comment]
Sorry came here from trying to send out using a Trezor T - Sounds like restoring using seed phrase in 3.0 is the way to go. Looks like 12 word is going to be supported in next release?

**Comment by markmhx** [comment]
Yep the next release will support 12-word Secret Keys. 

Unfortunately the Trezor T doesn't work with the Stacks Wallet v3.0. See https://www.blockstack.org/questions/which-hardware-wallets-are-supported-by-the-stacks-wallet-v3-x

**Comment by markmhx** [comment]
We'll test this once we have 1.0 data on testnet to confirm balances with existing Trezor devices.

**Comment by timstackblock** [comment]
I was able to restore a 12 word seed phrase on a ledger and now my ledger and trezor both open the same wallet. But when I enter the 12 word seed phrase into the wallet I get this screen.

<img width="1020" alt="Screen Shot 2020-12-21 at 1 44 07 PM" src="https://user-images.githubusercontent.com/49165468/102811392-46158100-4393-11eb-9445-4354a0d7d1aa.png">

**Comment by markmhx** [comment]
The above is getting fixed with https://github.com/blockstack/stacks-wallet/pull/422

**Comment by markmhx** [comment]
@timstackblock does this need further QA?

**Comment by timstackblock** [comment]
@jeffdomke this is the thread I was looking for, after seeing this I think you are right we need to have the user count off there seed phrase and see if its 13 words, but 12 should def work
