### ISSUE TITLE
Build a library for Stacking-related utilities

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-wallet#255]
As we work on Stacking integration, we will build JS interfaces that utilize stacking. The goal is to build something that is easily integrated into UI.

Functionality will include things like:
- Locking STX with appropriate params (i.e. BTC Address)
- Querying for locked STX

**Comment by markmhx** [comment]
@hstove is this still under development or can we close out the base library work now that we have Stacking integrated into a wallet build?
