### ISSUE TITLE
More helpful password requirement error messages

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-wallet#260]
Password requirement error message says password needs to be longer than 12 characters when the entered password is longer than 12 chars. 

![image](https://user-images.githubusercontent.com/29081231/94285838-3ddbb000-ff22-11ea-9339-6d979e1eccc6.png)

**To Reproduce**
1. Create new wallet
2. Enter new password: "stackswallet123"
3. See error message 

**Expected behavior**
A more helpful message indicating that it's the complexity of the password not the length that's the problem.

**Comment by markmhx** [comment]
@kyranjamie do you want guidance from @jasperjansz on this or can resolve on your own?

**Comment by kyranjamie** [comment]
I'm sure I can figure this one out.
