### ISSUE TITLE
[4.0.0-beta.3] Bug: Faucet issue

### ISSUE THREAD

**Issue by MichelLeideson-Pain** [blockstack/stacks-wallet#261]
Bug found testing Stacks Wallet build 3e97a15, Thu Sep 24 16:43:50 CUT 2020.

![image](https://user-images.githubusercontent.com/59208830/94310000-4eeee600-ff4f-11ea-9254-316603a49bda.png)

When clicking on get testnet stx I am not getting any feedback as well as the STX

**Comment by markmhx** [comment]
@kyranjamie I assume this is due to an underlying issue with the API and not client-side, given what I'm seeing in Discord?

**Comment by kyranjamie** [comment]
Ideally we'll display in bound transactions, but the issue with it not arriving is to do with the API/faucet issues.

**Comment by whoabuddy** [comment]
I'd like to see a link to the transaction in the explorer underneath the buttons, or listed in the box below with a status of pending that updates to confirmed. That way I'm not tempted to click the button over and over again :slightly_smiling_face:

**Comment by markmhx** [comment]
@kyranjamie is there a way to hit the API after the user requests faucet STX to load the related pending transaction into activity?

**Comment by kyranjamie** [comment]
We poll for changes, so it should be eventually correct without the need for this.

But there is certainly more we can do, re displaying inbound mempool txs;

**Comment by markmhx** [comment]
The polling doesn't seem to update activity for me? This is after 30 minutes wait after requesting the faucet:

<img width="674" alt="Screen Shot 2020-09-29 at 12 46 54" src="https://user-images.githubusercontent.com/28991/94549071-edca5980-0251-11eb-98ea-cdc38750aba7.png">

**Comment by MichelLeideson-Pain** [comment]
When I'm sending or receiving if the activity is pending, if I close the wallet and open the transaction that was being carried out, it disappears.
![Pendente](https://user-images.githubusercontent.com/59208830/94612324-55e06600-0279-11eb-9eb8-e020e8a91336.png)
![NaoExiste](https://user-images.githubusercontent.com/59208830/94612338-5aa51a00-0279-11eb-8105-80374eed0334.png)

**Comment by MichelLeideson-Pain** [comment]
> @kyranjamie Presumo que seja devido a um problema subjacente com a API e não do lado do cliente, dado o que estou vendo no Discord?



> @kyranjamie Presumo que seja devido a um problema subjacente com a API e não do lado do cliente, dado o que estou vendo no Discord?


Possibly should is pointing to some different api call

**Comment by MichelLeideson-Pain** [comment]
> @kyranjamie Presumo que seja devido a um problema subjacente com a API e não do lado do cliente, dado o que estou vendo no Discord?


Possibly should is pointing to some different api call

**Comment by kyranjamie** [comment]
Thanks @MichelLeideson-Pain, tracked in https://github.com/blockstack/stacks-wallet/issues/267

**Comment by markmhx** [comment]
I tried again today and got this error in the console:

<img width="1456" alt="Screen Shot 2020-09-30 at 11 48 00" src="https://user-images.githubusercontent.com/28991/94670421-d2735300-0312-11eb-84b0-13b30ed27802.png">

**Comment by MichelLeideson-Pain** [comment]
> Obrigado @ MichelLeideson-Pain , rastreado em [# 267](https://github.com/blockstack/stacks-wallet/issues/267)


Glad to help!

**Comment by MichelLeideson-Pain** [comment]
![image](https://user-images.githubusercontent.com/59208830/95131145-f6300200-0733-11eb-9fa1-20d43e6a6ab3.png)
Getting error when trying to send STX to another address

**Comment by markmhx** [comment]
@MichelLeideson-Pain That error message suggests you have signed into the wallet with a different Ledger or Secret Key than the one you're attempting to use for transaction signing.

Can you try going to "Settings" and resetting the wallet, then sign back in and try the transaction once more?

**Comment by MichelLeideson-Pain** [comment]
> @ MichelLeideson-Pain Essa mensagem de erro sugere que você se inscreveu na carteira com um Razão ou Chave Secreta diferente daquele que está tentando usar para a assinatura da transação.
> 
> Você pode tentar ir em "Configurações" e redefinir a carteira, em seguida, entrar novamente e tentar a transação mais uma vez?


I'll analyze it because I only have one secret key
