### ISSUE TITLE
Linux .deb installer needs a description

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-wallet#263]
**Is your feature request related to a problem? Please describe.**

When opening the .deb installer, it shows a period `.` for the description. 

**Describe the solution you'd like**

It would be nice if it at least displays the description from the website, and maybe a note with the version ` v4.0.0-beta.3` and that this is in beta / on Krypton testnet.

> Easily send and receive tokens on the Blockstack Network.

**Describe alternatives you've considered**

Options I see:
- don't update it, but I think it's nice to have a description when installing software
- update it after release, when Stacks 2.0 is complete
- have it pull info from github when the releases are built (fancy)

**Additional context**

Screenshot of the package installer:

![Screenshot from 2020-09-28 07-18-35](https://user-images.githubusercontent.com/9038904/94444633-613d6f80-015b-11eb-8623-091e82265955.png)

Screenshot of the MS Teams "preview" installer:

![Screenshot from 2020-09-28 07-26-15](https://user-images.githubusercontent.com/9038904/94445144-f50f3b80-015b-11eb-9d15-3e7e950ee4b6.png)

They're calling it a preview because:

> Today, Microsoft announced a public preview of Microsoft Teams for Linux, the first Office 365 tool that's available for the open-source operating system. The hope is that by making it available for preview, the company can get feedback from the community and improve it before it becomes generally available.

**Comment by kyranjamie** [comment]
![Screenshot from 2021-01-11 09-47-45](https://user-images.githubusercontent.com/1618764/104166247-6664b880-53f2-11eb-86b5-049b436a3c2a.png)
Working on Fedora, closing this out @whoabuddy - feel free to reopen if it's not working on Mint
