### ISSUE TITLE
Fix icon for Linux application

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-wallet#264]
**Is your feature request related to a problem? Please describe.**

After installation, the entry `Stacks Wallet Beta` is added to my menu on Linux Mint, but no icon is included.

**Describe the solution you'd like**

I'd like to see a Blockstack icon (as you can see in the screenshot at the bottom - the old app actually had an electron icon by default). The periwinkle version would work well for light/dark mode on various OSes.

**Describe alternatives you've considered**

Options I see:
- leave it without an icon
- wait until a new icon for stacks comes out with the branding

**Additional context**

![20200928_001_Selection](https://user-images.githubusercontent.com/9038904/94446307-4f5ccc00-015d-11eb-84f7-52d846b0c9d3.png)

Similar to #247 but on the Linux side :slightly_smiling_face:

**Comment by kyranjamie** [comment]
Thanks @whoabuddy 

Indeed, I've had some trouble getting the icons working on various linux distros. Hadn't tried Mint.

This will be fixed with the new Stacks icon, for sure.
