### ISSUE TITLE
When sending the BTC out of the wallet with a Ledger, the transaction hash does not show

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#266]
**Describe the bug**
When sending the BTC out of the wallet with a Ledger, the transaction hash does not show on the confirmation page, 

**To Reproduce**
1. Go to  the wallet and connect with a ledger 
2. Click on the button to send the BTC transaction out of the wallet 
3. Confirm the transaction on the ledger
4. See error on the confirmation page 

**Expected behavior**
The transaction ID should display you will see the missing data in the screenshot below, I can see the transaction went through https://www.blockchain.com/btc/address/17KxTYz2PoG7ALDj1LmJsNEJSRxs9cEso

**Screenshots**
<img width="1003" alt="Screen Shot 2020-09-29 at 12 39 22 PM" src="https://user-images.githubusercontent.com/49165468/94588543-063a7400-0252-11eb-9f8c-d8bf45d7e836.png">

<img width="1034" alt="Screen Shot 2020-09-29 at 12 50 07 PM" src="https://user-images.githubusercontent.com/49165468/94588758-587b9500-0252-11eb-8597-b0c199936749.png">

**Desktop (please complete the following information):**
 - LEDGER NANO S

**Comment by yknl** [comment]
Addressed in https://github.com/blockstack/stacks-wallet/pull/228/commits/883736cbc7cd792a916ea5e60366032d8d565bca
