### ISSUE TITLE
"No input at index -1" error appears while sending BTC with the windows software wallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#268]
**Describe the bug**
I cannot sent BTC out of my software wallet in windows. I hit this no input at index 1 error appears while sending BTC with the windows software wallet

**To Reproduce**
1. Go to bitcoin wallet
2. Click on withdrawal BTC
3. Scroll down to enter address then hit send the user is asked to confirm the secret key, enter a valid secret key and hit confirm 
4. See error in screen shot

**Expected behavior**
BTC should send without issue

VIDEO OF BUG: http://somup.com/cYQvoYl6tQ

**Screenshots**
![image (12)](https://user-images.githubusercontent.com/49165468/94705910-8ffc4700-030f-11eb-99b7-72e897e93973.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Version [3.1.0]

**Comment by yknl** [comment]
Addressed in https://github.com/blockstack/stacks-wallet/pull/228/commits/bf5d5f860a3be3e73171765948bde1f69a52e16c
