### ISSUE TITLE
[4.0.0-beta.3] Bug: Fallback transaction status polling broken

### ISSUE THREAD

**Issue by lisimu** [blockstack/stacks-wallet#271]
![stx](https://user-images.githubusercontent.com/59280053/94921767-7c0d3c80-04eb-11eb-8955-9fe8b2444f54.jpg)

**Comment by lisimu** [comment]
always pending

**Comment by markmhx** [comment]
@lisimu how long has this been pending more or less by now?

**Comment by lisimu** [comment]
always ，
until you restart wallet。


| |
dd
|
|
邮箱：limaoking@163.com
|

Signature is customized by Netease Mail Master

On 10/02/2020 21:09, Mark Hendrickson wrote:

@lisimu how long has this been pending more or less by now?

**Comment by lisimu** [comment]
What’s the fault?


| |
dd
|
|
邮箱：limaoking@163.com
|

Signature is customized by Netease Mail Master

**Comment by zone117x** [comment]
Mempool appears stuck. See the tx timestamps in https://stacks-node-api.blockstack.org/extended/v1/tx/mempool

A PR is in review for a temporary work-around https://github.com/blockstack/stacks-blockchain-api/pull/270

**Comment by kyranjamie** [comment]
There is a bug wallet side here, the fallback url is malformed so always fails.

Didn't notice this in testing as most the time, a failed response is expected.
