### ISSUE TITLE
Add prompt for automatic updates

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#274]
We should include the ability for the new Stacks Wallet to prompt the user upon load whenever there is a new version available, informing them of the changelog and giving them the option to install the update and restart the wallet.

@kyranjamie is design guidance necessary here or can you use standard elements?

**Comment by kyranjamie** [comment]
Design input always welcome.

More pertinently, curious for input on how to implement this. Maybe we can use the Github API to check if there's a newer release?

Linking off to to the release page/download page when that's the case would be quite straightforward. I imagine an inline update ala VS Code/Figma would be a little more involved.

**Comment by kyranjamie** [comment]
[Relevant article](https://medium.com/@johndyer24/creating-and-deploying-an-auto-updating-electron-app-for-mac-and-windows-using-electron-builder-6a3982c0cee6), though not sure we want to implement this flow exactly.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=3343%3A24518

I added a checkbox the user can toggle to enable automatic updates

**Comment by kyranjamie** [comment]
Having a modal open immediately when you open/sporadically when using the app is annoying.
I'd suggest showing a little "Update available" icon in the toolbar, or somewhere on home screen, prompting the user to update, but without getting in the way of what they might be doing.

Also, I don't think the initial release of an update notification feature should include auto-update. I'm not aware of any wallets that have this feature, primarily owing to the security risks it may present.

**Comment by markmhx** [comment]
Obvious but non-blocking message when there's a new version that links directly to download the new version and install on their own

**Comment by jasperjansz** [comment]
Added a header state here: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=3477%3A6979

This link would take you to github/wallet site
