### ISSUE TITLE
Edit description with more information about Secret Keys during registration

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#275]
Per @ryanarndtcm's suggestion [here](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES?node-id=772:21524#42941165), making use of the provided copy suggestions and content found in the current web-based FAQ (but instead incorporating it all into the UI directly).

<img width="595" alt="Screen Shot 2020-10-06 at 14 11 59" src="https://user-images.githubusercontent.com/28991/95199953-e967e880-07dd-11eb-98b8-8ee92e04f912.png">

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=772%3A21357
