### ISSUE TITLE
[4.0.0-beta.4] Bug: GET TESTNET STX button is not sending stacks into the wallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#281]
**Describe the bug**
GET TESTNET STX button is not sending stacks into the wallet

**To Reproduce**
1. Go to the wallet 
2. Click on GET TESTNET STX button 
3. Scroll down to balance wait a few minutes, then go to the CLI and manually send STX to your wallet
4. See error, the STX you manually sent will appear but the GET TESTNET STX never come into your wallet

**Expected behavior**
The GET TESTNET STX button worked before Krypton there may be some simple integration issues

**Screenshots**
<img width="1006" alt="Screen Shot 2020-10-20 at 9 41 06 AM" src="https://user-images.githubusercontent.com/49165468/96594357-846dc180-12b8-11eb-914e-0a6d63599d5c.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 10.14.6]
 

**Additional context**

Bug found testing Stacks Wallet build 7276ee2, Tue Oct 20 11:46:29 UTC 2020.

**Comment by markmhx** [comment]
Want to check the console to see if you're getting the same server error as reported here? https://github.com/blockstack/stacks-blockchain/issues/1953

**Comment by timstackblock** [comment]
@markmhx its a different bug with a different error

**Comment by markmhx** [comment]
I'm seeing that the "Get testnet STX" button works for me today fwiw:

![image](https://user-images.githubusercontent.com/28991/96716320-2ec31300-13a5-11eb-8c8b-86fe99a1acfe.png)

**Comment by timstackblock** [comment]
Yeah it works after a transaction has been put through it doesn't work on the initial download of the wallet. So in my screen shots below I tried to send STX to the wallet with the faucet button and did not receive them. Then I did a token transfer into the wallet and tried again and it worked. There is something wrong with the initial state of the wallet.

<img width="1006" alt="Screen Shot 2020-10-20 at 9 41 06 AM" src="https://user-images.githubusercontent.com/49165468/96717145-07078700-1374-11eb-9f18-782c3a849ca4.png">

**Comment by kyranjamie** [comment]
I'm not entirely clear what's going on here.

The `Get testnet STX` is a quick and dirty implementation, it's for testing purposes only. It only fires off a request to the faucet, nothing more.

Is this an issue with the refreshing of the wallet? If, with a new wallet, you request the faucet, and again nothing appears, and you do a CMD+R (test mode only), do the balances appear?

**Comment by timstackblock** [comment]
@markmhx I think you may be using an older version of the wallet the button should have a faucet image on it and it should send 3,000,000 now. Can you delete your current version of the wallet download the new one and then hit the GET TESTNET STX button. You should see the issue, if you don't we can close it out and I will retest when the new build is released.

<img width="1013" alt="Screen Shot 2020-10-21 at 8 13 04 AM" src="https://user-images.githubusercontent.com/49165468/96718141-92354c80-1375-11eb-90ad-1bbacf086228.png">

The button works after I have sent a CLI transaction into the wallet but didn't work upon initially opening the wallet. Similar to the way that I could not send STX out of the wallet initially and had to hit cancel and back out and then I was able to send STX out of the wallet. There is an error in the initial state of the wallet, if this is a valid bug than any testnet user will run into it upon download.

**Comment by markmhx** [comment]
I removed the wallet, re-installed the latest build and see the faucet request come through on a newly generated address:

![unknown](https://user-images.githubusercontent.com/28991/97008620-5a7bff80-1543-11eb-8034-deb76ac223d7.png)

**Comment by timstackblock** [comment]
Sure we can close this out. 

There was a WEBSOCKET errors that appeared in console upon initial installation of the wallet.  This is what prevented a faucet request from completing when I opened the build. It has worked for me afterwards but there was definitely something strange occurring initially, we can come back to this ticket if it happens again.


<img width="1025" alt="Screen Shot 2020-10-20 at 9 08 10 AM" src="https://user-images.githubusercontent.com/49165468/97014155-fabc2f00-1517-11eb-81c3-7172a33740c7.png">

**Comment by kyranjamie** [comment]
Alright, great. 

The WebSocket error shouldn't affect the faucet, btw. Thought, it will error if it fails to connect.
