### ISSUE TITLE
[4.0.0-beta.4] BLOCKING Bug: Stacking password verification error, user cannot stack

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#282]
Bug found testing Stacks Wallet build 7276ee2, Tue Oct 20 11:46:29 UTC 2020.

**Describe the bug**
This is a BLOCKING Bug I cannot access any of the stacking features and complete any testing until this is fixed. Stacking password verification is broken, user cannot stack, valid password rejected

**To Reproduce**
1. Go to wallet select the button to start stacking
2. Click on choose a duration, add a valid address and Select the CONFIRM & LOCK button to start stacking
3. User is asked there wallet password, use the same password that you use to send a transaction this is the ONLY wallet password and should work.
4. See error, the correct password is rejected, there is a bug with password verification in the wallet which BLOCKS any stacking from happening. I successfully sent a transactions in the video below then went into the stacking page and got rejected using the same password.

**Expected behavior**
The stacking page should work with the wallet password as expected and this should NOT block a user from using the stacking page.

**Video of bug** 
http://somup.com/cY6Y2xlKyq

**Screenshots**
<img width="983" alt="Screen Shot 2020-10-20 at 10 32 16 AM" src="https://user-images.githubusercontent.com/49165468/96602453-07931580-12c1-11eb-8635-40cc844185be.png">

**Desktop (please complete the following information):**

**Comment by kyranjamie** [comment]
Hey @timstackblock—fixed in latest builds.

I'm sure there are some (other) error states not handled by UI properly, so your help finding them is appreciated

**Comment by timstackblock** [comment]
@kyranjamie The last build failed, there is no artifact.

<img width="1409" alt="Screen Shot 2020-10-22 at 9 50 30 AM" src="https://user-images.githubusercontent.com/49165468/96881368-325da500-144c-11eb-935f-464f82b56693.png">
<img width="1416" alt="Screen Shot 2020-10-22 at 9 50 08 AM" src="https://user-images.githubusercontent.com/49165468/96881370-32f63b80-144c-11eb-8ddb-66f06b1387ae.png">

**Comment by kyranjamie** [comment]
Investigating

**Comment by timstackblock** [comment]
fixed
