### ISSUE TITLE
[4.0.0-beta.4] Development-time dll build issue

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#283]
`Uncaught SyntaxError: Invalid or unexpected token` being throw in the `renderer.dev.dll.js:365240` file.

The following code is being included in the bundle, which is missing a `require()` wrapper, resulting in a clear syntax error.

```ts
module.exports = @blockstack/stacks-transactions;
```

**To recreate**

Run `yarn build-dll && eslint dll/renderer.dev.dll.js --no-ignore`

```

/Users/kyran/dev/blockstack/stacks-wallet/dll/renderer.dev.dll.js
  364173:17  error  Parsing error: Expression expected

✖ 1 problem (1 error, 0 warnings)

```

**Comment by kyranjamie** [comment]
@yknl are you aware of any bundling issues with the tx lib? I'm really not sure where this issue lies.

**Comment by yknl** [comment]
I have not seen this error before. Can you try with `@stacks/transactions`?

**Comment by markmhx** [comment]
What's this error affecting exactly?

**Comment by kyranjamie** [comment]
It doesn't actually breaking anything, but it is still a problem.

**Comment by markmhx** [comment]
_A problem with no consequences_

**Comment by kyranjamie** [comment]
Errors being thrown in the console doesn't look pretty 👗
