### ISSUE TITLE
Display state of current stacking cycle

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#285]
When a user is stacking, their current status should be clearly communicated.

**Comment by markmhx** [comment]
@kyranjamie do we have design guidance for this?

**Comment by kyranjamie** [comment]
We do not. 

As briefly mentioned before, I think this'd be a great opportunity to use a dot ("block") matrix visualisation. Where each dot/square represents a block of cycle.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=3477%3A9549

**Comment by markmhx** [comment]
I believe we have a solution in place for this for now.
