### ISSUE TITLE
Round up the stacking amount to limit the long decimal place, per Mark's request

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#286]
Place holder for the change to the stacking amounts decimal places. The question arose in Discord so pulling it into an issue to track it.

<img width="510" alt="Screen Shot 2020-10-21 at 8 39 47 AM" src="https://user-images.githubusercontent.com/49165468/96726305-d3325e80-137f-11eb-8627-4fa67095a649.png">

<img width="399" alt="Screen Shot 2020-10-20 at 10 54 13 AM" src="https://user-images.githubusercontent.com/49165468/96726340-dd545d00-137f-11eb-9b4b-7462a66634ce.png">

**Comment by psq** [comment]
the node currently rounds in 10_000 STX (not mSTX) increments (https://github.com/blockstack/stacks-blockchain/blob/master/src/core/mod.rs#L72)

**Comment by timstackblock** [comment]
this is merged closing fix
