### ISSUE TITLE
When stacks are locked and the available amount is set to 0, the Max Amount button  includeds locked amount  

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#287]
**Describe the bug**
After I successfully lock STX I have 0 available STX and cannot sent STX out of my wallet but the wallet allows the user to enter an amount greater than is listed as available. When they select Max Amount the value that is populated includeds locked STX

**To Reproduce**
1. Lock all the STX in your wallet so you have 0 available 
2. Select send and attempt to send 200 STX
3. This is allowed but fails at the end with a "Transaction failed to verify" message
4. Select sent then this time click Max Amount which should be the Max available
5. You will notice that all the locked STX are added into the send transaction

**Expected behavior**
The wallet should exclude locked STX from being sent

**Screenshots**
<img width="1023" alt="Screen Shot 2020-10-22 at 12 40 50 PM" src="https://user-images.githubusercontent.com/49165468/96904909-ba03dd80-1465-11eb-920c-f5b77a28a489.png">
<img width="1007" alt="Screen Shot 2020-10-22 at 12 41 10 PM" src="https://user-images.githubusercontent.com/49165468/96904911-bbcda100-1465-11eb-8cba-90c3b9e2cdd0.png">
<img width="1014" alt="Screen Shot 2020-10-22 at 12 41 20 PM" src="https://user-images.githubusercontent.com/49165468/96904914-bc663780-1465-11eb-902f-a1f5e53e83b4.png">

**Desktop (please complete the following information):**
 - OS: [ iOS]

**Comment by markmhx** [comment]
@kyranjamie mind linking the relevant PR here?

**Comment by kyranjamie** [comment]
https://github.com/blockstack/stacks-wallet/pull/293
