### ISSUE TITLE
After Stacking is completed lower right BUY STACKS box disappears from wallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#288]
**Describe the bug**
After Stacking is completed and the user leaves the stacking page and comes back into the wallet the lower right BUY STACKS box disappears from wallet

**To Reproduce**
1. Lock your STX successful
2. Go back to the wallet
3. You will see a white space in the right side of the wallet where the prompt to buy STX or lock your STX was located

**Expected behavior**
After Stacking is completed lower right BUY STACKS box disappears from wallet. The user should see a box that asks them if they would like to buy STX or if they have enough would they like to GET STARTED and lock STX again

**Screenshots**
<img width="1025" alt="Screen Shot 2020-10-22 at 12 56 40 PM" src="https://user-images.githubusercontent.com/49165468/96905310-47473200-1466-11eb-9961-c123fb96a498.png">

<img width="1013" alt="Screen Shot 2020-10-21 at 8 13 04 AM" src="https://user-images.githubusercontent.com/49165468/96905369-59c16b80-1466-11eb-9f39-70e4bbe1ab63.png">

**Desktop (please complete the following information):**
 - OS: [iOS]

**Comment by kyranjamie** [comment]
On it. There's a stacking cycle progress box coming here soon 👍

**Comment by timstackblock** [comment]
I guess the second question is if I send in another 83,000,000 STX should I be able to stack again. I was expecting the user would be able to stack again but this is currently not possible. In the screen shot below you see my available balance should allow me to stack again.

<img width="1013" alt="Screen Shot 2020-10-22 at 1 56 14 PM" src="https://user-images.githubusercontent.com/49165468/96911287-aad55d80-146e-11eb-917f-c86ffe185c5b.png">

**Comment by kyranjamie** [comment]
I understand you can only stack once.

**Comment by markmhx** [comment]
That's correct. The user can stack only once at a time. 

We may want to provide this as a disclaimer on the Stacking get started screen or something. @jasperjansz thoughts?

**Comment by markmhx** [comment]
Since we're exploring partial Stacking capabilities in https://github.com/blockstack/stacks-wallet/issues/295, I believe we can close this particular issue out.
