### ISSUE TITLE
User must stack all STX in wallet when stacking and is NOT given the chance to stack the minimum amount 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#290]
**Describe the bug**
User must stack all STX in wallet even if they only want to stack the minimum amount the Stacking page takes the total STX available in the wallet and does not give the user the ability to choose the amount that should be stacked. 

**To Reproduce**
1. Send more than the minimum amount of STX required to stack into the wallet
2. Click on the GET STARTED button for STX
3. Go into the wallet and you will see the total amount auto-populated in the right side of the stacking page 

**Expected behavior**
Example I need 83333658 to LOCK as the minimum for stacking but I have 88333658  in my wallet. The entire 88333658 is currently being stacked and the user isnt allow to stack the minimum amount of 83333658 or any amount under 88333658 and larger than the minimum.

**Screenshots**
<img width="1012" alt="Screen Shot 2020-10-22 at 1 29 59 PM" src="https://user-images.githubusercontent.com/49165468/96911500-ea9c4500-146e-11eb-8d2c-8c7095d9951e.png">

**Desktop (please complete the following information):**

**Comment by markmhx** [comment]
This is expected behavior. @jasperjansz do you think we should clarify this somewhere on the above screen?

**Comment by psq** [comment]
> This is expected behavior

@markmhx this seems very limiting, and would force people to create multiple addresses if they want to stack only a portion of their STX, otherwise that address becomes unusable till the STX unlock.
And currently, switching addresses requires re-entering an other seed phrase, which is also limiting.

**Comment by aulneau** [comment]
I would agree with @psq

**Comment by markmhx** [comment]
I agree this is limiting and imagine we'll want to add support for Stacking just partial STX holdings some time in the (near) future.

We decided to support just full holdings out of the gate to simplify our design and development against a rather tight deadline (mainnet release), with the suspicion that partial Stacking could surface complicated edge cases.

That said, I'm open to hearing arguments that we do indeed need this immediately upon mainnet (or that the edge cases are manageable).

**Comment by aulneau** [comment]
I would pretty strongly advocate for making the amount to stack something the user can control. I personally would hate to have to go round about to transfer certain amounts of STX between address (which the wallet does not make easy) to have certain addresses for stacking and others for general purpose. To me I can't really see the edge cases that would exist such that we could not account for? An alternative is to allow our wallet to derive more than one address without having to generate private keys, which many other wallets tend to allow, too.

**Comment by kyranjamie** [comment]
I am inclined to agree. Defaulting to stacking your entire wallet balance would be frustrating, especially for people interested in just trying it out.

I don't think it would add a lot of complexity.

**Comment by markmhx** [comment]
I've spun up https://github.com/blockstack/stacks-wallet/issues/295 for @jasperjansz to design so we can all consider the factors involved more clearly before diving into development.
