### ISSUE TITLE
When stacking with my ledger the fee amount appeared as .002 on my ledger but showed up as .00026 in the explorer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#291]
**Describe the bug**
When stacking with my ledger the fee amount appeared as .002 on my ledger but showed up as .00026 in the explorer

**To Reproduce**
1. Go to stacking page and stack with your ledger
2. Verify the amount shown on the ledger
3. Look for the successful transaction in the explorer
4. You will see a different fee amount

**Expected behavior**
I would expect the fee amounts that appear on the ledger to equal the fee in explorer

**Screenshots**
https://testnet-explorer.blockstack.org/txid/0x5b56644cdc8f92fb2766bdbadf27f72cac7d89453b66e53f4e862e81e6af350a?w

<img width="1403" alt="Screen Shot 2020-10-22 at 2 10 59 PM" src="https://user-images.githubusercontent.com/49165468/96912532-82e6f980-1470-11eb-8562-353e2b1e0111.png">

**Desktop (please complete the following information):**
 - OS: [iOS]

**Comment by kyranjamie** [comment]
Can you verify it says `.002` on your ledger? Mines says `260` referring to uSTX. Which is the same as `0.00026 STX`

@markmhx noting here the lack of a clear currency unit, in case this is something you think is worth address

**Comment by markmhx** [comment]
@kyranjamie are you thinking the Ledger app should show a µSTX suffix (e.g. 260 µSTX) or display in STX (e.g. 0.00026 STX)?

**Comment by kyranjamie** [comment]
Either or. My preference would be `µSTX`.

A Ledger user may, quite rightly, find themselves thinking "wtf, this is gonna cost me 260 STX?".

**Comment by markmhx** [comment]
> My preference would be µSTX.

Works for me. I've created https://github.com/Zondax/ledger-blockstack/issues/36 for this request.

**Comment by timstackblock** [comment]
@kyranjamie yes your right it does say 260
