### ISSUE TITLE
Update wallet with rebrand style guidance

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#292]
We should update the new wallet's styles according to the rebrand (https://www.stx.design/):

- Fonts
- Colors
- Any other small details?

This does _not_ require any general overhaul of the design.

cc @jasperjansz @kyranjamie

**Comment by kyranjamie** [comment]
Ideally, this is a UI library task. Make the changes there once, and they'll propagate throughout our entire suite of software, (right¿?¿?)

**Comment by markmhx** [comment]
¡Indeed!

**Comment by jasperjansz** [comment]
This is already updated in the design: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=220%3A4095

What has changed:
- Title font from Söhne to Open Sauce.
- Blue color from #3700ff to #5546FF

We still use Inter for body text. If I remember correctly the typography and colors have been updated in the design system.
