### ISSUE TITLE
Add ability to initiate Stacking with partial holdings

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#295]
Per the discussion on https://github.com/blockstack/stacks-wallet/issues/290, we may want to add the ability for users to initiate Stacking with partial holdings instead of just total holdings.

This could involve empowering the user to initiate multiple Stacking locks in parallel, with partial holdings that add up to total holdings as a maximum. Or it could involve empowering only one Stacking lock at a time, just with any amount up to the total holdings.

If we decide the former, we should modify the UI to indicate somewhere that only one Stacking lock at a time is possible.

**Comment by psq** [comment]
The `pox` contract only allows one stacking operation per address so the decision is easy on the ui side

**Comment by jasperjansz** [comment]
Updated Stacking flow: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=3477%3A1579
