### ISSUE TITLE
No error message pop up when attempting to stack with the incorrect ledger, transaction fails in wallet/explorer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#296]
**Describe the bug**
No error message pops up when attempting to stack with the incorrect ledger, the page refreshes but we do not see the prompt that tells a user to verify they are using the correct hardware wallet. The message displays when sending STX but not during Stacking

**To Reproduce**
1. Go to the wallet attempt to stack with the wrong hardware wallet
2. Click on confirm and Stack and try to sign the transaction with the wrong ledger
3. The box refreshes but there is no error message

**Expected behavior**
The user should see the same error message that was shown when we attempt to send/sign a transaction with the wrong hard wallet.

**Screenshot**

The transaction shows up as failed in the wallet and on the explorer.

https://testnet-explorer.blockstack.org/txid/0xe5458eb2463748a2e00127eaeddd1b40a4b952d29433b983fe32aedf7a534fc8?w

<img width="1423" alt="Screen Shot 2020-10-26 at 12 16 02 PM" src="https://user-images.githubusercontent.com/49165468/97198314-095b4e00-1785-11eb-8cc5-feff3b492e05.png">

<img width="1025" alt="Screen Shot 2020-10-26 at 12 16 46 PM" src="https://user-images.githubusercontent.com/49165468/97198487-3ad41980-1785-11eb-8d55-3295effa6a2e.png">

**Comment by markmhx** [comment]
@kyranjamie will double check whether this has been fixed

**Comment by markmhx** [comment]
@kyranjamie have you been able to check this?

**Comment by kyranjamie** [comment]
Will address this this sprint

**Comment by kyranjamie** [comment]
For QA with security PR

**Comment by timstackblock** [comment]
This issue has returned in the latest build
