### ISSUE TITLE
Not able to stack on windows

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#297]
**Describe the bug**
Getting connection errors during stacking on windows, this may be due to the reset.
@kyranjamie can you please take a look and confirm if this is a real bug or just a reset issue

**Screenshots**
![image](https://user-images.githubusercontent.com/49165468/97195248-81277980-1781-11eb-8b59-b35c9646b7ae.png)

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by timstackblock** [comment]
![image](https://user-images.githubusercontent.com/49165468/97196666-1c6d1e80-1783-11eb-98e3-5d14f55212a3.png)

**Comment by kyranjamie** [comment]
Hmm, this looks like both some OS level permission error (Did you rename to `.tmp372....`?), and issues connecting to the node which I wonder if was to do with the reset.

To test this I opened up a localtunnel to my Mac running a local node, pointed to it on a Windows machine, and went through the stacking process successfully.

![image](https://user-images.githubusercontent.com/1618764/97277878-539e0700-1839-11eb-9ce5-de33ecaa406b.png)

**Comment by timstackblock** [comment]
Thanks @kyranjamie I got this to work without issue this morning using todays latest build on windows, maybe the restart put the wallet in a bad state. I will close this out.
