### ISSUE TITLE
Stacking how it works page goes to Blockstack.com

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#300]
**Describe the bug**
I think this was added as a place holder and never updated, do we have a webpage to link to

**To Reproduce**
1. Go to stacking page
2. Click on 'HOW IT WORKS
3. We go to blockstack.org

**Expected behavior**
There should be a stacking page at some point for this link

**Comment by markmhx** [comment]
This should go to https://www.blockstack.org/questions/how-does-stacking-work

**Comment by timstackblock** [comment]
Duplicate with #302 302
