### ISSUE TITLE
Blockstack wallet icon does not display in linux as it does in MacOS and Windows

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#301]
**Describe the bug**
Blockstack wallet icon does not display in linux as it does in MacOS and Windows, currently there is just an blank empty space with Stacks wallet beta next to it.

**To Reproduce**
1. Install the wallet on linux it comes in under PROGRAMMING
2. Click on 'Stacks wallet beta and u will notice there is no image
3. When you look at the  app tray at the bottom there is an empty panel with no icon in the tray that is for the stacks wallet
4. See error,  there is no thumbnail image

**Expected behavior**
The icons should display just like Windows and Mac

**Screenshots**
![Screenshot from 2020-10-27 15-41-16](https://user-images.githubusercontent.com/49165468/97326968-6da50d00-186c-11eb-819d-5580d9b10818.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon 20

**Comment by markmhx** [comment]
I believe this is the same as reported with https://github.com/blockstack/stacks-wallet/issues/264
