### ISSUE TITLE
Stacking how it works link goes to Blockstack.org

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#302]
**Describe the bug**
Stacking how it works link goes to Blockstack.org, I think this was added as a place holder is there a stacking page to update the link?

<img width="573" alt="Screen Shot 2020-10-27 at 12 04 13 PM" src="https://user-images.githubusercontent.com/49165468/97328587-8c93a700-184c-11eb-8ea1-503bc886d702.png">

**Comment by markmhx** [comment]
This should go to https://www.blockstack.org/questions/how-does-stacking-work

**Comment by kyranjamie** [comment]
I added this a while ago 🤔 

Here's a code screenshot for fun

![image](https://user-images.githubusercontent.com/1618764/97341356-3ee76080-1885-11eb-980e-8c6b9e80b2d9.png)

@markmhx did you only just pushing the page, maybe it was redirecting prior to that?

**Comment by timstackblock** [comment]
Yes there are 2 issues for the same thing I didnt see it go through so I created it again sorry about that

**Comment by markmhx** [comment]
The page has been live for awhile now I think. @timstackblock mind checking again?

**Comment by timstackblock** [comment]
@markmhx 
Here is a video of if going to Blockstack.org let me see if its updated in todays build 
http://somup.com/cY6uI2IhhC

**Comment by timstackblock** [comment]
@markmhx this is updated and working in the newest build, no code change needed.
