### ISSUE TITLE
Use mainnet by default

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#310]
Currently the new wallet is configured to use testnet by default (with associated banner and faucet option). The default should be updated to mainnet in time for launch, with those features showing only when the user optionally chooses testnet.

**Comment by markmhx** [comment]
@hstove You may have some thoughts here on how to detect and handle differences between network types

**Comment by markmhx** [comment]
We've discussed having two types of builds: for mainnet or testnet.

The mainnet one comes with PBC's mainnet node as default and can add more mainnet-compatible nodes but not testnet ones.

The testnet one comes with PBC's testnet node as default and can add more testnet-compatible nodes but not mainnet ones.

The testnet build will show the "Testnet mode" indicator in the navigation bar and the mainnet one will show no message there.

**Comment by kyranjamie** [comment]
Latest CI changes output both network type builds
