### ISSUE TITLE
Security issue: "contextIsolation" is disabled by default

### ISSUE THREAD

**Issue by Shashank-In** [blockstack/stacks-wallet#324]
**Describe the bug**
This means the Electron APIs and the preload script run in the same context, hence an XSS vulnerability could allow an attacker to re-define app functionality via ​prototype tampering​.

**Steps To Reproduce**
1. Go to https://github.com/blockstack/stacks-wallet/blob/master/app/main.dev.js#L62-L66

```
    webPreferences: {
      // nodeIntegration: nodeIntegration,
      preload: path.join(__dirname, "preload.js")
    }
  });
```

Since `contextIsolation` is not mentioned hence it will be disabled by default.

**Expected behavior**
It should have `contextIsolation: true` 

Ref:
https://www.electronjs.org/docs/tutorial/context-isolation

**Environment (please complete the following information):**
N/A

**Comment by Shashank-In** [comment]
@markmhx @kyranjamie I saw that blockstack reward for security issues. Does this qualify for a bounty?

https://forum.stacks.org/t/stacks-2-0-testnet-bounty-program-find-bugs-build-tools/10888

**Comment by Shashank-In** [comment]
Hi @markmhx @kyranjamie 
Can you please respond?

**Comment by timstackblock** [comment]
Hello @Shashank-In I can look into the bounty for you I will bring this bug up at the bounty meeting and see if it is eligible.

**Comment by Shashank-In** [comment]
Hi @timstackblock 
Thank you for your reply. I noticed that the public bug-bounty run on the HackerOne platform as well. 
https://hackerone.com/blockstack

I have filed this as a report. If this is eligible, you can reward me there. Thank you.

**Comment by timstackblock** [comment]
@Shashank-In whats your handle on discord

**Comment by Shashank-In** [comment]
Hi @timstackblock  it is `cyberboy#8597`

**Comment by Shashank-In** [comment]
Hi @timstackblock, It has been 19 days. Please provide some updates. It seems like no one is active for the team for security-related concerns, which should be the topmost priority for any company.

**Comment by Shashank-In** [comment]
@timstackblock No one reached me out yet on discord. I think I will drop the covo now.

**Comment by markmhx** [comment]
The Blockstack PBC team has been on Thanksgiving break since mid last week. @timstackblock should be able to follow up soon this week now that we're back.

**Comment by Shashank-In** [comment]
@markmhx Ahh sorry I didn't realize that. Thank you

**Comment by timstackblock** [comment]
@Shashank-In  a friend request was sent please add me back. @jdbender66 has already reviewed your bug and is trying to setup payment. Thanks.

![20201201_084931](https://user-images.githubusercontent.com/49165468/100749216-5f3d9a00-33b2-11eb-9daf-329a04f07392.jpg)
