### ISSUE TITLE
Disable enableRemoteModule option

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#327]
Making note here to disable this option which is enabled by default in the current version of Electron.

Right now this breaks some of the libraries that rely on the features this enables.

https://www.electronjs.org/docs/api/remote

**Comment by markmhx** [comment]
Are you actively working on this, and as such, should we move this onto the sprint board?

**Comment by markmhx** [comment]
@kyranjamie this can be closed yea?

**Comment by markmhx** [comment]
Lol there's a meme for everything

**Comment by kyranjamie** [comment]
lol yeah I'm going to make this a thing now

**Comment by markmhx** [comment]
![image](https://user-images.githubusercontent.com/28991/105064435-1da9a100-5a7d-11eb-90c0-b91388d4bd84.png)
