### ISSUE TITLE
Not able to transfer stacks from stacks wallet trezor to exchange

### ISSUE THREAD

**Issue by viv1333** [blockstack/stacks-wallet#330]
When I try to transfer stacks , I get a notification on trezor stating op return and I sign a transaction by paying some gas fees , but nothing happens after that. The stacks and the Btc remains the same in stacks wallet

**Comment by markmhx** [comment]
@ryanarndtcm have you seen this behavior before?

**Comment by ryanarndtcm** [comment]
I havent no. This sounds like a new issue.

**Comment by markmhx** [comment]
@viv1333 Are you using the very latest wallet version available at https://wallet.blockstack.org/? And does this problem happen repeatedly?

**Comment by viv1333** [comment]
> @viv1333 Are you using the very latest wallet version available at https://wallet.blockstack.org/? And does this problem happen repeatedly?

Yes it’s the latest version and it happens repeatedly. But I figured a way out, I downgraded my trezor from 1.9.3 to 1.8.3 and it worked .
