### ISSUE TITLE
Remove electron-store from renderer thread

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#332]
Move all electron-store code over to renderer thread

**Comment by markmhx** [comment]
Are you actively working on this, and as such, should we move this onto the sprint board?

**Comment by markmhx** [comment]
Is this addressed with https://github.com/blockstack/stacks-wallet/pull/331 or somewhere else?

**Comment by kyranjamie** [comment]
Yes.

**Comment by markmhx** [comment]
@kyranjamie this can be closed yea?
