### ISSUE TITLE
Add support for testnet Bitcoin addresses to testnet build

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#337]
This morning I tried both Bitcoin addresses `3NhNnPYzWUxaQRJXoceo76dHbmrbvBbtuM` and `12c2rhmV89FfEmVACjUwm5mvcWfDeDXEkT` for Stacking. The former resulted in [a failed transaction](https://testnet-explorer.blockstack.org/txid/0xa63ba3ea9f684cd7efba5acf3b8695e81bd22a4646486710d0fec5f96b624b23?w) whereas the second one resulted in [a successful transaction](https://testnet-explorer.blockstack.org/txid/0x53d401edf3aec98c0acf0ecb71f5ddad9318f427a7ca5d966e703f9ecb4b6693?w), despite both being accepted by the wallet UI as valid.

On inspection of the network requests, the former ultimately exhibited [an `abort_by_response` status](https://stacks-node-api.krypton.blockstack.org/extended/v1/tx/0x889007828bfabd655743fd4984da9df336f80dcd2a4032a46fb8f40660e74cd8) but its unclear why. Presumably it was due to the format of the address, though perhaps that's a red herring.

**Comment by markmhx** [comment]
@timstackblock for testing alongside https://github.com/blockstack/stacks-wallet/issues/253

**Comment by timstackblock** [comment]
Thanks @markmhx we need a bit more context on this issue, what was the cause of the failure and what was fixed. Is there a certain format of BTC address that we accept like native segwit or segwit. Was that a testnet address that failed, Could we clarify the issue a bit more?

**Comment by markmhx** [comment]
@kyranjamie to provide some more guidance on just what types of addresses to test

**Comment by kyranjamie** [comment]
See Bitcoin's documentation here https://en.bitcoin.it/wiki/Invoice_address

**Comment by markmhx** [comment]
@timstackblock The linked PR here is merged now. I presume that means QA is complete and we can close this issue out?

**Comment by markmhx** [comment]
@kyranjamie do we still need to add support for testnet BTC addresses here, for testnet builds only?

**Comment by kyranjamie** [comment]
@markmhx see PR here https://github.com/blockstack/stacks-wallet/pull/438

**Comment by markmhx** [comment]
@timstackblock this appears ready for testing
