### ISSUE TITLE
Improve Stacking-related copy

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#339]
All copy related to BTC earning should be framed more in terms of potential rather than promise, and Stacking as a term should be used where helpful.

The following should say "Earn Bitcoin rewards with Stacking" and "You can earn Bitcoin upon temporarily by locking N STX or more":

<img width="415" alt="Screen Shot 2020-11-13 at 13 48 10" src="https://user-images.githubusercontent.com/28991/99073915-1666a280-25b7-11eb-863b-647324b14509.png">

We may also want to place a "How Stacking works" link here below the button for those who aren't familiar already, similar to what we have on the Stacking page itself.

The following should say "When you lock your STX, you'll have a chance to earn Bitcoin every week."

<img width="410" alt="Screen Shot 2020-11-13 at 09 05 16" src="https://user-images.githubusercontent.com/28991/99073633-917b8900-25b6-11eb-9961-f038e394a71b.png">
"Lock your STX for chance to earn Bitcoin when the next cycle starts":

<img width="603" alt="Screen Shot 2020-11-13 at 14 00 23" src="https://user-images.githubusercontent.com/28991/99074725-95100f80-25b8-11eb-8a7e-1672bb0b52c9.png">

"you'll have the chance to earn Bitcoin":

<img width="578" alt="Screen Shot 2020-11-13 at 13 56 44" src="https://user-images.githubusercontent.com/28991/99074465-14e9aa00-25b8-11eb-8642-1fb048fbe9d6.png">

"You may receive Bitcoin twice":

<img width="638" alt="Screen Shot 2020-11-13 at 13 57 44" src="https://user-images.githubusercontent.com/28991/99074555-3f3b6780-25b8-11eb-8d81-2ab71c714685.png">

(Although "twice" – is that a constant? why twice?)

**Comment by kyranjamie** [comment]
I believe the twice comes from the implementation. I believe there are two payouts.

**Comment by markmhx** [comment]
I presume then it's twice per cycle and the total comes from multiplying by the variable number of cycles indicated (e.g. 3 cycles x 2 times per cycle = "You may receive Bitcoin six times")?
