### ISSUE TITLE
Stacking looks like sending while processing

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/stacks-wallet#346]
[![Screenshot_2020-11-13_20-53-57.png](https://mrkr.io/s/5faef265aa02fe43f16efba5/2)](https://mrkr.io/s/5faef265aa02fe43f16efba5/0)

The two panic causing elements are the minus sign and the Sending. For the Stacking maybe "Stacking" and no minus. Or a lock instead of minus. 

---

**Reported by:** Bobby (jeff.domke@gmail.com)
**Source URL:** [file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.27.28%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.27.28%20PM.png)
<table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1944 x 1161</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
This change is covered by https://github.com/blockstack/stacks-wallet/issues/335, though I'll add a note there specifically about the minus sign. That's a good additional point.
