### ISSUE TITLE
Funky state

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/stacks-wallet#347]
[![Screenshot_2020-11-13_20-56-41.png](https://mrkr.io/s/5faef3094880254445670d7b/2)](https://mrkr.io/s/5faef3094880254445670d7b/0)

This state is strange. User may just wait. In the previous screens `close` is often used to indicate `cancel` but here it just means close. I suggest removing all together or something like `Back to wallet` and some guidance of how long this may take. 

Or better yet make it a toaster that sits on the main wallet page. 

---

**Reported by:** Bobby (jeff.domke@gmail.com)
**Source URL:** [file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.25.47%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202020-11-13%20at%203.25.47%20PM.png)
<table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1944 x 1161</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
This is addressed by https://github.com/blockstack/stacks-wallet/issues/335
