### ISSUE TITLE
Learn more about Stacking link: More durable URL

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/stacks-wallet#355]
https://www.blockstack.org/questions/how-does-stacking-work

We can always redirect but would prefer a more durable URL.

**Comment by markmhx** [comment]
Do you mean something like `blockstack.org/stacking` since it's simpler and could lead to more than just a Q&A item?

**Comment by jeffdomke** [comment]
Blockstack.org will simply redirect to Stacks.co in a couple months.
