### ISSUE TITLE
Apply Recommendations on Argon2 KDF Parameters

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#363]
As suggested by NCC:

Not fully utilizing the Argon2 configuration parameters would allow for for efficient brute force attacks on the user’s stored mnemonic.

The Argon2 key derivation function is used for deriving a wrapping key from the user supplied password. Argon2 can be used for both password storage and key derivation and is highly configurable, depending on the environment. The Stacks Wallet application uses the argon2 -browser library that appears to be configured for password storage, which is not ideal for use case of non-interactive key derivation. This can result in less than optimal configuration parameters.

Although parameters are not fixed as they depend on the environment, required execution time and target architecture; there are number of common parameter choices. The libs odium documentation,6 can provide a good starting point from which execution times can be derived. The current recommendation is that highly sensitive data and non-interactive operations, key derivation will take about 3.5 seconds on a 2.8 Ghz Core i7 CPU and requires 1024 MiB of dedicated RAM.

**Comment by kyranjamie** [comment]
Closed, approved by NCC follow up audit
