### ISSUE TITLE
[4.0.0-beta.7] Issue: Strong enough password

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#365]
Issue found testing Stacks Wallet build , 4.0.0-beta.7.

When creating a new software wallet, I am asked to enter a password. (I guess for local encryption). After entering a password, I am told that it is not strong enough. I tried several times without luck. What are the requirements?

I am stuck on that page because the back button is disabled.

Furthermore, there is not support for password managers.

**Comment by markmhx** [comment]
I agree that guidance here could be helpful, though I'm not sure what's available given the library that @kyranjamie has implemented.

Password manager support sounds good too, though I'm unclear on how Electron apps hook up to them.

**Comment by kyranjamie** [comment]
The requirements are 12 chars and a zxcvbn score 4. Ken also made an issue to improve guidance.

Other than explaining what zxcvbn is, though, there aren't exact requirements. It's either strong enough, or it isn't. The library outputs some advice which should be displayed. Not sure what else to do.

Maybe your passwords just aren't that strong friedger 😅

Regarding pw manager, I'm also not sure if electron apps can integrate the same as in browser. Do you know of any examples?

**Comment by markmhx** [comment]
Linking the issue from @yknl: https://github.com/blockstack/stacks-wallet/issues/260

**Comment by markmhx** [comment]
This appears addressed by https://github.com/blockstack/stacks-wallet/pull/371
