### ISSUE TITLE
[4.0.0-beta.7] Bug: Wrong estimated lock time in confirm message

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#366]
Bug found testing Stacks Wallet build , 4.0.0-beta.7.

The confirm message says ~2 weeks, while the widget on the right says ~24 hours.

![Screenshot from 2020-11-19 11-37-20](https://user-images.githubusercontent.com/1449049/99655219-b90d9e00-2a5b-11eb-8d47-1736b40caf54.png)

**Comment by markmhx** [comment]
I'm closing this out since it's a dupe with https://github.com/blockstack/stacks-wallet/issues/340.
