### ISSUE TITLE
[4.0.0-beta.7] Issue: link to explorer

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#367]
Issue found testing Stacks Wallet build , 4.0.0-beta.7.

As a power user I would like to be able to close the modal dialog and watch the transaction in the explorer.

![Screenshot from 2020-11-19 11-39-35](https://user-images.githubusercontent.com/1449049/99655500-1bff3500-2a5c-11eb-9fe1-737887965f22.png)

**Comment by markmhx** [comment]
This modal is getting removed entirely in favor of sending the user back to the home activity view with related information along the lines of what you suggest: https://github.com/blockstack/stacks-wallet/issues/335
