### ISSUE TITLE
[4.0.0-beta.7] Bug: Stacking failed with error 13

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#368]
Bug found testing Stacks Wallet build , 4.0.0-beta.7.

The stacking transaction issued from the wallet failed with error 13 invalid pox address

https://stacks-node-api.blockstack.org/extended/v1/tx/0xe3c7d1caae0d4f3967c6e6f6c4777e97ed7d97d1caad5df0628e369669d64e49

There should be a check before sending the tx off.

**Comment by kyranjamie** [comment]
Thanks @friedger — this was a testnet address?

![image](https://user-images.githubusercontent.com/1618764/99678347-02b9b100-2a7b-11eb-9ca8-78ad5de279ca.png)

Added a check for this in `7b47825`

**Comment by kyranjamie** [comment]
@timstackblock this is testable in the latest release of the PR I've assigned you

**Comment by markmhx** [comment]
@timstackblock have you been able to QA this bug?

**Comment by kyranjamie** [comment]
To be QA'd with https://github.com/blockstack/stacks-wallet/pull/375

**Comment by timstackblock** [comment]
<img width="1009" alt="Screen Shot 2020-12-02 at 10 03 20 AM" src="https://user-images.githubusercontent.com/49165468/100889887-a779bc80-3485-11eb-8e46-62b5ad40d8e4.png">
