### ISSUE TITLE
[Legacy] Code signing doesn't seem to work

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#370]
Looking for guidance on how to implement https://github.com/blockstack/stacks-wallet/issues/171 I ran into the following error trying to run `3.1.1` edit: downloaded from here https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.1

![image](https://user-images.githubusercontent.com/1618764/100742990-f23efa00-33db-11eb-9c6d-22b031bbdbc8.png)

**Comment by markmhx** [comment]
@yknl thoughts here?

**Comment by yknl** [comment]
Are you getting this error from the .dmg downloaded from wallet.blockstack.org?

**Comment by kyranjamie** [comment]
No, I downloaded from github releases: https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.1

**Comment by yknl** [comment]
You are on macOS Catalina correct?
Going forward we'll need to notarize the app with Apple:
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by markmhx** [comment]
I'm closing this out since I don't expect it'll be priority for the v3.x wallet now that v4.x is released.
