### ISSUE TITLE
[Security]Disable auxclick to limit navigation flows to untrusted origins

### ISSUE THREAD

**Issue by Shashank-In** [blockstack/stacks-wallet#372]
**Describe the bug**
The creation of a new browser window or the navigation to untrusted origins may lead to severe vulnerabilities. Additionally, middle-click causes Electron to open a link within a new window. Under certain circumstances, this can be leveraged to execute arbitrary JavaScript in the context of a new window.

Navigation to untrusted origins can facilitate attacks, thus it is recommend to limit the ability of a BrowserWindow and webview guest page to initiate new navigation flows. Middle-click events can be leverage to subvert the flow of the application.

**To Reproduce**
1. Go to https://github.com/blockstack/stacks-wallet/blob/master/app/main.dev.js#L57
We will notice Auxclick is not disabled

**Expected behavior**
Auxclick should be disabled

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS

**Suggested Fix**
`libchromiumcontent` will trigger middle-click events as auxclick instead of click. The application has to explicitly disable this insecure behaviour using 

```
"webPreferences": {
        "disableBlinkFeatures ": "Auxclick"
    }
```

** Reference **
- https://github.com/electron/electron/issues/10315

**Comment by kyranjamie** [comment]
Please see https://github.com/blockstack/stacks-wallet/pull/331 this is addressed in this PR

**Comment by timstackblock** [comment]
Thank you for the submission but this is code for the old V1 wallet. 

We are only submitting bug bounty for the new wallet and code that will be used on our current testnet please only review the V2 wallet that @kyranjamie has built for bug bounty submissions.
