### ISSUE TITLE
[Security] Weak CSP policy 

### ISSUE THREAD

**Issue by Shashank-In** [blockstack/stacks-wallet#374]
**Describe the bug**
CSP is really good to restrict and control the resources Electron can load for that given web page. Since any execution of script is harmful for the app the cap policy should be very strict. 
I noticed an important attributes missing. 

If we go to https://github.com/blockstack/stacks-wallet/blob/master/app/app.html#L5

We will notice CSP is missing `object-src`
Missing object-src allows the injection of plugins which can execute JavaScript. This can be set to `none`

**To Reproduce**
1. Go to https://github.com/blockstack/stacks-wallet/blob/master/app/app.html#L5

**Reference**
- https://csp-evaluator.withgoogle.com

**Comment by kyranjamie** [comment]
Hi @Shashank-In, thanks for the issue.

We have a WIP security PR with the [following CSP](https://github.com/blockstack/stacks-wallet/pull/299/files#diff-66e2a509e5a3f1709bd0509bf031ce33bd4070b1639a4680c9815bb01a062ca5R8)
 
```
default-src 'none'; font-src 'self'; img-src data:; style-src 'unsafe-inline'; script-src 'self' 'nonce-6ca3c3e1fcd34bbc8cfaeceaa8106e36'; connect-src *;
```

With this CSP, `object-src` defaults to `none` as a `default-src` directive is set.

**Comment by Shashank-In** [comment]
The fix looks great also the uses of the nonce is much better @kyranjamie 
However, I am confused if this qualifies for a security bounty. 
Can you confirm the same?

**Comment by kyranjamie** [comment]
Adding a stricter CSP has been addressed prior to your report, so in this instance it doesn't qualify for a bounty.

But we appreciate you reporting it. Let us know if you find any other issues, though I'd encourage you to first check issues and active PRs to see if they've already been addressed.

**Comment by Shashank-In** [comment]
Thank you @kyranjamie

**Comment by timstackblock** [comment]
@Shashank-In this is not a testnet but as @kyranjamie found this issue and is already fixed it
