### ISSUE TITLE
Transaction from Binance to Stacks Wallet "Invalid" after 8 days.

### ISSUE THREAD

**Issue by mattholemew** [blockstack/stacks-wallet#384]
Hello,

I am having an issue receiving STX into my stacks wallet.  I have the latest version of the wallet as of today (3.1.1) on Windows.  I have tried restarting the wallet, resetting the wallet, and waiting (as others have suggested in other issues).  I'm using it with a Ledger device.

Here's the details of the transaction:
Sender: SP3WV3VC6GM1WF215SDHP0MESQ3BNXHB1N6TPB70S
Wallet Addr: SP7YXQM4VBM6GN9KXSX5MJBC12KDYT7SRPTZ4WV0
TXID: 5f078dbfb5f0af808ae9e597f56f96b047574b0f97b79014e19eacacf53f6776

The BTC transaction DID take several hours to confirm (unfortunately sent during a busy network time period)

Is there any way to retrieve my funds which show up in my wallet but are still showing as "Invalid" and unspendable?

![image](https://user-images.githubusercontent.com/6975658/101503740-0af96380-3938-11eb-8895-594962bcf1d9.png)

Thanks.

**Comment by markmhx** [comment]
Can you confirm your wallet's address? I'm unable to pull up any activity for the one you've listed:

https://explorer.blockstack.org/address/stacks/SP7YXQM4VBM6GN9KXSX5MJBC12KDYT7SRPTZ4WV0

I see the transaction you've here for a week ago, however without any indicated STX transfer:

https://explorer.blockstack.org/tx/5f078dbfb5f0af808ae9e597f56f96b047574b0f97b79014e19eacacf53f6776

**Comment by mattholemew** [comment]
Yes, that's correct... That's another issue... the wallet address transactions cannot be found on the block explorer either and that's what's puzzling me.  I'm using the latest stacks wallet with Ledger Nano S:
![image](https://user-images.githubusercontent.com/6975658/101659745-02725d00-3a0c-11eb-872b-d1be8c0545d4.png)
![image](https://user-images.githubusercontent.com/6975658/101659795-0e5e1f00-3a0c-11eb-91b0-8ee0fef8b802.png)

**Comment by mattholemew** [comment]
Showing zero stacks balance, though even though the transaction is showing on the wallet
![image](https://user-images.githubusercontent.com/6975658/101659892-2897fd00-3a0c-11eb-9922-76058d4affe4.png)

**Comment by yknl** [comment]
The transaction was invalid, and the explorer did not pick it up. The wallet will show you invalid transactions. Best to follow up with Binance to resend the transaction.

**Comment by mattholemew** [comment]
I will attempt to follow up with Binance to see if they can resend the transaction.  We shall see.  Thank you!

**Comment by mattholemew** [comment]
Okay, .... After waiting in queue for Binance Chat Support for about 6 hours, I finally was able to speak with a very cordial and helpful person.  They were NOT, however, able to resolve my issue.  They were saying that because the transaction looked okay from their end (and because the BTC transaction did confirm as I saw), they would not be able to help resend the transaction, and they would not be able to return my funds.

They're blaming some sort of bug in either the blockchain or the wallet.

I fear that the funds that I sent to the wallet are now lost, and I wish (in retrospect) that I had sent a smaller amount to the wallet to test it first before sending a larger amount.

Since this transaction is on the BTC blockchain but is not showing on the STX address... it seems to be lost???  Not sure where the funds went, but maybe into the great void.  As BTC blockchain gets busier and busier in the next year or so I fear that this may be a more common occurrence

Thanks again!

**Comment by castadream2** [comment]
@mattholemew I have same issue. Have you tried looking at the transaction id in explorer.blockstack.org from your Wallet? May have to refresh, but I bet you do see this in Explorer like I do mine. First I show an unparsed address to, then the following which appears BTC sent back to sender (in this case Binance).
<img width="1013" alt="Screen Shot 2020-12-27 at 7 27 14 PM" src="https://user-images.githubusercontent.com/36422910/103182473-88e6c580-4879-11eb-8ef5-10fd95629181.png">

**Comment by mattholemew** [comment]
Hi @castadream2 !  I do see the BTC transaction in the blockstacks explorer, however, I do not see any transactions to my address in the explorer.  In my case, however, the BTC was never sent back to Binance.  It looks like it's still sitting in my Stacks wallet right now.  So looks like I've received the BTC part of the transaction, but not the STX.

Thanks again,
- Matt

**Comment by markmhx** [comment]
Please see https://github.com/blockstack/stacks-wallet/issues/430#issuecomment-751840049 for related information.

**Comment by markmhx** [comment]
Please try again with the new Stacks Wallet if needed now that the network has upgraded to Stacks 2.0: https://www.hiro.so/wallet/install-web

**Comment by ecshanewiley** [comment]
Hi. @markmhx . I'm having the same problem. Thanks BTW for your help on this thread. The invalid stacks transaction via Binance, thus zero available balance in my wallet, but my wallet does show 2912.075 STX in the transaction.  The wallet version is 3.1.1. I used my Trezor to login and make transactions in the past. Now I'm unable to access with my Trezor wallet or get private keys. I do not recall getting a private key since I was using my Trezor. Currently I have a ticket in with Binance to see if they can fix this issue. 

**Any other ideas on how I can get access to these STX coins?** 

Wallet address: SP3XD9MVR6GPPWKZB586G0XKJ5J6A9RP84TWJQVSG
BTC Transaction: 9978256dfc9f64bb583e9ef7bfcaae34ccb7310a9378a7d4d2e3701aa4173ba0

<img width="618" alt="Screen Shot 2022-05-15 at 5 52 28 PM" src="https://user-images.githubusercontent.com/85648385/168502734-d37dce2a-0475-4e10-9520-3b22fff37bc3.png">

<img width="942" alt="Screen Shot 2022-05-15 at 5 52 17 PM" src="https://user-images.githubusercontent.com/85648385/168502718-daf04e9e-ed10-4d60-863c-eec30687b20f.png">

**Comment by markmhx** [comment]
@ecshanewiley you'll need to upgrade your wallet since the one shown in your screenshots is very old and no longer works with the network: https://www.hiro.so/wallet

Then see: https://www.hiro.so/wallet-faq/how-can-i-use-my-trezor-device-with-the-stacks-wallet
