### ISSUE TITLE
Infinite spinner when creating a new software wallet[4.0.0-beta.8]

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#391]
Infinite spinner when creating a new software wallet

Users are blocked from entering the wallet

Video of issue http://somup.com/cYl62L2uDr

<img width="1011" alt="Screen Shot 2020-12-10 at 9 54 18 AM" src="https://user-images.githubusercontent.com/49165468/101788083-c0115480-3acd-11eb-9851-c4174f8d5299.png">

**Comment by timstackblock** [comment]
https://github.com/blockstack/stacks-wallet/issues/312

**Comment by kyranjamie** [comment]
Errors because of 

```
renderer.prod.js:84803 Uncaught (in promise) Error: Uncaught Error: Error invoking remote method 'derive-key': ReferenceError: atob is not defined
```

**Comment by kyranjamie** [comment]
Fixed.
