### ISSUE TITLE
stacks wallet opening up to all white screen

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#392]
stacks wallet opening up to all white screen

Video of issue http://somup.com/cYl6bg2ugd

<img width="1081" alt="Screen Shot 2020-12-10 at 12 40 05 PM" src="https://user-images.githubusercontent.com/49165468/101808941-f5756c80-3ae4-11eb-9d5a-cca2c5916c9e.png">

**Comment by kyranjamie** [comment]
Sorry you keep encounting blocking issues @timstackblock

As discussed on Discord, I've been having issues replicating a truly production-like build locally. Both issues are to do with the packaging set up re argon2, which—and I've tested on all possible environments—is now fixed.

You can download latest build from https://github.com/blockstack/stacks-wallet/pull/331. The jobs are failing, but the assets are still created. I've added a debug build back again as well, so you can capture issues with devtools.

**Comment by timstackblock** [comment]
@kyranjamie any update on this issue is the white screen fixed?

**Comment by kyranjamie** [comment]
Yes, it is.

**Comment by timstackblock** [comment]
Ok thanks I will take a look
