### ISSUE TITLE
[4.0.0-beta.3] Bug: 24-word verification not working?

### ISSUE THREAD

**Issue by chrismtx** [blockstack/stacks-wallet#393]
Bug found testing Stacks Wallet build 3e97a15, Thu Sep 24 16:43:41 UTC 2020.

**Comment by chrismtx** [comment]
enter 24 secret words don't match.....    it is matched but it keeps on saying it doesn't match...

**Comment by kyranjamie** [comment]
Thanks for reporting the issue @chrismtx 

Can you provide some more details? You've entered the 24-word Secret Key, and it doesn't let you proceed when enter it to verify?
