### ISSUE TITLE
Fix builds for Windows 10

### ISSUE THREAD

**Issue by joshmatix** [blockstack/stacks-wallet#408]
Yarn build complained about cross-env not installed, even though it is in package.json.
Deleted from package.json and then 
yarn add cross-env
after which yarn build worked.

**yarn dev**
yarn run v1.22.5
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
The DLL files are missing. Sit back while we build them for you with "yarn build-dll"
Starting Main Process...

> stacks-wallet@4.0.0-beta.8 start-main-dev S:\dev\stacks-wallet
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

Error: Invalid header: Does not start with Cr24
    at crxToZip (S:\dev\stacks-wallet\node_modules\unzip-crx\dist\index.js:32:15)
    at S:\dev\stacks-wallet\node_modules\unzip-crx\dist\index.js:57:32
    at callHanler (S:\dev\stacks-wallet\node_modules\yaku\lib\yaku.js:719:16)
    at tryCatcher (S:\dev\stacks-wallet\node_modules\yaku\lib\yaku.js:436:32)
    at S:\dev\stacks-wallet\node_modules\yaku\lib\yaku.js:575:38
    at flush (S:\dev\stacks-wallet\node_modules\yaku\lib\yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
23:53:01.141 > Skip checkForUpdatesAndNotify because application is not packed
(node:9176) Electron: Loading non-context-aware native module in renderer: '\\?\S:\dev\stacks-wallet\app\node_modules\usb\build\Release\usb_bindings.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[6496:1211/235307.174:ERROR:CONSOLE(7)] "Uncaught TypeError: Cannot read property 'panels' of undefined", source: chrome-extension://devtron/static/devtron.html (7)

the gui that came up
renderer.dev.js:183631 Invalid Host/Origin header
error @ renderer.dev.js:183631
renderer.dev.js:183819 Invalid Host/Origin header
error @ renderer.dev.js:183819
renderer.dev.js:183634 [WDS] Disconnected!
close @ renderer.dev.js:183634
renderer.dev.js:183822 [WDS] Disconnected!
close @ renderer.dev.js:183822

Subsequent runs of yarn dev did not have gui errors

**Comment by markmhx** [comment]
@kyranjamie got this running on Windows and just needs to add some instructions to the README about how he did it.

**Comment by markmhx** [comment]
@joshmatix It's unclear whether you were able to unblock yourself and run `yarn dev` here successfully in the end?
