### ISSUE TITLE
stacks wallet v4.0 won't send stx testnet tokens. the send button keeps on spinning

### ISSUE THREAD

**Issue by chrismtx** [blockstack/stacks-wallet#409]
stacks wallet v4.0 won't send stx testnet tokens. the send button keeps on spinning

**Comment by kyranjamie** [comment]
What version @chrismtx, screenshot, any extra info?

**Comment by chrismtx** [comment]
Build date: Thu Sep 24 16:43:41 UTC 2020

v4.0.

**Comment by kyranjamie** [comment]
We've made some changes that should've fixed this, see the build in this PR https://github.com/blockstack/stacks-wallet/pull/331
