### ISSUE TITLE
ERROR: Unable to verify transaction Failed to call stacking contract

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#412]
Previously I was running into a password issue, then we had a random white screen now I am seeing this error.

This is the first time I have seen this error

After the user enter the correct password this error message displays

<img width="1009" alt="Screen Shot 2020-12-14 at 1 25 36 PM" src="https://user-images.githubusercontent.com/49165468/102119949-e148ac80-3e0f-11eb-9cd0-b444a5535ca5.png">

**Comment by timstackblock** [comment]
<img width="827" alt="Screen Shot 2020-12-15 at 9 12 05 AM" src="https://user-images.githubusercontent.com/49165468/102226739-bebd9e80-3eb6-11eb-8352-d5c4b23440b7.png">
<img width="625" alt="Screen Shot 2020-12-15 at 9 11 03 AM" src="https://user-images.githubusercontent.com/49165468/102226742-bebd9e80-3eb6-11eb-9499-59395b78fc09.png">
<img width="1309" alt="Screen Shot 2020-12-15 at 9 08 11 AM" src="https://user-images.githubusercontent.com/49165468/102226758-c715d980-3eb6-11eb-96e4-88608f66f623.png">

**Comment by markmhx** [comment]
@timstackblock The linked PR here is merged now. I presume that means QA is complete and we can close this issue out?
