### ISSUE TITLE
problems withdrawing

### ISSUE THREAD

**Issue by reyalto** [blockstack/stacks-wallet#415]
I'm new to posting to github but its the best I could find for help on the stacks wallet. I have enough btc to transfer to my kucoin account..but still shows pending for the last few hours. not sure what to do...

**Comment by fluidvoice** [comment]
> I'm new to posting to github but its the best I could find for help on the stacks wallet. I have enough btc to transfer to my kucoin account..but still shows pending for the last few hours. not sure what to do...

post in the Telegram channel. This is not the place to report your problem.
