### ISSUE TITLE
Stacks V2 wallet has correct balance but does not have any of the transactions that show in the V1 explorer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#420]
Stacks V2 wallet has correct balance but does not have any of the transactions that show in the V1 explorer, is this expected?

I can login to the wallet with my V1 seed phrase so this is great and I see the balance, but should I see an accurate transaction history?

https://explorer.blockstack.org/address/stacks/SP2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK7880556R3
Adress: SP2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK7880556R3 
Balance 0.098903 STX

<img width="1266" alt="Screen Shot 2020-12-21 at 9 35 46 AM" src="https://user-images.githubusercontent.com/49165468/102789492-3afe2900-4372-11eb-98b6-608a0cfc52fc.png">
<img width="1041" alt="Screen Shot 2020-12-21 at 9 35 39 AM" src="https://user-images.githubusercontent.com/49165468/102789496-3cc7ec80-4372-11eb-99b4-fc615f018e3d.png">

**Comment by diwakergupta** [comment]
> Stacks V2 wallet has correct balance but does not have any of the transactions that show in the V1 explorer, is this expected?
> 
> I can login to the wallet with my V1 seed phrase so this is great and I see the balance, but should I see an accurate transaction history?

Yes, this is expected. We're importing over accounts balances etc, but not the entire transaction history of Stacks 1.0.
