### ISSUE TITLE
[4.0.0-beta.1] Bug: beta 1 release says 24 word seed phrase and not 12 or 24

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#427]
beta 1 release says 24 word seed phrase and not 12 or 24

<img width="806" alt="Screen Shot 2020-12-23 at 9 37 00 AM" src="https://user-images.githubusercontent.com/49165468/103008018-6c0d6380-4502-11eb-9dea-cefd3e5c9c2f.png">

**Comment by kyranjamie** [comment]
I'll remove the number of words altogether
