### ISSUE TITLE
NSIS error when trying to install

### ISSUE THREAD

**Issue by JohnAlf** [blockstack/stacks-wallet#429]
I got this error on the first attempt to install Blockstack wallet. I then turned my anti virus off and still get the same error. It says:
"Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy." More information at: http://nsis.sf.net/NSIS_Error

The download is 96,153KB

**Comment by markmhx** [comment]
Just to confirm, did you install the wallet from here?  And if so, which operating system build exactly? https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.1

**Comment by JohnAlf** [comment]
Yes, from GitHub. I am using Win 10.HOME ver 20H2 64bit

Sent with Protonmail.com encrypted/secure email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by timstackblock** [comment]
Let me try installing this now

**Comment by timstackblock** [comment]
This worked for me, there must have been an issue downloading the exe file please delete your current download and try again

**Comment by JohnAlf** [comment]
please send me a link to the exact file you downloaded so I know I am on track.
Thanks ;)

Sent with Protonmail.com encrypted/secure email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by timstackblock** [comment]
https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.1

**Comment by JohnAlf** [comment]
thank you very much. I am now installed. ;)

Sent with Protonmail.com encrypted/secure email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by markmhx** [comment]
Glad to hear it!
