### ISSUE TITLE
Ensure new Stacks Wallet can be installed in parallel to v3.x

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#436]
Opening here rather than fixing right away owing to issue with electron-builder where it uses "productName" field for MacOS installation, rather than appId or another key, for the install location.

Problematic if we have the same name "Stacks Wallet"

**Comment by kyranjamie** [comment]
Installing to `StacksWallet` and `StacksWalletTestnet` respectively, circumventig this issue.

**Comment by markmhx** [comment]
No spaces huh? Kinda weird. Is there not a better way like "Stacks Wallet (New)" for now or something?

**Comment by kyranjamie** [comment]
*For the install location `~/Library/Application Support/StacksWallet`. The actual app remains Stacks Wallet.

**Comment by markmhx** [comment]
Oooh fantastic 👍
