### ISSUE TITLE
Content overlapping with footer items

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#439]
I noticed that the ToS overlaps with labels on the bottom:

<img width="934" alt="Screen Shot 2020-12-30 at 9 21 54 AM" src="https://user-images.githubusercontent.com/1671228/103370097-c8cbc980-4a80-11eb-9ada-db3fcafb25fa.png">

**Comment by kyranjamie** [comment]
Would love some ideas as how we can

1) Always show some kind of build information in the frame (as it's incredibly helpful for feedback)
2) Avoid content overlap that looks like like this

Really small font and tighter in the bottom right?

**Comment by aulneau** [comment]
You could make it look like a toast, wrap it in a padded div with a border radius, box-shadow and border?
