### ISSUE TITLE
Lag when initiating stacking

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#442]
Once "initiated" is clicked on, there's a waiting period for some seconds (assuming due to the tx broadcasting timing). During the time, the state seems to change a few times, until the popup is disabled. It felt like things are not going right. Might make sense to review the state changes

**Comment by kyranjamie** [comment]
This isn't so much the tx broadcast network delay as it is the key derivation.

I've fixed this issue, by adding a fixed-time delay for the animations to begin properly, before the cpu-intense argon2 fn is called—during which the software is basically unresponsive for a number of seconds relative to the cpu power of your computer.

Some wallets add a "Program may seem unresponsive, please wait" message. We might need something similar.
