### ISSUE TITLE
Opening new transactions URLs with `?w` param

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#443]
When I click on one of the transactions in the list, it opens the Explorer but the URL ends with `?w`. Is there a reason for that?

**Comment by kyranjamie** [comment]
This was to give us some insight into usage. Should we remove?

**Comment by agraebe** [comment]
Ah, I didn't know we're using it for that. I like that, actually. Something like '?source=wallet' might be more clarifying but I don't have strong opinions here

**Comment by markmhx** [comment]
We may do best to use a standard `utm_source=stacks-wallet-[OPERATING SYSTEM]` format (e.g. `stacks-wallet-mac`, `stacks-wallet-windows` and `stacks-wallet-linux`, or simply `stacks-wallet-desktop`) here for easier recognition, greater specificity, and readier compatibility with analytics tools.

**Comment by kyranjamie** [comment]
using utms
