### ISSUE TITLE
Stacking view showing all steps at once

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#446]
I felt like the stacking configuration screen intentionally uses a "step-wise flow". However, seeing all options available at once, was confusing. It was not clear if there's a sequence that should be followed and if all options should be set.

**Comment by markmhx** [comment]
I believe this UX will get ironed out by https://github.com/blockstack/stacks-wallet/issues/343

**Comment by agraebe** [comment]
got it, will close this
