### ISSUE TITLE
Improve Stacking card while waiting for next reward cycle

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#447]
I'm seeing "68 blocks to go" once the stacking was confirmed. The card is very empty/underwhelming considering I went through all these steps. I also don't know (as an end-user) is 68 blocks means to wait for weeks/days/hours/minutes.

**Comment by markmhx** [comment]
This has been resolved now that the status indicator has been updated generally:

<img width="397" alt="Screen Shot 2021-01-20 at 13 30 36" src="https://user-images.githubusercontent.com/28991/105175039-b4c93400-5b23-11eb-8a64-9e648be5848c.png">
