### ISSUE TITLE
Restoring a keychain asking to set a password 

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#449]
When I restore a keychain (after I entered the secret key), I'm being asked to "set a password". The UI also shows a password strength indicator, making it look like I'm setting a new password. Enter my actual password works, so this seems just a UI issue (likely due to a re-used view?)

**Comment by markmhx** [comment]
I think you are indeed being asked to set a new password, but if you used your old / actual, then that works too (as your new password 🙃 )

**Comment by agraebe** [comment]
Oh wow, so if I don't remember my password before confirming q transaction, I could just reset and restore the account and set a new password? Is that the right practice, from a security standpoint?

**Comment by kyranjamie** [comment]
> Oh wow, so if I don't remember my password before confirming q transaction, I could just reset and restore the account and set a new password?

Of course... Similarly to how, if you lost your computer, you could also restore it from your seed phrase.

Setting a password encrypts the seed phrase locally, so you don't have to keep entering it. Repeatedly accessing/entering your seed phrase isn't a secure practice. But your password is in no way tied to the phrase. If you enter your seed on a new computer, we have no way of persisting your old password, and even if we did, there wouldn't any value in doing so.

**Comment by agraebe** [comment]
I see. I guess my assumption was the password is somehow tied to the account due to the flow. I wouldn't be surprised if users would have a similar takeaway and support tickets could come up

**Comment by markmhx** [comment]
I sense this may get resolved with https://github.com/blockstack/stacks-wallet/issues/240

**Comment by agraebe** [comment]
True, closing in favor of that
