### ISSUE TITLE
Build-time one version behind semantic release

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#461]
There's an issue with the updater where the latest version shows the "Update available" message.

This is because we're using `package.json` version _at build-time_. Semantic release increments the version _after_ build. So release version `v4.0.0-beta.6` thinks it is still `v4.0.0-beta.5`.

@CharlieC3 any ideas how we can fix this? Is there any harm in running the `release` job before `build`, so the next version can be passed to build as an environment var? 🤔 

Edit: Of course... it can't be ran before as the assets are needed for release. This is the exact same issue we ran into before with trying to find out, ahead of time, what the version will be. In this instance we really need to know, so we can tell the software at build time what version it is. This seems like such a trivial requirement yet it's near impossible with semantic-release.

Maybe we can refactor the jobs so that:
- Semantic release runs as it is, but doesn't create the github release
  - Adds to change log, creates the version increment commit, pushes tag
- Separate job builds watches for tag push with the create versions
- A build is created with now accurate version
- A separate github action used to `create-release`

**Comment by CharlieC3** [comment]
@kyranjamie The idea you laid out is roughly what I would do as well. The only changes I would make is to have it all run in the same workflow. Having too many workflows (which there already is plenty of) is confusing. Plus you probably won't want the `create-release` job to run separately if someone had to push up a tag from their local for whatever reason. Not to mention semantic-release will push up both a commit and a tag together. So if you have a separate workflow which needs to trigger from a pushed tag, the current workflow would get triggered from the new commit, create a loop. It's probably safest/easiest to just add it in a subsequent job in the same workflow, post semantic-release. The job would just have to check out the correct tag, which can be obtained from the semantic-release job's output variable.

**Comment by kyranjamie** [comment]
@markmhx can you test this?

**Comment by markmhx** [comment]
Yup should I just look at the latest PR / build?

**Comment by kyranjamie** [comment]
Yeah, get latest build (no _update available_), wait for new build, check it's there

**Comment by markmhx** [comment]
It seems to work

![image](https://user-images.githubusercontent.com/28991/104124913-cbb59c80-5353-11eb-8be6-fb7a705aeb74.png)

**Comment by kyranjamie** [comment]
_Seems_ is good enough for me. Thanks for checking.
