### ISSUE TITLE
Add feature to verify Ledger address

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#462]
[Re discussion in Slack](https://ledger-dev.slack.com/archives/G013HKZRC3X/p1609927638042100), a mandatory feature is being able to verify your wallet address, where it shows both on the device and in the wallet at the same time.

**Comment by markmhx** [comment]
@timstackblock I believe any of the most recent builds will allow you to test this

**Comment by timstackblock** [comment]
I verified this last week, looks good
