### ISSUE TITLE
Stacking progress box displays incorrect bitcoin address after successful stacking

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#469]
Stacking progress box displays incorrect bitcoin address after successful stacking I have not received my rewards yet but there is also the possibility that we are sending the BTC to that address as well

https://stacks-node-api.blockstack.org/extended/v1/tx/0x0b82b08b49c249496f51e35bcc5e1300cc9f3496eed128fb13a2c41c05f9fc73

Transaction: 0x0b82b08b49c249496f51e35bcc5e1300cc9f3496eed128fb13a2c41c05f9fc73
Used bitcoin address: mmPKhbTX4mM4R6LAJDfq3yaRR2WHs6XkJS
But the address that dispays is 16sNQYNYFjuodyrYaehTE4N6Z2uavLkWdq

https://stacks-node-api.blockstack.org/extended/v1/tx/0x0b82b08b49c249496f51e35bcc5e1300cc9f3496eed128fb13a2c41c05f9fc73

ADDRESS ENTERED
<img width="531" alt="Screen Shot 2021-01-08 at 12 54 26 PM" src="https://user-images.githubusercontent.com/49165468/104048286-fd423280-51b0-11eb-914a-134044a10a32.png">

ADDRESS DISPLAYED
<img width="425" alt="Screen Shot 2021-01-08 at 12 54 50 PM" src="https://user-images.githubusercontent.com/49165468/104048226-e3a0eb00-51b0-11eb-84ac-3aa037c8981c.png">

**Comment by timstackblock** [comment]
I no longer get the progress box in the wallet

**Comment by timstackblock** [comment]
<img width="1189" alt="Screen Shot 2021-01-13 at 3 51 29 PM" src="https://user-images.githubusercontent.com/49165468/104509131-3a466480-55b7-11eb-8203-aa1b75196f46.png">

**Comment by markmhx** [comment]
@kyranjamie was this an intended change since I know you wanted to modify the stacking progress UI?

**Comment by kyranjamie** [comment]
I made significant changes yesterday evening to stacking, have not been able to replicate infinite spinner.
