### ISSUE TITLE
Trezor dialog usability: ambiguous heading and awkward order

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-wallet#47]
Interesting, I did this sequence:

1. Connected my trezor via USB.
2. Choose connect to Hardware Wallet
    Purple screen
3. Choose Trezor.
4. Choose Continue.
     See this:
     
![image](https://user-images.githubusercontent.com/1347209/49184697-e6b02880-f314-11e8-80d3-f3b203b16c6f.png)

**Expected**:  System should detect my Trezor
** Env** Mac Mojave
**Trezor** Model T

### Other Notes

This says connect the device and then press continue.

![image](https://user-images.githubusercontent.com/1347209/49184454-48bc5e00-f314-11e8-88f7-229b5edc9f01.png)

Also, "to continue" doesn't seem appropriate as there is no next button. If there is an order dependency, maybe just use numbers and remove the & which is pretty tiny.

![image](https://user-images.githubusercontent.com/1347209/49184218-a9976680-f313-11e8-85f0-5505679c9fd7.png)

What does  **Export public key** mean in this context? Sounds like an action looks like a heading but how will I get back to this dialog to do an export.

![image](https://user-images.githubusercontent.com/1347209/49183720-6f799500-f312-11e8-8000-e620a95396da.png)

**Comment by markmhx** [comment]
I'm closing this issue since we can't control or know the steps or UI of hardware wallets generally and relate them to our UI.
