### ISSUE TITLE
Wallet doesn't work past "Make sure you have "Browser Support" set to no" with up-to-date Ledger Nano S

### ISSUE THREAD

**Issue by npinto** [blockstack/stacks-wallet#493]
There is no Browser Support on the settings of the Bitcoin App 1.5.5 and once I click next, it doesn't work.

Any hint on how to fix this? I'm running the 3.1.1 on macOS.

Thanks for your help!

**Comment by npinto** [comment]
Version 3.0 seems to work for this. How can 3.1.1 isn't working for such a simple access?

**Comment by npinto** [comment]
https://github.com/blockstack/stacks-wallet/issues/124#issuecomment-728781924

**Comment by markmhx** [comment]
This appears to have been related to Stacks 1.0 entering read-only mode ahead of Stacks 2.0 release.

@npinto please try the new Stacks Wallet found here for Stacks 2.0 and let us know if we should re-open this issue, in the case that it doesn't work for you: https://www.hiro.so/wallet/install-desktop
