### ISSUE TITLE
Fix sending with Ledger Nano X devices

### ISSUE THREAD

**Issue by VI510N** [blockstack/stacks-wallet#500]
while attempting to send Stacks, transaction gets stuck at "sign transaction on ledger". Transaction was confirmed on ledger and defaults back into stacks app on ledger. Meanwhile button is send button is stuck spinning. This is occurring on Ledger Nano X.
<img width="487" alt="Screen Shot 2021-01-14 at 8 39 54 PM" src="https://user-images.githubusercontent.com/77476698/104682640-00a25600-56aa-11eb-95d8-b0eea54791e5.png">
<img width="279" alt="Screen Shot 2021-01-14 at 8 53 01 PM" src="https://user-images.githubusercontent.com/77476698/104682903-a3f36b00-56aa-11eb-8242-f23f9b15b11a.png">

**Comment by kyranjamie** [comment]
Thanks for reporting this issue @VI510N, investigating now

**Comment by markmhx** [comment]
@VI510N We've confirmed this is a compatibility issue with Ledger Nano X devices and are working to resolve it ASAP with a patch. However, given the weekend has arrived and we'll need the help of a firm working with us on the Stacks app for Ledger, we probably won't get this resolved until early next week. 

Our apologies for the inconvenience. We'll update here as soon as it's resolved. 🙏

**Comment by markmhx** [comment]
This work is getting tracked now on the Stacks app for Ledger side here: https://github.com/Zondax/ledger-blockstack/issues/48

**Comment by markmhx** [comment]
The fix for this has been made and just needs review by Ledger and deployment to Ledger Live, which should happen soon.

**Comment by markmhx** [comment]
This fix is now available as part of the latest version of the Stacks app listed on Ledger Live. Please upgrade within Ledger Live if you've encountered this problem.

If you've previously set your "Manager provider" to 4 under "Experimental features" in Ledger Live's settings, you'll need to toggle it off or otherwise set to 1 before this version appears for installation.
