### ISSUE TITLE
Add build guidance to releases and clarify filenames

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#502]
Now that users will get directed to this page from the "Updates available" prompt, we should provide guidance for each release description that helps the user choose which file to download given:

- Their need for mainnet vs. testnet
- Their operating system

That way users aren't confused as what to do on this page.

![image](https://user-images.githubusercontent.com/28991/104704079-7b09bf00-5718-11eb-9315-6580d63198a4.png)

**Comment by markmhx** [comment]
This sort of copy could go a long way:

> Please download the latest version of the Stacks Wallet as appropriate for your operating system from the list below under "Assets".
> 
> Look for the option with "mainnet" in the filename that also ends with the extension suitable for your operating system:
>
> - MacOS users select file ending in `dmg` (e.g. `stacks-wallet.mainnet.v[number].dmg`)
> - Windows users select file ending in `exe` (e.g. `stacks-wallet.mainnet.v[number].exe`)
> - Linux users select file ending in `deb` or `rpm` (e.g. `stacks-wallet.mainnet.v[number].deb`)
>
> Please do _not_ download any option with "testnet" in the filename unless you're looking to download a version that works only against the Stacks Testnet. This version will not be suitable for sending and receiving STX for any "real" purposes. It is only recommended for developers and testers.

**Comment by kyranjamie** [comment]
Yeah we can add this to the build script quite easily

**Comment by markmhx** [comment]
I'm expanding this issue a bit to include improvements to the filenames as well since as @yknl pointed out, users can't easily tell which is for what operating system upon glance.

We should use a filename format that specifies each operating system clearly e.g. `stacks-wallet.mainnet.windows.v4.1.0.exe`

**Comment by kyranjamie** [comment]
I must admit I find it hard to believe someone downloading the cryptocurrency wallet of the 80th biggest project, doesn't know Windows uses `.exe` files 🤷🏼 
I'd prefer to keep the filenames the same, as we already do a lot of string formatting to target the correct file name in CI, this'd add to it. It's also [not a recommended practice for AppImages](https://docs.appimage.org/packaging-guide/distribution.html?highlight=linux#do-not-put-linux-into-the-appimage-file-name).

I'd suggest we create a table in the release body (maybe with some nice Windows icons) to point users to the correct build.

| Operating System | Download Link |
|------------------|---------------|
| MacOS (.dmg)     | [Download Link](url) |
| Windows (.exe)   | [Download Link](url) |

**Comment by yknl** [comment]
> I must admit I find it hard to believe someone downloading the cryptocurrency wallet of the 80th biggest project, doesn't know Windows uses `.exe` files 🤷🏼 , and why are they not downloading from hiro.so/wallet which already navigates by OS?

When you click the "Update available" button in the wallet UI, it takes you directly to the GitHub page. That's where people start getting confused. Also, the Testnet versions are confusing to people as well. I've seen people ask why their wallet suddenly switched to Testnet. I'm guessing it's because they clicked on the Testnet binary. Even as someone who understands this stuff, it took me a few extra seconds to find the binary I'm looking for. And it's quite easy to not pay attention to the "testnet" part.

**Comment by andresgalante** [comment]
@yknl has a point, I was confused by it too. Why not link it to hiro.so/wallet ?

**Comment by markmhx** [comment]
This issue will be mitigated by https://github.com/blockstack/stacks-wallet/issues/688 but will remain useful for users who find the release page through other routes.
