### ISSUE TITLE
Restore Ledger functionality with testnet builds

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#509]
Currently the integration is incorrect given the compatibility patch made to the Stacks app for Ledger.

**Comment by kyranjamie** [comment]
This will require corporation with Zondax to expand the APIs exposed for the device, so mainnet & testnet addresses can be derived from the same derivation path.

**Comment by markmhx** [comment]
Have you given them a heads up already / should we create a related issue in the Ledger app repo for them?

**Comment by kyranjamie** [comment]
@markmhx logged here https://github.com/Zondax/ledger-blockstack/issues/52
