### ISSUE TITLE
Fix ability to send multiple transactions for same block with better nonce handling

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#513]
Wallet should track nonce locally to prevent `ConflictingNonceInMempool` error

**Comment by markmhx** [comment]
What use case(s) trigger this at the moment?

**Comment by kyranjamie** [comment]
Multiple txs in the same block

**Comment by markmhx** [comment]
@timstackblock this appears ready to test with https://github.com/blockstack/stacks-wallet/pull/554
