### ISSUE TITLE
"Password entered is incorrect" wrong error message?

### ISSUE THREAD

**Issue by jefreybulla** [blockstack/stacks-wallet#518]
When trying to transfer STX, the wallet displays an error: "Password entered is incorrect". However I double checked my password. Is is possible that the wallet is displaying a wrong message?

**Comment by markmhx** [comment]
I believe @kyranjamie is pushing a fix shortly with v4.0.2 that resolves this.

**Comment by asapstak** [comment]
i got the same problem in 4.1.2

**Comment by markmhx** [comment]
@asapstak Mind restoring the wallet and setting it up again to confirm that the password entry still doesn't work for you at that point?
