### ISSUE TITLE
BTC from old Blockstack wallet?

### ISSUE THREAD

**Issue by doffing81** [blockstack/stacks-wallet#519]
I sent some BTC to my old stacks wallet in order to try out a send, but that didn't work, so I updated to the newest release (4.0.2), and it looks like there is no way to access the BTC I sent to the old version of the wallet (3.1.1)?

**Comment by kyranjamie** [comment]
Stacks 2.0 doesn't use BTC for transaction fees, so the new wallet doesn't display bitcoin balances from the previous wallet. We implemented a way to withdraw these funds in [an older version of the wallet](https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.1).

**Comment by doffing81** [comment]
Ok, thank you. I suppose I will have to downgrade to get the BTC then.
