### ISSUE TITLE
Provide guidance around Secret Key restore

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#522]
Some users are confused when trying to restore, what they know as their seed phrase, in the Secret Key box.

<details>
<summary>Discord context</summary>
I've seen this occur in one other instance as well

![image](https://user-images.githubusercontent.com/1618764/104819022-3753aa00-582b-11eb-8ee9-d517349948ad.png)
</details>

Let's add some extra wording to make it clear this is aka a seed phrase

**Comment by markmhx** [comment]
Maybe it'd be easiest to add a little "i" or "?" icon here that when clicked goes to an FAQ page on Hiro.so?

<img width="490" alt="Screen Shot 2021-01-17 at 12 37 19" src="https://user-images.githubusercontent.com/28991/104839359-c8289500-58c0-11eb-9df1-4625b4bc4b71.png">

**Comment by kyranjamie** [comment]
I've added this in https://github.com/blockstack/stacks-wallet/pull/523

![image](https://user-images.githubusercontent.com/1618764/104839478-b09ddc00-58c1-11eb-909f-96d7c7532855.png)

**Comment by markmhx** [comment]
I'm thinking a full page link could help more here since we could include additional information about the various types of seed phrases from past sales, as compared to the Blockstack Browser, etc. @ryanarndtcm has run into this so he may have ideas as well for what to include here.

**Comment by kyranjamie** [comment]
Happy to add link as well in addition too. I think it's important we show explain the Secret Key = seed phrase inline.

**Comment by kyranjamie** [comment]
Happy to add link as well in addition too. I think it's important we show explain the Secret Key = seed phrase inline.

**Comment by markmhx** [comment]
Let's link to here: https://www.hiro.so/questions/what-are-secret-keys-and-how-do-they-work

**Comment by markmhx** [comment]
I'm closing this since it's getting resolved with https://github.com/blockstack/stacks-wallet/pull/534.
