### ISSUE TITLE
Refactor modal components

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#525]
These components have grown too large, and go against some React best practices resulting in some unpredictable, difficiult behaviours.

- [ ] Replace the modal component with one with a more friendly api
- [x] Compose the transaction form modal down into smaller components
- [x] Compose the stacking modal down into smaller components
- [ ] Write tests for these components

This would also be a good time to revisit any design improvements we want in this flow.

**Comment by markmhx** [comment]
@kyranjamie are you still expecting to address this as part of the end-to-end tests milestone? Or best we remove from it?

**Comment by TgTruNc** [comment]
thanks
