### ISSUE TITLE
Your transaction failed to verify

### ISSUE THREAD

**Issue by wrayjohn157** [blockstack/stacks-wallet#532]
After 3 successful tx's the tx will not verify and process. Wallet was restored with same issue. v4.0.2. Sofware wallet, not hardware i.e. ledger being used.
![image](https://user-images.githubusercontent.com/54514642/104962804-35165a80-59a7-11eb-84b2-4b4be01d696c.png)

**Comment by markmhx** [comment]
I imagine this could be related to https://github.com/blockstack/stacks-wallet/issues/513. 

@wrayjohn157 does this error still appear if you wait over, say, an hour to send the next transaction?

**Comment by wrayjohn157** [comment]
Test withdrawal going through now. tx pending but its progress.

**Comment by markmhx** [comment]
@wrayjohn157 I'm going to close this out since your test withdrawal went through, but please let me know if you continue having difficulty with any transactions and I'll re-open.
