### ISSUE TITLE
Detect closure of Ledger Live without having to go back and forward

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#545]
If a user arrives at the transaction signing modal with Ledger Live open and their device authorized with the "Manager" section, the "Connect your Ledger" and "Open the Stacks app" steps won't show as complete even if the user closes Ledger Live and opens up the Stacks app on their device.

The user currently needs to close the modal then re-engage it for those steps to show as complete, which isn't intuitive.

Ideally we could detect from this modal automatically that the user has closed Ledger Live and opened the Stacks app. If that's not technically possible, we should improve the guidance on this screen and perhaps add a button for the user to manually trigger whatever happens when they close and re-open the modal to re-engage the Ledger's status.

I believe this problem is also affecting authentication into the wallet upfront as well.

<img width="496" alt="Screen Shot 2021-01-20 at 12 16 56" src="https://user-images.githubusercontent.com/28991/105168392-5ea3c300-5b1a-11eb-8c57-2a298f9600df.png">

This came up when meeting with @ades5.

**Comment by markmhx** [comment]
@kyranjamie Is this a state change we can detect automatically within the modal upon close of Ledger Live?

**Comment by kyranjamie** [comment]
I'll need to test this. All these kinds of actions require polling the device to check it's state, which is both the cause of, and solution to various issues.

**Comment by markmhx** [comment]
This interaction might get worked out by #527

**Comment by markmhx** [comment]
@jasperjansz to provide "checking Ledger status" state guidance

**Comment by markmhx** [comment]
@kyranjamie should we move this to QA for testing against v4.1.1?

**Comment by markmhx** [comment]
This works for me in v4.1.1 💪
