### ISSUE TITLE
Improve confirmation UX for initiating Stacking

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#546]
Resolve a few UX issues immediately after signing the transaction to initiate Stacking:

1. The "Stacking initiated" transaction item in activity delays in appearing, perhaps a few seconds on average
2. The item says "Function call" which most users won't understand in relation to Stacking
3. The item shows a spinner, as well as the right-hand CTA section, while stating "Pending", though it's not obvious to the user whether they need to sit here and wait or can close out the Stacks Wallet / do other things since it's just pending on the blockchain.

We may want to resolve the third item here in particular by showing a confirmation screen entirely that explains that Stacking is initiated and will just need pending on-chain, but that the user can go about their day without waiting. 

We should also probably remove the spinner on the right-side entirely since it especially appears like a UI item that the user should wait for loading.

<img width="1266" alt="Screen Shot 2021-01-20 at 12 26 08" src="https://user-images.githubusercontent.com/28991/105169183-7465b800-5b1b-11eb-8642-015554f767bc.png">

This came up when meeting with @ades5 as well.

**Comment by jasperjansz** [comment]
Proposal for short term: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=4133%3A424

1. Show stacking card regardless if pending or transaction confirmed (assume it will confirm)
2. Suggest we remove the transaction type (token transfer, function call) from the transaction subtitle

**Comment by markmhx** [comment]
The concerns in this issue have been largely resolved by now.
