### ISSUE TITLE
When you attempt to send STX there is a 3 second load time after clicking the password confirm button 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#549]
There is a delay when submitting a transaction in the wallet, it makes the user think they have to click the button multiple times. The first click takes a few seconds to trigger any change in the UI so the user will continually click the button until because there is no confirmation that the first click did anything. This happens for any transaction in the wallet. Similar issue filed below for stacking.

We should speed this up so the transaction happens instantly or at the very least make the UI display something that lets the user know the action is taking place.

Similar to the issue mentioned here
https://github.com/blockstack/stacks-wallet/issues/442

**Comment by markmhx** [comment]
@timstackblock this appears ready to test with https://github.com/blockstack/stacks-wallet/pull/554
