### ISSUE TITLE
Faster feedback of successful transaction

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#552]
The UI can be slow to update upon completion of a successful transaction. Previously we had a faster poll rate, however with an increased time the delay is increased.

Ideally we'll have websockets soon, but in the meantime, we should trigger a refresh quicker so to display pending txs immediately.

**Comment by markmhx** [comment]
I just submitted the preview form and saw the "Send" button revert back to normal pre-submit state for several seconds before the modal closed. Is that resolved as part of this?

<img width="499" alt="Screen Shot 2021-01-26 at 15 03 17" src="https://user-images.githubusercontent.com/28991/105855150-0cfeab00-5fe8-11eb-9520-228f701ef7a8.png">

**Comment by kyranjamie** [comment]
I don't think so. This step doesn't do any requests I think so no idea how this happened.

**Comment by markmhx** [comment]
This time it reverted back but only very briefly (and note it's actually the password submission form):

![Kapture 2021-01-26 at 15 15 52](https://user-images.githubusercontent.com/28991/105856343-6ddab300-5fe9-11eb-82f2-0287f3429823.gif)

**Comment by andresgalante** [comment]
I just tested it out, I can reproduce it. It went back to solid blue for at least 2 seconds before closing the Modal

**Comment by kyranjamie** [comment]
Issue was that the spinner was just for password decrypt action. Fixed in 4.0.4
