### ISSUE TITLE
[4.0.3] Bug: <describe issue>

### ISSUE THREAD

**Issue by Ro853** [blockstack/stacks-wallet#553]
Good day. 01/20/201, after installing the wallet, I mistakenly sent from my address https://explorer.stacks.co/address/SPEBV6N05ADNPGJEE37MYJP28HFATJZKGF508BD9 coins in the amount of 99.9 STX to SP29TZ7H3ZTDCQBCVVHZ0099HM37S34 Where did the address SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS come from, I do not know, since I used the wallet for the first time. Perhaps it appeared when resetting the wallet login.
How can I now, through the wallet, go to the address SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS?
Transaction confirmation: https://explorer.stacks.co/txid/0xeb2d1b7a4911519e1e810965b8fedae6a021b0f2495f2c39979b236140b31245?utm_source=stacks-wallet&chain=mainnet
I ask you to help and consider my question.
Bug found testing Stacks Wallet build undefined, 4.0.3.

**Comment by kyranjamie** [comment]
Hi @Ro853 

How did you send coins to this address? It appears to be an invalid address

![image](https://user-images.githubusercontent.com/1618764/105488190-8e390380-5cb1-11eb-8d3c-5fa0ee99a1e1.png)

**Comment by Ro853** [comment]
Sorry.  SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS   — address.
  
>Пятница, 22 января 2021, 14:59 +03:00 от kyranjamie <notifications@github.com>:
> 
> 
>Hi  @Ro853
>How did you send coins to this address? It appears to be an invalid address
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Давид Гоцман

**Comment by kyranjamie** [comment]
Your question is:

> Where did the address SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS come from, I do not know, since I used the wallet for the first time. 

But you sent to this address? `SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS`? 

To access these funds, you'll need the private keys to this address.

**Comment by Ro853** [comment]
Is it impossible to recover the keys?

  
>Пятница, 22 января 2021, 15:12 +03:00 от kyranjamie <notifications@github.com>:
> 
> 
>Your question is:
>>Where did the address SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS come from, I do not know, since I used the wallet for the first time.
>But you sent to this address? SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS?
>To access these funds, you'll need the private keys to this address.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Давид Гоцман

**Comment by Ro853** [comment]
Add   a node
 
 
Enter an address from the Stacks Blockchain API that proxies a node. Before using a node, make sure you review and trust the host before configuring a new API.
Name
URL
Cancel Add   node
 
 
>Пятница, 22 января 2021, 15:12 +03:00 от kyranjamie <notifications@github.com>:
> 
> 
>Your question is:
>>Where did the address SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS come from, I do not know, since I used the wallet for the first time.
>But you sent to this address? SP29TZ7H3ZTDCGVVV0099HMQVHZK37GRTBC934BVS?
>To access these funds, you'll need the private keys to this address.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
Can I use this method?
 
--
Давид Гоцман

**Comment by kyranjamie** [comment]
Yes, I'm sorry, this is a behaviour of blockchains.

If you send funds to the wrong address, by mistake, yes. There's no centralised authority to revert this action. We do our best in the UI to prevent users from making mistakes like this.

**Comment by Ro853** [comment]
Are these addresses assigned only by the wallet or can crypto exchanges create them too?

  
>Пятница, 22 января 2021, 15:18 +03:00 от kyranjamie <notifications@github.com>:
> 
> 
>Yes, I'm sorry, this is a behaviour of blockchains.
>If you send funds to the wrong address, by mistake, yes. There's no centralised authority to revert this action. We do our best in the UI to prevent users from making mistakes like this.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Давид Гоцман

**Comment by kyranjamie** [comment]
Anyone can create addresses.

**Comment by Ro853** [comment]
Before traction, I was registered for   gate.io . I'll send them a request.

  
>Пятница, 22 января 2021, 15:23 +03:00 от kyranjamie <notifications@github.com>:
> 
> 
>Anyone can create addresses.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Давид Гоцман
