### ISSUE TITLE
[4.0.3] Ubuntu: installer doesn't add app shortcut/icon to the start menu

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-wallet#555]
Using Ubuntu Mate v20.04 in a VM.  Installing 4.0.3 using `dpkg` or `gdebi` to install there is no entry placed in the start menu.
This should be done by default, no?

**Comment by kyranjamie** [comment]
Any screenshots? I've tested on Fedora and Mint

![image](https://user-images.githubusercontent.com/1618764/105493636-f1c72f00-5cb9-11eb-990c-783ed33403e2.png)

**Comment by fluidvoice** [comment]
![Screenshot_2021-01-22_11-45-12](https://user-images.githubusercontent.com/373038/105505172-65137580-5ca7-11eb-851f-cad3d97f9898.png)

**Comment by markmhx** [comment]
@timstackblock Mind testing this as well?

**Comment by fluidvoice** [comment]
hmmm, just tested 4.0.4 and still no go for me. I wonder if something specific to my VM instance.

**Comment by fluidvoice** [comment]
It looks like what is happening is the installer is installing the icon/entry but is not selecting/enabling it so the "Other" category doesn't show up in the start menu.

![image](https://user-images.githubusercontent.com/373038/106318273-708a1200-624e-11eb-87d9-173e1da6f2c5.png)

**Comment by fluidvoice** [comment]
> Using Ubuntu Mate v20.04 in a VM. Installing 4.0.3 using `dpkg` or `gdebi` to install there is no entry placed in the start menu.
> This should be done by default, no?

a related issue perhaps the icon also does not show up when the wallet is running see mouse pointing in this image

![image](https://user-images.githubusercontent.com/373038/106329231-daf77e00-625f-11eb-806a-f63a62debcf9.png)
