### ISSUE TITLE
Ledger X freezing on "Pending review" screen

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#556]
**Problem**
The Leger X sometimes crashes when on the "Pending review" screen. [Discussed in Ledger slack here.](https://ledger-dev.slack.com/archives/G013HKZRC3X/p1610618668015000)

**Cause**
There is a polling mechanism in place to check the device status. If 2 or more requests are made to the device while on this pending screen, the device crashes. Reducing the polling interval, and not polling in certain circumstances, lowers but does not remove the chance of this happening.

**Solution**
I believe this problem will go away when the app is audited. Some investigation is needed in order to remedy this until then.

**Comment by markmhx** [comment]
Ledger Live tells me my device has gone into "Bootloader mode" after going dark (for quite awhile unresponsively), but the "Continue" button doesn't do anything:

![image](https://user-images.githubusercontent.com/28991/105505827-b46a9d80-5cc9-11eb-8881-3be3c62fb51d.png)

**Comment by markmhx** [comment]
Is this a problem with which Zondax can help us resolve? If so, we should create a related issue in https://github.com/Zondax/ledger-blockstack/

**Comment by kyranjamie** [comment]
Nope, this is all Ledger.

**Comment by markmhx** [comment]
It appears this was fixed by https://github.com/Zondax/ledger-blockstack/issues/43. We can re-open if the problem reemerges.
