### ISSUE TITLE
Error installing updated version on OSX El Capitan 10.11.16

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/stacks-wallet#557]
_Hi there I have been trying to download the new wallet and send my stx there but no luck. Very disappointed for last 2 weeks since launch.

Many others having the same issue as per telegram chat.

Everytime I download app in my Mac ( OX EI Captain- 10.11.06) it will install the old app, now I noticed there is a update available link & tried but same issue.

Forget stacking i am not able to use a decent wallet ! Some screenshot attached._

![image](https://user-images.githubusercontent.com/52256509/105540213-39ef4d00-5ccc-11eb-8afe-679c98884ddd.png)
![image](https://user-images.githubusercontent.com/52256509/105540242-47a4d280-5ccc-11eb-9da3-4a9be9bdf857.png)
![image](https://user-images.githubusercontent.com/52256509/105540267-54292b00-5ccc-11eb-86ce-ab9ff0c4cca6.png)
![image](https://user-images.githubusercontent.com/52256509/105540297-5ee3c000-5ccc-11eb-9398-28faa63cdd09.png)

**Comment by kyranjamie** [comment]
Well I am sorry to disappoint said user.

As I understand this explanation, on El Capitan isn't able to install the new version over the old one? I'm curious how this happens. It'd be helpful to see how it's being installed. 

I'd try the following steps:
1) Ensure you have a paper backup of your Secret Key/seedphrase
2) Delete the `Stacks Wallet.app` from `/Applications`
3) Install the latest `4.0.3` version

**Comment by markmhx** [comment]
If the user is trying to send STX to the Stacks Wallet, they shouldn't actually need to update to the latest v4.x.x version here (since they're already on some v4.x version compatible with Stacks 2.0).

Can't they click "Receive" in the UI and send STX to that address?
