### ISSUE TITLE
[4.0.3] Bug: Stacks Wallet 1 with Trezor - don't let me send STX

### ISSUE THREAD

**Issue by Dee88888** [blockstack/stacks-wallet#561]

**Comment by kyranjamie** [comment]
You need to use the latest version of the stacks wallet. See instructions for Trezor users here https://www.hiro.so/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet

**Comment by Dee88888** [comment]
I am not gonna buy a ledger, and that should not be a solution for your bugs.

second option: Enter the 12- or 24-word recovery phrase you saved when originally setting up our Trezor device directly into the wallet upon selecting "Sign In" and viewing a prompt for your "Secret Key".
(are you talking about the newest version of the stacks wallet? cos I have done that and nothing)

**Comment by aulneau** [comment]
> I am not gonna buy a ledger, and that should not be a solution for your bugs.

This is not because of a bug, see this from the link above:

> This is due to how Trezor supports integrations, in which the company's availability and engagement is required to set them up in contrast to Ledger's open model.

If you have the correct 12 word phrase from your Trezor, you should be able to enter it into the latest version of the stacks wallet (v4) in software mode.
