### ISSUE TITLE
[4.0.3] Bug: <describe issue>

### ISSUE THREAD

**Issue by sasha199511** [blockstack/stacks-wallet#562]
Bug found testing Stacks Wallet build undefined, 4.0.3.

**Comment by sasha199511** [comment]
hi program write me to my password incorect

**Comment by kyranjamie** [comment]
Hi @sasha199511,

This isn't really enough information for us to help you. It's quite possible you're using a different password.

You can alway reset your wallet and restore with your Secret Key and set a new password. We recommend using a password manager.
