### ISSUE TITLE
[4.0.3] Bug: Using a different Ledger warning

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#565]
When trying to test the Nonce update for the desktop wallet I am un able to send a transaction with ledger X on a windows 10 machine

Bug found testing Stacks Wallet build c5251a3, 4.0.3.

![Screenshot (7)](https://user-images.githubusercontent.com/49165468/105858709-9fd42100-5fb9-11eb-917f-8be0a0d8d110.png)

![Screenshot (6)](https://user-images.githubusercontent.com/49165468/105858729-a498d500-5fb9-11eb-9eca-2675416ff0c5.png)

![Screenshot (5)](https://user-images.githubusercontent.com/49165468/105858742-a95d8900-5fb9-11eb-9547-7fa82aea9f65.png)

**Comment by kyranjamie** [comment]
@timstackblock can you open dev tools so we can see the network error? It should print the error on the screen (unless it's null)

**Comment by timstackblock** [comment]
I think this issue was caused by deleting the old version of the wallet which had a wallet that was logged in with my nano S and closed out. Then installing the new version and logging in but never resetting the wallet. This is not normal behavior I guess the only bug

**Comment by markmhx** [comment]
@jasperjansz may want to tackle a design for this error state alongside https://github.com/blockstack/stacks-wallet/issues/609
