### ISSUE TITLE
Infinite spinner with Nano X when opening the stacks app on the ledger

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#566]
The user will intermittently get an infinite spinner when connecting with the ledger nano X. In order to get into the wallet successfully the user sometimes has to back out and open the app on the ledger nano X before going to the connect your ledger screen.

If they do not they will get the connection issue below which gives an infinite spinner.

![Screenshot (9)](https://user-images.githubusercontent.com/49165468/105868944-b3d15000-5fc4-11eb-8a23-c6c7406a40a0.png)

**Comment by kyranjamie** [comment]
When this happens, does the device display your address to be approved, or does this happen after you've pressed approve?

The spinner starts and won't stop until you either 1) approve, where it'll go to home screen or 2) reject, tells you to approve

**Comment by markmhx** [comment]
Ping @timstackblock ☝️

**Comment by suspended** [comment]
> In order to get into the wallet successfully the user sometimes has to back out and open the app on the ledger nano X before going to the connect your ledger screen.

This workaround works for Ledger Nano S 1.6.1

**Comment by markmhx** [comment]
@kyranjamie should we move this to QA for testing against v4.1.2?
