### ISSUE TITLE
Add guidance about memos to send and receive modals

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#571]
It appears that a significant number of users attempting to send STX to exchanges that require transaction memos are failing to include such memos and finding their delivered STX in a sort of purgatory on those exchanges. They then have to follow up with the exchanges' customer support in an attempt to iron it out, though they initially start off confused and concerned that something has gone wrong with the Stacks Wallet itself.

We could perhaps help prevent this situation by adding a note here about the necessity of memos for certain types of transactions:

> ⚠️ Some transactions (such as to exchanges) require a properly formed memo to get processed successfully. [Learn more](http://hiro.so/questions/what-is-the-purpose-of-a-memo)

This note could combine the needs of https://github.com/blockstack/stacks-wallet/issues/490 to say:

> ⚠️ This value will get published to the Stacks blockchain publicly. Some transactions (such as to exchanges) require a properly formed memo to get processed successfully. [Learn more](http://hiro.so/questions/what-is-the-purpose-of-a-memo)

cc @agraebe  @GinaAbrams @ryanarndtcm

**Comment by fluidvoice** [comment]
The wallet should also provide some info about the memo usage to users when receiving transactions also to avoid confusion.
ie, some exchanges require to enter a memo when **sending** a Tx and if sending to the wallet it's fine to put in a "fake" memo (comment) maybe recommend "1234567" or a comment of your choice to identify the Tx.

**Comment by agraebe** [comment]
For context, this is how eg OKCoin is asking for a memo

![gSiM1faknRZik7LwadRdRULh8](https://user-images.githubusercontent.com/1671228/107964371-1089b000-6f5e-11eb-9c73-82ee3adb31b7.png)

**Comment by fluidvoice** [comment]
I will pass this on to OKcoin.  They should improve this info text to avoid confusing users.
State that it may be optional/not-required for some wallets and exchanges.

**Comment by markmhx** [comment]
Yea this is confusing for anyone who wants to withdraw just to the Stacks Wallet, which doesn't need a memo. I imagine users are seeing this text then going to the wallet and looking for a memo value there to copy and paste.

Perhaps on the _receive_ modal within the Stacks Wallet we can simply say:

> ℹ️ The Stacks Wallet does _not_ require a memo to receive STX. You can leave the memo field blank when sending STX to the address listed above, even if withdrawing from an exchange that instructs you to set a memo.

**Comment by fluidvoice** [comment]
> Yea this is confusing for anyone who wants to withdraw just to the Stacks Wallet, which doesn't need a memo. I imagine users are seeing this text then going to the wallet and looking for a memo value there to copy and paste.
> 
> Perhaps on the _receive_ modal within the Stacks Wallet we can simply say:
> 
> > information_source The Stacks Wallet does _not_ require a memo to receive STX. You can leave the memo field blank when sending STX to the address listed above, even if withdrawing from an exchange that instructs you to set a memo.

agreed. But in the event that an exchange enforces the use of memo (I think this is the case with Kucoin) perhaps we should say in this info message that users can put any "fake" memo or a short one or two word string to identify the transaction, which will be ignored by the wallet? not sure how to concisely phrase this.

**Comment by fluidvoice** [comment]
On second thought, I really think wallets should retain the use of the **memo/note** field if possible.
It provides potentially helpful accounting, reporting, and searching capabilities in future apps/wallets.

**Comment by haidersf** [comment]
> I will pass this on to OKcoin. They should improve this info text to avoid confusing users.
> State that it may be optional/not-required for some wallets and exchanges.

Thank you Fluidvoice. We acknowledge this is confusing, and currently working on a short term / long term fix. We'll prob have something out soon. Thanks again for flagging.

**Comment by ElaineSongGithub** [comment]
> I will pass this on to OKcoin. They should improve this info text to avoid confusing users.
> State that it may be optional/not-required for some wallets and exchanges.

Seconded Haider's point!

**Comment by markmhx** [comment]
I'm reopening since we have yet to address the case in which users are trying to withdraw to the Stacks Wallet from an exchange that advises they need a memo, even though a memo isn't needed for the Stacks Wallet receipt.

E.g. https://twitter.com/alixagaf/status/1405480902566813703
