### ISSUE TITLE
Ability to manually set fees

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#577]
In some cases users want to manually increase fees for transactions

**Comment by markmhx** [comment]
Per @hstove's note in Discord, these fees won't change the speed in which transactions get included in the next block until there's enough transaction volume to generate competition.

**Comment by agraebe** [comment]
The issue I had in mind is not likely to appear in the wallet, so the fee setting (even as a workaround) isn't relevant -- in addition to the fees not having an impact on the processing time right now. Closing!
