### ISSUE TITLE
[4.0.4] Bug: <Cannot confirm address on Stacks wallet>

### ISSUE THREAD

**Issue by stavros726** [blockstack/stacks-wallet#578]
Hi,

I followed all the steps described here

https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet-v4-x

and everything goes well until I open ledger live and stacks wallet and open the stacks app.

The stacks wallet app says that the next step is to confirm my address, but the only options I am given on my ledger Nano S after I enter the stacks app are:

Stacks ready
Expert mode enabled/disabled
Stacks version
Developed by
License 
Quit

So I cannot confirm my address.

Thanks for your help! 

Bug found testing Stacks Wallet build undefined, 4.0.4.

**Comment by kyranjamie** [comment]
Hi @stavros726 

The option to confirm your address only appears when you request it from the Stacks Wallet.

There are known problems when multiple programs try using the Ledger at the same time, so when using the Stacks Wallet, keep Ledger Live closed.

**Comment by stavros726** [comment]
Hello @kyranjamie

Thanks for your swift response!

I accessed my stacks using my secret phrase and it worked fine.

Thanks again!
