### ISSUE TITLE
[4.0.4] Cannot open new version of wallet with either Ledger Nano S or X

### ISSUE THREAD

**Issue by roleerob** [blockstack/stacks-wallet#594]
Tonight, I upgraded to the latest version of your Stacks wallet.  It will not open with either version of Ledger.  Specifically, it will not open with the Bitcoin app.  If I plug in my Ledger, #1 in your 3-step process receives a check mark.  When I open the Bitcoin app, that check goes away and nothing further happens.

My first use of your wallet was just at the end of last year, with version 3.1.1.  It took my awhile to figure out that I needed to set it up with the Bitcoin app.  Once I did, I was able to successfully deposit my STX tokens.  There is no specific STX app on Ledger Live.  Prior to upgrading to 4.0.4, I check and my balance of STX was still showing in the older version.

Please advise.  Thank you!

**Comment by aulneau** [comment]
Hi there!

The are some different steps that you need to take with the new version of the wallet. You can find the instructions here: https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet-v4-x

Namely you need to ensure you're on the latest firmware for your ledger device, enable dev mode, and install the stacks app. With older versions (before stacks 2.0) you had to use the bitcoin app, but now we have a Stacks specific ledger app!

Hope this helps, feel free to reply with any other questions :)

**Comment by roleerob** [comment]
Perfect @aulneau!  Never before needed to do anything with settings on my Ledger, so it never would have occurred to me.  As I have already mentioned, I got it to work the 1st time with the Bitcoin app, although that didn't seem all that obvious either ...

Thanks for the great and timely assist!
