### ISSUE TITLE
failed to broadcast  transaction[4.0.4] Bug: <describe issue>

### ISSUE THREAD

**Issue by gcgcgc** [blockstack/stacks-wallet#596]
Bug found testing Stacks Wallet build undefined, 4.0.4.
when send some stx to address it shows http error
{
  "error": "transaction rejected",
  "reason": "NotEnoughFunds",
  "reason_data": {
    "actual": "0x00000000000000000000000000000000",
    "expected": "0x00000000000000000000000023c34600"
  },
  "txid": "480c5a067c79ac1f8eb43c4883618d85afe408eb136241190c510ef47ae38be0"
}

**Comment by kyranjamie** [comment]
@gcgcgc Are you able to try again? This could well have been because of some API issues we were experiencing. Please reopen this issue if this is still happening.

**Comment by kelseyp99** [comment]
i am getting this error when I try to deploy through Stacks.js
transaction rejected
NotEnoughFunds

const transaction = await makeContractDeploy(txOptions);
const broadcastResponse = await broadcastTransaction(transaction, network);
const txId = broadcastResponse.txid;

**Comment by fbwoolf** [comment]
Similar issue here and the user just needed to restart the app: https://github.com/hirosystems/stacks-wallet/issues/1037
