### ISSUE TITLE
Failed to broadcast transaction

### ISSUE THREAD

**Issue by chicosci** [blockstack/stacks-wallet#597]
![stacks](https://user-images.githubusercontent.com/39632058/107179314-2f91ba80-6a11-11eb-8726-2512dcd5e615.png)

**Comment by timstackblock** [comment]
This is being resolved and should be working shortly, thank you for the report.

**Comment by kyranjamie** [comment]
These errors should now have been fixed API-side. Let us know if this problem continues @chicosci
