### ISSUE TITLE
Delegate transaction does not display in wallet instantly takes several minutes

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#598]
When I call the execute a delegation call in the wallet I do not see my wallet update with a transaction. it takes several minutes for the delegation box to update in the wallet. 

I can see 2 transactions in the explorer one for delegation and the other for stacking with the delegation address I entered as the delegator address. But in the wallet nothing updates for minutes.

<img width="1017" alt="Screen Shot 2021-02-09 at 2 53 08 PM" src="https://user-images.githubusercontent.com/49165468/107420998-79e56b00-6ae7-11eb-9417-0f25921f52c0.png">

<img width="1409" alt="Screen Shot 2021-02-09 at 2 50 49 PM" src="https://user-images.githubusercontent.com/49165468/107421021-7fdb4c00-6ae7-11eb-9cb0-8ff07fee90b2.png">

<img width="1402" alt="Screen Shot 2021-02-09 at 2 52 41 PM" src="https://user-images.githubusercontent.com/49165468/107421009-7c47c500-6ae7-11eb-816b-d0d9e0659578.png">

**Comment by kyranjamie** [comment]
@timstackblock Can you share the address in question? Is it correct that you haven't made a since 26th January?

**Comment by kyranjamie** [comment]
Just tested. 

![image](https://user-images.githubusercontent.com/1618764/107517844-90a2c500-6bae-11eb-9b91-46a1b8890b73.png)

The contract call does show up eventually, but only after it's successful.

@zone117x After a successful contract call of the `delegate-stx` function of pox contact, the tx never makes it to the mempool endpoint. Any ideas why this might be?

**Comment by timstackblock** [comment]
Here is the address 
https://explorer.stacks.co/address/SPFN121G9S35P8G926SP5D73BKR1V44PGSZ1XEKS?chain=mainnet

The wallet eventually updates its just very very slow. I can see people delegating multiple times thinking it did not go through the first time.

**Comment by timstackblock** [comment]
Used the lates version of the wallet and the delegation function call doesn't appear instantly in the wallet.
VERSION
refs/pull/579/merge
Commit: ba45363
[v4.0.4]

**Comment by kyranjamie** [comment]
Instantly, or at all? What kind of delay?

**Comment by timstackblock** [comment]
The function call comes in completed, so it doesn't come in pending. From the wallets point of view it is not visible in the pending transaction form after the user delegates so there may be some confusion there.

**Comment by timstackblock** [comment]
The pending transaction is not longer displaying when doing _stacking_ as well (not delegation but regular stacking in the wallet).

Seems like the same issue as with delegation please I get the completed call transaction line when the stacking box updates after the transaction is confirmed.

**Comment by kyranjamie** [comment]
Fixed. Stacking, delegation, revocation calls now add the pending tx properly, see 2303d9e

**Comment by timstackblock** [comment]
Thanks @kyranjamie
