### ISSUE TITLE
I have 3 transactions invalid but I have the correct balance

### ISSUE THREAD

**Issue by madela** [blockstack/stacks-wallet#599]
Hello,

On 8th January I made 3 transactions from Binance to my wallet. The balance on my wallet is correct but the 3 transactions seems to be invalid, and with the hiro.so wallet and they don't appear. 
![Screen Shot 2021-02-10 at 07 56 58](https://user-images.githubusercontent.com/5593359/107477268-beb8e280-6b77-11eb-9916-a223fac2b68c.png)

The invalid transactions are: 

[3eabc06cbf2a842e2153237abdf3c1e17a5f2933e6dd4930ff6e23e81f185da6](https://explorer.stacks.co/txid/3eabc06cbf2a842e2153237abdf3c1e17a5f2933e6dd4930ff6e23e81f185da6)
[0f7e58fdefbdc2afca8294e922fddeac1b55e43660c8b2e399beecc10197c23d](https://explorer.stacks.co/txid/0f7e58fdefbdc2afca8294e922fddeac1b55e43660c8b2e399beecc10197c23d) 
[75aca9c3cdb0b6b4ec57e2b0727a1736e8ffa043cc5beda18a1b6f12cdbe826f](https://explorer.stacks.co/txid/75aca9c3cdb0b6b4ec57e2b0727a1736e8ffa043cc5beda18a1b6f12cdbe826f)

However the balance on my wallet seems to be ok:

[SPJRZP06AZ6VJ5GAFPP75XHM3XRNHQW3TNB8M838](https://explorer.stacks.co/address/SPJRZP06AZ6VJ5GAFPP75XHM3XRNHQW3TNB8M838?chain=mainnet)

On 8th January, the transactions appear in the blockchain and I was able to see the confirmations, it's like they disappear. I don't understand how it's possible that I have an address with balance without any transaction incoming. Where did the funds come? 

I have contacted Binance about this issue but they said the they don't seen any transaction in my account. Are my funds safe?

Thanks

**Comment by markmhx** [comment]
Please download the new Stacks Wallet from here then see if the proper balance shows up on Stacks 2.0: https://www.hiro.so/wallet/install-desktop

You appear to be using the old version of the Stacks Wallet, which will not reflect any new transaction activity. The new wallet won't show any _old_ transactions from Stacks 1.0 (before mid January), but if the correct balance shows up, then your funds should be safe.

**Comment by madela** [comment]
Thank you very much for your help. I have downloaded Stacks 2.0 and my funds are correct. I just can't see the transactions as you pointed.

Glad to hear that my funds are safe
