### ISSUE TITLE
Improve BTC address validation error message

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#600]
Currently the Stacking initiation form says "only pubkey hash and scriptkey hash support" when the user enters an invalid BTC format.

Instead it should say the following with a link to the relevant FAQ:

> Please enter an address with format Legacy or Segwit (and not Native SegWit). [Learn more](https://www.hiro.so/questions/what-form-of-btc-addresses-can-i-use-for-proof-of-transfer-rewards)

**Comment by kyranjamie** [comment]
![image](https://user-images.githubusercontent.com/1618764/107945452-eea92100-6f8f-11eb-86af-44cf4bbcc8ad.png)
