### ISSUE TITLE
Remove rounding behavior for "Send Max" button in direct Stacking form

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#605]
Send Max button on stacking form should subtract the estimated fee of the transaction. So a user can see if they're below the amount.

A validation error should be thrown when trying to stack entire available balance.

**Comment by hstove** [comment]
The behavior I'm seeing is that "send max" rounds my balance down to an integer - so it's subtracting about 0.8 STX. But that's not the stack-stx fee. I think this behavior is fine, but wanted to make note. I will leave this up to @markmhx to determine if it's fine to close.

**Comment by markmhx** [comment]
@kyranjamie wasn't the initial approach here based on just rounding down but this issue in particular was meant to incorporate the fee more specifically?

**Comment by kyranjamie** [comment]
Rounding down to the nearest integer is intentional. If you stack your 100% max balance, which you can if you enter it directly, you won't have any funds with which to pay your fee to revoke.

**Comment by markmhx** [comment]
I'm a bit confused as to the problem we're trying to solve here? And why do any rounding at all when we know the exact fees needed for any given transaction these days?

**Comment by kyranjamie** [comment]
I don't think there is a problem with how it works currently. As mentioned above, if you stack entirely 100% of your balance, versus ~99.99%, you will have insufficient funds left to cover the fee for the revocation transaction.

**Comment by aulneau** [comment]
@kyranjamie I am confused as to why we're rounding when the fee is known?

**Comment by kyranjamie** [comment]
I can remove this functionality if everyone feels strongly about it. But no one has yet acknowledged the issue I've presented:

Encouraging a user to delegate 100% leaves them unable to revoke their delegation without topping up their wallet.

**Comment by aulneau** [comment]
> Encouraging a user to delegate 100% leaves them unable to revoke their delegation without topping up their wallet.

Ah that is what I was interested in. I think this makes sense :) it might be helpful to add a note about this in the UI.

**Comment by markmhx** [comment]
Is this the scenario you have in mind?

1. User has 100 STX
2. User delegates all 100 STX
3. Delegation service locks up all 100 STX for Stacking
4. User wants to revoke but has 0 STX available to do so

**Comment by kyranjamie** [comment]
Yes, exactly. For the take of a few cents, isn't it better to just round down to the nearest whole number? If a user desperately wants to delegate the fractions of their last STX, they can.

**Comment by markmhx** [comment]
I guess I'm confused then since we don't have a "Max" button here in the delegation form:

![image](https://user-images.githubusercontent.com/28991/108728463-ea4dac80-7529-11eb-9ec4-99b7479f224d.png)

And how do we square this sort of fee deduction with the decision to allow the user to enter any number of STX _above_ their current balance (since on a Clarity level, this isn't constrained to their current balance)? 

E.g.

1. User has 100 STX
2. User delegates maximum of 1,000 STX
3. User later adds 5,000 STX
4. Delegation service locks up maximum of 1,000 STX

**Comment by kyranjamie** [comment]
Uhhh. You're right, sorry this is in relation to stacking not delegation. Delegation doesn't have a send max button as there isn' a max.  So that's a mute point on not being able to revoke delegation.

**Comment by markmhx** [comment]
It was decided during our meeting yesterday that the remaining task for this issue is to remove the rounding behavior for the direct Stacking form specifically. No change is needed for the Stacking delegation form itself.
