### ISSUE TITLE
Prevent v4.x overwriting app data folder of v3.x

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#606]

**Comment by markmhx** [comment]
This is to allow users to re-install v3.x without problems, correct? In that we've received reports in which users aren't able to go back a version since they keep seeing v4.x when they open the app.

**Comment by kyranjamie** [comment]
On MacOS at least, they have the same name `Stacks Wallet.app`. So provided it's renamed, they should both work, see _"Keep Both"_

![image](https://user-images.githubusercontent.com/1618764/107938948-5bb7b900-6f86-11eb-919a-135adfcd6780.png)

There is a separate issue where an Electron 8 bug creates a `~/Library/Application Support/Stacks Wallet` folder, despite the fact the _actual_ app data is `.../so.hiro.StacksWallet`. This bug could cause issues issues between the two versions, but the impact of this should be small, though, as it's empty dir and the old wallet stores no valuable data that could be overwritten.

**Comment by kyranjamie** [comment]
I tested this a while ago but didn't update issue. The application data directory is not overwritten. Some users have encountered the problem as the old and new app _are_ called the same. This isn't going to change and users can always rename the app, so closing this out.
