### ISSUE TITLE
Phoenix wallet bc1 address not accepted for stacking

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-wallet#607]
I tried to use the [Phoenix mobile wallet](https://phoenix.acinq.co) "bc1" (native segwit?) address for stacking and it was not accepted.  The error message from memory was something like ... _"address not supported... must be P2PKH ..."_
Phoenix is a wallet that supports **both** BTC on-chain send/recv and Bitcoin Lightning send/recv.
So who is most at fault here?
Should the Stacks wallet support bc1 addresses or should Phoenix change?
What do other BTC+LN wallets use like bluewallet.io
IMO we should support what is used by most new wallets esp ones that support Lightning as more and more exchanges are supporting LN and this will continue to grow as BTC fees keep going up.

**Comment by kyranjamie** [comment]
This is a limitation of the pox contract itself, not the wallet.

Discussed briefly here: https://github.com/blockstack/stacks-blockchain/issues/1902

**Comment by kyranjamie** [comment]
I'm going to close out this issue. We do want to support Native SegWit addresses, but until the contract does, this isn't possible.
