### ISSUE TITLE
Wallet successfully delegates, locks and unlocks but corner right delegate box stills displays delegated 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#612]
The wallet successfully delegates, locks and unlocks but the corner right delegate box stills stays the same after unlocking. I would expect it to return back to normal after the end of a successful staking cycle the same way the stacking box does. This seems to me like it would stop the user from stacking or delegating again, is this the case?

1) Here is a picture of the stacks successfully locked after delegation in the wallet

<img width="1022" alt="Screen Shot 2021-02-13 at 7 00 32 PM" src="https://user-images.githubusercontent.com/49165468/107891777-c0bfd000-6eee-11eb-8a29-cfd996032f11.png">

2) Here is the STX address as a reference STF312GAEPAWBP8D7CP0JECVWS1VEK7XHFBYT5S9
<img width="1016" alt="Screen Shot 2021-02-13 at 7 00 56 PM" src="https://user-images.githubusercontent.com/49165468/107891793-d33a0980-6eee-11eb-9848-526785a87125.png">

3) Once the wallet unlocks after the stacking period I would expect the right box to go back to its original state so the user can stack or delegate again but it does not it stays the same
<img width="1018" alt="Screen Shot 2021-02-14 at 5 59 05 PM" src="https://user-images.githubusercontent.com/49165468/107891833-1bf1c280-6eef-11eb-86e3-b14384ce2ed6.png">

**Comment by kyranjamie** [comment]
This is expected behaviour afaik. STX remain delegated until you revoke, so your delegator can stack again.

**Comment by markmhx** [comment]
Yep this looks like expected behavior. The right-side module for delegation doesn't act the same way as the one for direct Stacking, since it's not showing state for Stacking per se – just delegation status. So, the Stacking state can keep changing but it'll stay the same (unlike with direct Stacking where it "reverts" so the user can initiate Stacking again).

**Comment by markmhx** [comment]
Also, it's great to see that the "locked" sub-balance is updating based on the state of delegated Stacking. ✨
