### ISSUE TITLE
[4.0.4] Bug: <describe issue>

### ISSUE THREAD

**Issue by ArtTheArtGuy** [blockstack/stacks-wallet#616]
Bug found testing Stacks Wallet build undefined, 4.0.4.

{
  "error": "transaction rejected",
  "reason": "NotEnoughFunds",
  "reason_data": {
    "actual": "0x00000000000000000000000000000000",
    "expected": "0x0000000000000000000000008c122834"
  },
  "txid": "6e7836b55a56f392d5059c1ae911a3b3468c016f1d21e862299e41cd31a20d98"
}
trying to send STX to another wallet and keep getting this message although there are plenty of funds. on a MacOS 

any help?

**Comment by kyranjamie** [comment]
@ArtTheArtGuy Can you try again? We were experiencing some issues with the API yesterday which might've caused this. 

Feel free to reopen if this persists.

**Comment by ArtTheArtGuy** [comment]
Hi Jamie

I did try a little earlier and all good, the wallet API is working a treat

thank you for looking at this

Art

**Comment by kyranjamie** [comment]
Glad to hear it!
