### ISSUE TITLE
[4.0.4] Bug: Delegation disabled due to lack of funds

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-wallet#617]
I'm seeing a "Insufficient balance" message and can't delegate with a fresh Stacks address. The balance is 0, but delegation itself shouldn't require a specific balance. Is there a UX argument for the balance check? I could see how users would start delegating while they wait for funds to be transferred to the account

Bug found testing Stacks Wallet build f305d92, 4.0.4.

**Comment by kyranjamie** [comment]
You need to be able to pay the fee.

**Comment by agraebe** [comment]
Ah, totally right. Requires >= 260 microSTX as per:
```const sufficientBalanceToCoverFee = availableBalance.isGreaterThan(260);```
