### ISSUE TITLE
refactor(ledger): move all logic to main thread, expose messaging api 

### ISSUE THREAD

**Issue by andresgalante** [blockstack/stacks-wallet#622]
This task aims to:

- Overhaul of the Ledger integration
  - Currently much of the connection logic takes place in the `preload.js` script
  - A more secure approach is to only perform this logic on main thread

**Comment by timstackblock** [comment]
@andresgalante @kyranjamie is this a full regression of all ledger transactions, or is this a place holder can you please elaborate.

**Comment by kyranjamie** [comment]
@timstackblock I've updated description, but what does 

> full regression of all ledger transactions

mean?

**Comment by timstackblock** [comment]
What needs to be tested for this issue, what is the scope of the change and how does it affect the wallet.

**Comment by kyranjamie** [comment]
Yeah, all functionality touching the Ledger will need to be retested.

**Comment by timstackblock** [comment]
ok will do thanks @kyranjamie
