### ISSUE TITLE
Stacks wallet not sending STX to OKCoin 

### ISSUE THREAD

**Issue by alex1580** [blockstack/stacks-wallet#626]
Bug found testing Stacks Wallet build undefined, 4.0.4.

**Comment by markmhx** [comment]
Could you elaborate on just what behavior you're seeing when trying to send STX to OKCoin?

**Comment by alex1580** [comment]
It's been two days I have made two transactions to OKcoin. I see the stx
out of the stx wallet, but not into OKcoin

Okcoin Helpdesk says i did not feel the memo correctly.

I filled it, but I am not really sure how was I supposed to fill it as it
was my first stx transaction.

They are now asking me a video declaration showing myself logging into the
wallet and sending them the TXID.

They also want a video of a hand written declaration of my details and
releasing them of liabilities.

**Comment by markmhx** [comment]
I believe the separate issue https://github.com/blockstack/stacks-wallet/issues/571 will help in cases like this one in which users aren't clear on how to use memos when sending to exchanges.

I'm glad to hear that OKCoin has provided a path for recovering this transfer despite it taking a bit of work with the declarations. Please let us know if you're unable to clear it up with them that way.

**Comment by kcdenman** [comment]
I’ve seen the same behavior here. Not sure if the process just takes this long or there is an issue? My stacks wallet indicates the transfer out is complete and the stacks explorer correctly had the from and to address, but I still do not see the STX deposit in OKCoin.

should I just wait?

**Comment by kyranjamie** [comment]
@kcdenman If the transaction is successful, but your OKCoin hasn't been credited, you should contact their support team. 
There's little we can do to help with exchange related issues.

**Comment by kcdenman** [comment]
Thanks @kyranjamie - I’ve submitted a ticket with Okcoin and will post anything I learn regarding their processing of the transfer in

**Comment by kcdenman** [comment]
This is odd to me. Okcoin is saying they never received the memo, but I entered the memo into the Stacks Wallet and was able to initiate the transfer.

The memo is on the stacks blockchain so I'm assuming Okcoin somehow messed up the processing of the memo...

The steps being required of me in order to get the STX into my account are quite a lot..

![image](https://user-images.githubusercontent.com/10832542/117679452-4960ac00-b17e-11eb-9454-b16db91f741c.png)

**Comment by kcdenman** [comment]
Update with more information - 

I've submitted all of the above to OKCOIN. I believe this may have been user error (I'll update once the case is closed) but here is the feedback:

The "memo" field in the STX wallet when I initiate the transaction allows me to enter any string I'd like.

The "memo" field in OKCOIN is system generated and immutable. 

Given this was my first STX Wallet to OKCOIN transfer, it was unclear to me that the memo generated by OKCOIN needed to be entered in the memo field in the STX Wallet and it was somehow "matching" to validate the transation.

I think this UX could be more clear in the STX Wallet. I'd recommend the memo field in the transaction screen (attached) say something to the effect of "Ensure the memo you enter matches the memo you enter in the receiving wallet. If these memos do not match, your transaction could experience processing issues".

![image](https://user-images.githubusercontent.com/10832542/117687660-00acf100-b186-11eb-9243-44dcde3bc68f.png)
