### ISSUE TITLE
[4.0.4] Bug: unable to connect Stacks Wallet to Ledger Nano S

### ISSUE THREAD

**Issue by clintonchang** [blockstack/stacks-wallet#633]
Bug found testing Stacks Wallet build undefined, 4.0.4.

**Comment by markmhx** [comment]
Could you describe the problem you're facing in some detail? What error or behavior do you see specifically when trying to connect your Ledger Nano S?

**Comment by eliframe1** [comment]
Hi - I've had the same issue.  I've followed the Ledger instructions on Hiro, updated, toggled on developer mode and downloaded the Stacks app for Ledger Nano S.  The app shows on the Ledger.  When I open the stacks wallet and say "I have a wallet" it asks me to connect, which works fine.  Then it says open Stacks wallet.  When I do that, it says "pending ledger review".  I double click the Ledger and then the wallet shows I've opened the app very briefly, then the checkmark goes away and it goes back to "connect ledger".  My Ledger device still shows "Stacks Ready" on the screen.  I can't get past that part.  Thanks!

**Comment by kyranjamie** [comment]
@eliframe1 Can you try the instructions here, where the Stacks app on the Ledger is open before you proceed?

**Comment by eliframe1** [comment]
> @eliframe1 Can you try the instructions here, where the Stacks app on the Ledger is open before you proceed?
> [#614 (comment)](https://github.com/blockstack/stacks-wallet/issues/614#issuecomment-779342455)

this worked for me (having ledger live closed and opening the stacks wallet on the ledger before clicking "connect ledger" in stacks wallet.  thanks!!
