### ISSUE TITLE
Support until-burn-ht parameter in delegation form

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#639]
As a pool provider, I get a lot of requests how to set the number of cycles. Currently, this is set as indefinite and therefore the delegatee controls the locking period.

Ideally, the user can set the locking period.

**Comment by markmhx** [comment]
I'm not sure whether this sort of behavior is supported on the chain level.

The [`delegate-stx`](https://docs.blockstack.org/references/stacking-contract#delegate-stx) function supports an `until-burn-ht` parameter, which allows the user to specify a burn height upon which delegation ends. But this is different than what you're proposing, which is more of a `maximum-cycles` sort of parameter (which doesn't yet exist).

**Comment by friedger** [comment]
For me the two values are the same

**Comment by markmhx** [comment]
I understand `until-burn-ht: an optional burn height at which this delegation expiration` from the Clarity documentation linked above as meaning the future burn height upon which delegation itself will get revoked automatically.

As such, if the user provides this value during delegation, the delegation service can initiate Stacking for the user for _any_ number of cycles until that height it reached. E.g. the service can initiate Stacking for 12 cycles right before the height is reached, and so while the height is reached – and delegation is revoked – soon afterwards, the user's STX are still locked up for those following ~6 months.

**Comment by friedger** [comment]
The pox contract checks during `delegate-stack-stx` that the `unlock-burn-ht` is before the `until-burn-ht` 
![Screenshot from 2021-02-26 16-43-33](https://user-images.githubusercontent.com/1449049/109321947-061ac080-7852-11eb-9419-cf8001a74c99.png)

Therefore, I think it is possible to just let users enter this value, or have some nice UI that then provides the suitable value.

**Comment by friedger** [comment]
This should be high priority for the next cycle

**Comment by markmhx** [comment]
We can certainly add an input for `until-burn-ht` (and presumably would have to make it a lot more user-friendly than just entering a number). That would allow users to automatically revoke their delegation at a future time basically. 

I'm going to update the title of this issue to reflect the nature of that functionality.

**Comment by friedger** [comment]
The value goes next to the value for #645

**Comment by friedger** [comment]
I would label this even as a bug.

**Comment by digitalronin** [comment]
Taking a step back, and looking at this from a user's POV, as a user I would like to be able to say "stack my STX until I say stop." i.e. stacking continues from one cycle to the next seamlessly, as long as the user does nothing. When the user wants to stop stacking, their STX would be released at the end of the current cycle.

Is there any way this could be achieved?

**Comment by kyranjamie** [comment]
@digitalronin I don't believe the contract allows this. If your delegatee locks up your funds for 12 cycles, while you can revoke anytime, the fund are locked until the end of _all_ cycles.

**Comment by digitalronin** [comment]
I do understand that this isn't possible right now. I just think, if
changes are being considered, it would be good to try and think about what
would benefit users the most, and keep that in mind as a goal.

**Comment by friedger** [comment]
Just for clarification, the `pox-address` parameter in the `delegate-stx` call refers to the address that the delegatee has to use.

Snippet from `delegate-stack-stx` called by delegatee:
![Screenshot from 2021-03-02 17-53-14](https://user-images.githubusercontent.com/1449049/109685915-07b1f480-7b82-11eb-9e13-893f81649acb.png)

**Comment by markmhx** [comment]
@jasperjansz Could you post the finalized Figma designs here so @friedger has clear materials to move forward with the integration?

**Comment by jasperjansz** [comment]
Here you go @friedger : https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=3990%3A0

**Comment by friedger** [comment]
@jasperjansz The wording of stacking and locking period is still not clear:
" Limit the duration the pool can stack your STX for. After this duration, your STX will unlock automatically."

If the pool locks for 1 cycle and the user limited to 3 cycles, the STX are unlocked after 1 cycle.

**Comment by friedger** [comment]
That the duration does not effect the APY.

**Comment by timstackblock** [comment]
This is currently being tested I am waiting on burn height 1940070 to verify the test.
