### ISSUE TITLE
[4.0.4] Bug: <describe issue>

### ISSUE THREAD

**Issue by Neyfan** [blockstack/stacks-wallet#642]
![4WD9u9O38I0](https://user-images.githubusercontent.com/79596468/109038238-93d49f80-76dc-11eb-9551-250c1a95c21e.jpg)
I sent more stx tokens than I have on my balance. The transaction does not go through. What should I do?

Bug found testing Stacks Wallet build undefined, 4.0.4.

**Comment by kyranjamie** [comment]
The transaction should eventually be rejected.

**Comment by Neyfan** [comment]
How long should I wait?

**Comment by Neyfan** [comment]
???

**Comment by Neyfan** [comment]
> The transaction should eventually be rejected.

How long should I wait?

**Comment by kyranjamie** [comment]
Described in https://github.com/blockstack/stacks-wallet/issues/648
