### ISSUE TITLE
The transaction should eventually be rejected.

### ISSUE THREAD

**Issue by Neyfan** [blockstack/stacks-wallet#643]
How long should I wait?

**Comment by markmhx** [comment]
How often have you been waiting for your transaction to confirm? Oftentimes they can very in length substantially.

We're planning to add an FAQ with information about timing here: https://github.com/blockstack/stacks.co/issues/15

cc @GinaAbrams

**Comment by kyranjamie** [comment]
This is an API/blockchiain level complaint. The wallet should simply reflect an accurate presentation of the chain.
