### ISSUE TITLE
Functionality to delegate to multiple delegatees at the same time

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet#644]
Correct me if I'm wrong, but I don't think this is currently possible. 

The use case: 
Because several delegatees will have different terms, for example Friedger's pool pays out in STX, some pay yields in BTC etc. Would be great to see this added and have multiple stacking entries run simultaneously from the same desktop wallet.

**Comment by friedger** [comment]
The PoX protocol does not allow this. There can be only one reward address

**Comment by GinaAbrams** [comment]
Yeah, I wonder if we might want to consider this for those that have enough STX for multiple stacking slots sometime down the line?

**Comment by kyranjamie** [comment]
I'm going to close this out as it isn't possible on the contract level. Let's reopen if this changes.
