### ISSUE TITLE
Display relevant error message when user tries to revoke delegation without sufficient balance

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-wallet#649]
Bug found testing Stacks Wallet build undefined, 4.1.0.

I have delegated STX here:
https://explorer.stacks.co/txid/0xe225a0f01f094ad24619307ca08304106f5d345bbb33d56060ae30941d8cdc99?utm_source=stacks-wallet&chain=mainnet

While trying to revoke delegation using the button/link in the desktop wallet, the process repeatedly fails with:
Unable to verify transaction Failed to call stacking contract
![image](https://user-images.githubusercontent.com/7738/109353529-59304b80-7831-11eb-912c-1ad8cb97abf9.png)

**Comment by kyranjamie** [comment]
Thanks for reporting @dantrevino 

I just tried this and was able to revoke without issue. 

Any other USB device-using software open? 
Sure you're using the same Ledger you delegated with? 

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1618764/109378180-bd561c80-78d0-11eb-8be4-c09039c20814.png)

</details>

**Comment by dantrevino** [comment]
No hardware wallet in use here.

**Comment by markmhx** [comment]
Thanks for the report. We'll investigate ASAP.

**Comment by markmhx** [comment]
Assigning to @timstackblock to recreate

**Comment by timstackblock** [comment]
Thanks for testing this @dantrevino. The transaction above shows 29,000 STX delegated 7 days ago. This bug was created 4 days ago after the latest stacking cycle locked all the tokens in the wallet. The balance at the time of revoking was 0.00 STX So the error message appeared because the contract call failed due to lack of funds.

I think we need to improve the message handling to inform the user they need to add STX to fund the contract call. I think we need to handle this more gracefully but the failure should have happen.

**Comment by markmhx** [comment]
I agree it appears that the enhancement here is adding a better message when the user tries to revoke without sufficient funds.

**Comment by markmhx** [comment]
I see the new message in red, but it still shows the "Revoke delegation" option despite having unlocked STX available, and if I click it, I end up at the same generic error message:

![image](https://user-images.githubusercontent.com/28991/113291428-4eb31700-92f3-11eb-8d36-50dc4afeb3cb.png)

![image](https://user-images.githubusercontent.com/28991/113291349-33480c00-92f3-11eb-9571-320d52e73ee5.png)

Shouldn't we hire the "Revoke delegation" option entirely in this case?

This copy might be a bit clearer as well:

> You don't have enough unlocked STX to cover the transaction fee needed to revoke your delegation. Please deposit a small amount of STX or wait for any locked STX to unlock.

**Comment by markmhx** [comment]
I'm not sure how I got here, but I'm also now seeing double revocation options: 😶

![image](https://user-images.githubusercontent.com/28991/113294033-cdf61a00-92f6-11eb-8a22-cf536adf3b9c.png)

https://explorer.stacks.co/address/ST1SCZCYS2PPRJWCHFHCBATEXSC4N9NTYN9TZBMTQ?utm_source=stacks-wallet&chain=testnet

**Comment by kyranjamie** [comment]
Yep this was a poorly-done merge. Fixed pushed.

**Comment by markmhx** [comment]
Cool, how about the copy and style changes. Are those pushed as well?

**Comment by markmhx** [comment]
This is looking good in my latest build testing:

![image](https://user-images.githubusercontent.com/28991/113551327-ba97c700-95f4-11eb-8baf-de9902bb07fa.png)
