### ISSUE TITLE
Update domain to Hiro.so for linked resources

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#650]
The URL to the "How does Stacking work?" page from the Stacking form screen goes to the blockstack.org domain but should be updated to the hiro.so domain. This should be updated along with any others we may have in the app pointing to blockstack.org.

<img width="397" alt="Screen Shot 2021-02-25 at 13 43 43" src="https://user-images.githubusercontent.com/28991/109294519-9561ad00-782d-11eb-955c-50c65645ee47.png">

**Comment by kyranjamie** [comment]
These were updated with `4.1.1`.

**Comment by markmhx** [comment]
I see this still points to blockstack.org while testing [v4.1.2](https://github.com/blockstack/stacks-wallet/pull/710)

**Comment by kyranjamie** [comment]
Just searched the repo and there are no instances of blockstack urls so closing this one out.
