### ISSUE TITLE
Improve various copy details for Stacking

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#651]
"Small or large sums":

<img width="255" alt="Screen Shot 2021-02-25 at 13 49 03" src="https://user-images.githubusercontent.com/28991/109294398-69462c00-782d-11eb-91ad-bd8c8ab83b8e.png">

"the contract" here seems ambiguous. Maybe "the PoX contract" is better?:

<img width="380" alt="Screen Shot 2021-02-25 at 13 49 12" src="https://user-images.githubusercontent.com/28991/109294401-69dec280-782d-11eb-9635-19ac2916b38f.png">

"A delegation service stacks on your behalf":

<img width="367" alt="Screen Shot 2021-02-25 at 13 48 54" src="https://user-images.githubusercontent.com/28991/109294406-6b0fef80-782d-11eb-8330-3b4351e227b3.png">

"Minimum required to stack _is_ [NUMBER]":

<img width="367" alt="Screen Shot 2021-02-25 at 13 48 48" src="https://user-images.githubusercontent.com/28991/109294407-6b0fef80-782d-11eb-9d38-c9929aee060b.png">

"you'll have the chance to earn":

<img width="517" alt="Screen Shot 2021-02-25 at 13 48 39" src="https://user-images.githubusercontent.com/28991/109294409-6ba88600-782d-11eb-9f6d-d64983aa7442.png">

Capitalize "Stacking" everywhere:

<img width="266" alt="Screen Shot 2021-02-25 at 13 48 33" src="https://user-images.githubusercontent.com/28991/109294483-8aa71800-782d-11eb-8ea3-4b214c855163.png">

<img width="527" alt="Screen Shot 2021-02-25 at 13 48 28" src="https://user-images.githubusercontent.com/28991/109294486-8b3fae80-782d-11eb-9aad-d649b67506bf.png">

"Your STX _will_ never..."

<img width="278" alt="Screen Shot 2021-02-25 at 13 43 34" src="https://user-images.githubusercontent.com/28991/109294487-8c70db80-782d-11eb-800d-d589e9bc34ff.png">

"cannot":

<img width="326" alt="Screen Shot 2021-02-25 at 13 43 25" src="https://user-images.githubusercontent.com/28991/109294489-8c70db80-782d-11eb-976c-6b981a5975df.png">

"Stacks blockchain" (i.e. no need to capitalize "blockchain"):

<img width="525" alt="Screen Shot 2021-02-25 at 13 43 17" src="https://user-images.githubusercontent.com/28991/109294491-8d097200-782d-11eb-8f0d-2e164281e383.png">

**Comment by markmhx** [comment]
Related: https://github.com/blockstack/stacks-wallet/issues/551

**Comment by markmhx** [comment]
Let's also soften the language here to "Have a chance to earn Bitcoin when you lock your STX temporarily"

![image](https://user-images.githubusercontent.com/28991/110635938-f5504000-81ab-11eb-9013-bcf6037aa8e7.png)

**Comment by kyranjamie** [comment]
Done. And agree on softening, but nit on capitalisation. 

When referring to bitcoin as a currency, rather than network, [should use a lowercase b](https://bitcoin.stackexchange.com/a/20902). Same rule as if it were euros or dollars.

**Comment by markmhx** [comment]
@kyranjamie should this move to QA or done?
