### ISSUE TITLE
Ensure accurate dynamic minimum displayed for Stacking

### ISSUE THREAD

**Issue by Shenron2020** [blockstack/stacks-wallet#652]
The Minimum required to stack shows 70,100 STX.  The wallet was updated on cycle 2 and did not update the minimum required STACKS to the current 80,000 STX causing roughly 59 stackers 21% out of the 277 to not be part of Cycle 3 rewards.  In my opinion this is a pretty big issue.  Some Stackers have locked tokens for 2,4,6+ cycles.  How can we fix this so that 1. the wallet can reflect accurate if not a better estimation of minimum stacks needed 2. additional stacks can be added 3. those not meeting minimum can have the option to cancel future locked cycles?

Bug found testing Stacks Wallet build undefined, 4.1.0.

**Comment by Shenron2020** [comment]
https://user-images.githubusercontent.com/40416209/109397558-3ff8cf00-7905-11eb-8ca9-0db1e8e4e30c.mov

**Comment by markmhx** [comment]
It's unclear to @kyranjamie and me why https://stacking.club/ is showing 80k when the API used by the wallet is showing ~70k: https://stacks-node-api.mainnet.stacks.co/v2/pox

@aulneau @hstove Any thoughts here?

**Comment by aulneau** [comment]
> It's unclear to @kyranjamie and me why https://stacking.club/ is showing 80k when the API used by the wallet is showing ~70k: https://stacks-node-api.mainnet.stacks.co/v2/pox
> 
> @aulneau @hstove Any thoughts here?

Once this pr lands, https://github.com/blockstack/stacks-blockchain/pull/2459 the wallet will have a much better ability to predict / display the correct minimum.

**Comment by markmhx** [comment]
We can close this issue once we confirm per https://github.com/blockstack/stacks-blockchain/pull/2459#issuecomment-800194112 that the underlying API property used in the wallet is now getting updated dynamically.

**Comment by markmhx** [comment]
**Update**: We're awaiting deployment of the above node PR to mainnet, at which point the API value will start getting reportedly accurately and dynamically without any further client-side changes. We'll just want to QA the wallet quickly to ensure that it's indeed reporting the latest dynamic minimum value as provided by the API at that time.

**Comment by markmhx** [comment]
This appears to be updating dynamically:

![image](https://user-images.githubusercontent.com/28991/116163142-7e3d1f80-a6f7-11eb-801a-9e09cd29540b.png)

![image](https://user-images.githubusercontent.com/28991/116163150-8301d380-a6f7-11eb-9a52-e9649e5b6bb5.png)
