### ISSUE TITLE
Add guidance to check mnemonic word list upon Secret Key entry error

### ISSUE THREAD

**Issue by minorthreatmikey** [blockstack/stacks-wallet#653]
Hey there,

Was happy to get the opportunity to be part of the (Block)Stacks ICO in 2019. Finally decided to stack what has been released to me so far. Here is what order I did things in:

1. I sent some bitcoin to my STX address so I can move it (BTC miner fee was 33% of the total I sent >.<).
2. Once the btc arrived successfully, I tried to send some STX - it then asked for my 24 word phrase, which I thought was odd since I was already in my wallet.
3. Ended up going online and sure enough, there's a new wallet - I download it from hiro.so/wallet.
4. Dug up my 24 word seed phrase, entered it in the new wallet, and I got "Not a valid bip39 mnemonic" -  I tried entering by column, by row, and even backwards, nothing seems to work.

~~I've tried going to the Discord and despite the link being available, there is nothing on the other end. Just a completely blank channel.~~ I am starting to worry a little bit so I check my STX wallet address on the explorer. I see all my STX still there but I don't see any bitcoin there. What the heck is going on?! Please help :(
-mikey

**Comment by unclemantis** [comment]
Would you mind sharing the TXID?

**Comment by minorthreatmikey** [comment]
> Would you mind sharing the TXID?

c2686cd3959ba67ff092be590df3a50e1f32b5364e64cb0a2417282adfb91de8

This is the result of sending BTC to my original Blockstacks wallet address

**Comment by unclemantis** [comment]
This is a bitcoin TX.

**Comment by minorthreatmikey** [comment]
> This is a bitcoin TX.

Yes, the only transaction I did. The Blockstacks wallet said I needed BTC to send STX so that's what I did. After I did that I downloaded the new wallet. Now I cant get in hence this issue.

**Comment by unclemantis** [comment]
Would you mind sharing your stacks account address?

**Comment by minorthreatmikey** [comment]
> Would you mind sharing your stacks account address?

SP1EFBP7ZVXGJP27X2NX1WGCRDAYP5VSDXXB6NMA6

**Comment by unclemantis** [comment]
Are you on windows? If so...

npm i @stacks/cli

I am on discord.

**Comment by minorthreatmikey** [comment]
Yes I am on windows and I just joined the discord. Not sure what npm means

**Comment by unclemantis** [comment]
Pull me into chat.  I am trying to help you. Thank you.

**Comment by markmhx** [comment]
This sounds related to https://github.com/blockstack/stacks-wallet/issues/584.

Mind trying to type your seed into a text editor then copy/pasting it into the wallet from there? We've heard a report that it somehow resolves this issue, though we still need to investigate.

**Comment by minorthreatmikey** [comment]
kyranjamie on discord helped me out. Turns out, one of the words, although a real word, wasn't a word on the list of valid words for

**Comment by markmhx** [comment]
That's great to hear!

I'm re-opening so we can track the addition of guidance here for checking the word list since it helped in your case and might help others: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by ghostshirt** [comment]
I can confirm this bug for both on Ubuntu and Windows 4.1.0 wallets. I have checked all the words against BIP-0039 English words. I have copied from a plain text file with only single white spaced between them.

**Comment by kyranjamie** [comment]
We now link to the FAQ when there's a BIP-39 error, which can explain this circumstance.
