### ISSUE TITLE
Add guidance for delegation service address in Stacking delegation form

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#654]
It appears [this user](https://forum.stacks.org/t/stacking-delegation-now-supported-by-stacks-wallet/11739/6?u=markmhendrickson) has mistaken the STX receipt address for OKCoin with a delegation address. 

We could clarify the different between such addresses (e.g. as provided by exchanges that also support custodial delegation) and those addresses used for non-custodial delegation.

<img width="639" alt="Screen Shot 2021-03-01 at 10 24 57" src="https://user-images.githubusercontent.com/28991/109477964-f29d6e80-7a78-11eb-905f-224e4f6b464b.png">

**Comment by kyranjamie** [comment]
@markmhx Can we close this one with the latest updates?
