### ISSUE TITLE
Standardize term for "to whom one delegates" for delegation

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#656]
We tend to use "delegation service" and "delegatee" interchangeably in the Stacking delegation form, whereas we should use the former consistently for clarity.

Also "Delegate" in "Confirm and Delegate" doesn't need capitalization. The other section headers capitalize only the line's first letter.

<img width="278" alt="Screen Shot 2021-03-01 at 10 27 14" src="https://user-images.githubusercontent.com/28991/109499627-71080980-7a95-11eb-828e-5082fbaf9040.png">
<img width="181" alt="Screen Shot 2021-03-01 at 10 27 16" src="https://user-images.githubusercontent.com/28991/109499630-71a0a000-7a95-11eb-815d-bb8070198875.png">
<img width="211" alt="Screen Shot 2021-03-01 at 10 27 18" src="https://user-images.githubusercontent.com/28991/109499632-72393680-7a95-11eb-87f5-74934264c9c3.png">
<img width="256" alt="Screen Shot 2021-03-01 at 10 27 24" src="https://user-images.githubusercontent.com/28991/109499634-72d1cd00-7a95-11eb-9059-944f67308d27.png">
<img width="178" alt="Screen Shot 2021-03-01 at 10 27 28" src="https://user-images.githubusercontent.com/28991/109499636-72d1cd00-7a95-11eb-90ab-a2da4e5de1e0.png">
<img width="198" alt="Screen Shot 2021-03-01 at 10 27 30" src="https://user-images.githubusercontent.com/28991/109499637-736a6380-7a95-11eb-819b-e3b6f9af0b06.png">
<img width="155" alt="Screen Shot 2021-03-01 at 10 27 42" src="https://user-images.githubusercontent.com/28991/109499638-736a6380-7a95-11eb-9963-09bbda5f69bd.png">

**Comment by kyranjamie** [comment]
For reference, as there's been some confusion (myself included):

**delegator** _noun_. a person who delegates (e.g. user's of the wallet)
**delegatee** _noun_. someone to which something is delegated (e.g. @friedger)

The word **delegate** is both a noun and verb. IMO we should avoid using the noun in favour of _delegatee_ or _delegation service_. 

We can definitely improve language here, though we can also educate with our language. Along the lines of "Delegation services, also know as delegatee..." somewhere.

**Comment by markmhx** [comment]
On a call yesterday, someone made a good point that we may want to use distinctly different words for the "delegator vs. delegatee" relationship akin to "register vs. sign in" (instead of "sign up vs. sign in", which are easier to confuse at first glance / require more mental overhead when deciding "which one?").

There's also the simple question of what word users are likely to use in the wild, regardless of what we pick here.

I'm voting for "pool" simply because it's very different than "delegator" (which we all seem happy with). E.g. "You can delegate to the pool for a chance to earn BTC with your peers". And despite us not having really used it to date in materials. It's also quite short and sweet.
