### ISSUE TITLE
[4.1.0] Bug: Pending transaction

### ISSUE THREAD

**Issue by creci** [blockstack/stacks-wallet#657]
The pending transaction is over 24 hours old, it's weird and very long.

Transaction ID:
0xd2921a84cb29eff672a9538a9f4764886c58b7ea60c83979ca384f54025b86cb
![изображение](https://user-images.githubusercontent.com/18026330/109521779-56925800-7ab6-11eb-93ab-f39c9710c420.png)

**Comment by markmhx** [comment]
There may be an issue with the nonces here, similar to https://github.com/blockstack/stacks-wallet/issues/648.

**Comment by markmhx** [comment]
@kyranjamie Could you describe the nature of this bug a bit so I can design a test case for it?

**Comment by kyranjamie** [comment]
@markmhx This is the nonce issue, I believe.

Test case is to successfully send multiple transactions in quick succession.
