### ISSUE TITLE
Possible to add errors to older versions of the wallet? 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet#658]
Probably unlikely but throwing it out there anyway: we get a lot of folks inquiring about not being able to send STX on the older versions of the wallet. If we had a simple pop up in the older wallet to download the new one that would help.

**Comment by andresgalante** [comment]
Let me see if I understand this correctly: The older wallet doesn't allow users to send STX but there's no way they'd know that since there is no notification asking them to upgrade, right? How many inquires are "a lot"?

@markmhx if this is a small task, can we put it in the backlog? when can we deprecate old versions?

**Comment by GinaAbrams** [comment]
> Let me see if I understand this correctly: The older wallet doesn't allow users to send STX but there's no way they'd know that since there is no notification asking them to upgrade, right? How many inquires are "a lot"?

Correct! 

>  How many inquires are "a lot"?

This is one of the most commonly asked questions in that a few users seem to ask each day.

**Comment by kyranjamie** [comment]
The problem is that we would first have to update the old wallet, to include an update notification. Unlike a website, we can't update this remotely.

**Comment by markmhx** [comment]
Yep, unless we've missed a creative solution here, it seems there's no way to push any such a change automatically to old v3.x wallet installations. And if we push people through general comms to install a new version of the old v3.x wallet (e.g. with error, popup, etc), we might as well just push people to install the newest v4.x version. So we're in a pickle.

**Comment by markmhx** [comment]
I spoke with @GinaAbrams about this and we agreed that there doesn't appear to be anything concrete we can do here for now that'd make much difference (e.g. create new FAQ) apart from the direct guidance we've been giving to users who report trying to use the old wallet.

**Comment by jeffdomke** [comment]
Can we please add a notice to the /status page explaining this issue.

**Comment by markmhx** [comment]
Yep ✅ :

![image](https://user-images.githubusercontent.com/28991/110133333-7da99c00-7dcc-11eb-83b2-a1042fb3b6f1.png)
