### ISSUE TITLE
2 pending DELEGATING STX transactions appear instead of 1 in the activity section 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#660]
When I delegate one contract call is present in the explorer but the wallet duplicates the pending transaction in the UI

Video of the bug
http://somup.com/crenDlDJzg

<img width="1009" alt="Screen Shot 2021-03-02 at 11 11 16 AM" src="https://user-images.githubusercontent.com/49165468/109678037-390dce80-7b48-11eb-916d-a0338ea5f353.png">

**Comment by kyranjamie** [comment]
Can you test again in `4.1.0` @timstackblock, as mentioned in Discord, this is a debug build

**Comment by timstackblock** [comment]
Not an issue in 4.1.0
