### ISSUE TITLE
[4.1.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by wils26** [blockstack/stacks-wallet#662]
Bug found testing Stacks Wallet build undefined, 4.1.0.

I followed instructions to download Stacks on Ledger. But when I open the wallet, connect Ledger, open Stacks... then nothing happens. It never asks me to confirm address and I can not click on Continue.

**Comment by kyranjamie** [comment]
Hi @wils26, thanks for reporting. 

Are you using Windows? There are know issues connecting, reported in https://github.com/blockstack/stacks-wallet/issues/614, https://github.com/blockstack/stacks-wallet/issues/633, and more

[This PR](https://github.com/blockstack/stacks-wallet/pull/527), containing various fixes, is currently being reviewed & QA'd and should be released shortly.

**Comment by wils26** [comment]
Thank you very much for the response. I was able to fix the issue and can get into the wallet.

________________________________

**Comment by kyranjamie** [comment]
Glad to hear it @wils26, will close out this issue.
