### ISSUE TITLE
Stacks Wallet loop with Ledger 'Continue'

### ISSUE THREAD

**Issue by cuevasm** [blockstack/stacks-wallet#667]
Hey people, been stuck in a loop on a new Windows machine. I have everything setup as far as Ledger goes, works all great on another device. I wanted to access my wallet on a new machine and I got to this screen here after picking continue with Ledger:
![image](https://user-images.githubusercontent.com/6131188/110076106-c879d400-7d38-11eb-9c86-3869261a3ba2.png)

Blue check comes on as soon as I key in my pin. But then, I open the Stacks app on my Ledger as normal, but then the check disappears. 
![image](https://user-images.githubusercontent.com/6131188/110076176-e8a99300-7d38-11eb-9a25-60edeb2e02a1.png)

I can't get past this and have let it sit there for a while, open and closed, reset the devices, etc. Still every time I get to the step where I confirm the Pending Ledger review by double clicking, my blue checks go away never allowing me to get to verifying my address. 

As far as the Ledger, it says 'Stacks Ready' as I would expect. 

Couldn't find an issue that described an issue like this, apologies if I missed one. Thanks!

**Comment by kyranjamie** [comment]
Thanks for reporting @cuevasm. Known issue unfortunately.

We have a PR in QA you could try out that fixes this (and would be extremely helpful testing 🙏🏼) https://github.com/blockstack/stacks-wallet/pull/527

**Comment by seagulljim** [comment]
@kyranjamie I had the exact same issue, and this PR seems to have resolved it.  Thanks!

**Comment by markmhx** [comment]
I'm closing this out since it appears filed as an issue elsewhere and has a fix in the linked PR.
