### ISSUE TITLE
Combine status and help indicators with new FAQ link

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#676]
We can probably just display the footer indicator instead of the in-line one on the homepage as well. And we should add a link to the FAQs.

E.g.:

> Got a question? [Read FAQs](https://www.hiro.so/wallet#faq) then [ask on Discord](http://stacks.chat/). Having difficulties? [Check status](stacks.co/status#wallets) then [file a bug](https://github.com/blockstack/stacks-wallet/issues/new?title=%5B4.1.0%5D+Bug%3A+%3Cdescribe+issue%3E&labels=bug%2Creported-from-ui%2C4.x%2Cmainnet&body=%0A%3C%21--%0A%0A++Thanks+for+creating+an+issue.+Please+include+as+much+detail+as+possible%2C%0A++including+screenshots%2C+operating+system%2C+and+steps+to+recreate+the+problem.%0A%0A++If+you+have+any+questions%2C+ask+%40kyranjamie+on+Github%2C+Discord+and+Twitter.%0A%0A--%3E%0A%0ABug+found+testing+Stacks+Wallet+build+undefined%2C+4.1.0.%0A%0A). [v4.1.0]

![image](https://user-images.githubusercontent.com/28991/110484371-e05fa800-80ea-11eb-84e6-d05a87a763f2.png)

**Comment by kyranjamie** [comment]
I'm also eager to kill this box, but I'm hesitant to put all this information in the version/bug info box. It'll make it really wide, and require some sort of collapse handling that won't look good.

Perhaps we make a dismissible social box or something, that prompts users to join our community.

**Comment by andresgalante** [comment]
Why don't we put this one in the design cue? 

cc @jasperjansz
