### ISSUE TITLE
Stacking Copy Suggestion 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet#682]
Translating from this [forum comment](https://forum.stacks.org/t/hiro-s-feedback-on-stacking/11680/11?u=gina)/ 

**Clear disclosure.** The Hiro wallet and other stacking wallets should make very clear that the number of cycles you choose to stack for matters, because you have to take one cycle off before re-stacking. This was not at all clear when I first stacked on the Hiro wallet. Clear disclosure also eliminates the need to fork the protocol to make changes here. 

I think adding this to the wallet stacking experience can help.

**Comment by markmhx** [comment]
I think we have this covered by https://github.com/blockstack/stacks-wallet/issues/640 though it's good to hear corroboration.
