### ISSUE TITLE
Delegation with Hiro wallet using Ledger frozen on "Pending Ledger review"

### ISSUE THREAD

**Issue by ar8901** [blockstack/stacks-wallet#683]
I attempted a delegation today, and followed the instructions. After opening the Stacks app and confirming the transaction, the Hiro wallet did not go from the second step to the third step, and the Ledger simply says "Pending Ledger review." I can get out of the pending screen on the Ledger with a double-press, but I can't process the transaction or use the wallet for other STX transactions. The Stacks explorer shows no record of a transaction.  Will this eventually free up or will the Ledger be frozen in a doom loop?

**Comment by kyranjamie** [comment]
@ar8901 Some tips:

- Make sure your Ledger App is up to date on Ledger Live (freezing NanoX was a known issue on older version)
- Open Stacks Ledger app before Connect Ledger screen in the Stacks Wallet
- Wait for tomorrow (hopefully) when we'll release https://github.com/blockstack/stacks-wallet/pull/527 with fixes

**Comment by ar8901** [comment]
Thanks. It's up to date according to Ledger Live (yes it's a NanoX).  Will try again tomorrow.

**Comment by ar8901** [comment]
I was able to create a workaround by restoring the Ledger wallet directly onto Hiro using the seed phrase. Delegation from the Hiro app worked fine.

**Comment by markmhx** [comment]
What appears immediately on your Ledger device exactly having double-pressed the "Pending Ledger review" message?

**Comment by ar8901** [comment]
After I double-press the "Pending Ledger review" message, the message is "Stacks Ready."

**Comment by markmhx** [comment]
Thanks for the additional information. I'm not sure how to explain this behavior without trying it over a video call with you. Mind booking a time here to do so? https://calendly.com/markmhendrickson/meeting

**Comment by kyranjamie** [comment]
@ar8901 please try again with the[ 4.1.1 release. ](https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.1)

**Comment by ar8901** [comment]
Ok. So I downloaded 4.1.1, reset the wallet and rebuilt from Ledger, and that worked (i.e., Hiro recognized the Ledger and is pulling up the keys). However, whenever I go into the Stacks app on Ledger, it still starts with "pending ledger review" which I then have to double-press to get out of. I also don't know if this will work the next time I try to do a transaction on the Ledger via Hiro (I haven't attempted that).

**Comment by markmhx** [comment]
Having to double press "Pending Ledger review" is expected at this time, though we hope to remove it once Ledger has the chance to review the Stacks app internally.

Please do let us know if the transaction doesn't work with Ledger when you do attempt it and we'l reopen this issue as needed then. I'm glad v4.1.1 has helped unblock you.

**Comment by ar8901** [comment]
Understood. Thanks guys -- looking forward to continuing to invest in this project.
