### ISSUE TITLE
[4.1.0] Bug: Unable to revoke delegation (macOS, Ledger Nano X)

### ISSUE THREAD

**Issue by liujoshua** [blockstack/stacks-wallet#685]
I delegated some STX for cycle 3 and wanted to revoke delegation now that it has ended. I was unable to on Stacks Wallet 4.1.0, macOS, with Ledger Nano X

<img width="485" alt="Screen Shot 2021-03-12 at 9 09 22 PM" src="https://user-images.githubusercontent.com/7097368/111019933-3a749d80-8377-11eb-9b4a-6deccd9251e8.png">

Fee: 165 uSTX
Contract/Function: https://explorer.stacks.co/txid/0x18c6182e18d3e8873dcedb65359972a2fcd46b198f34d81072d28946c69f4d76?chain=mainnet

**Comment by markmhx** [comment]
Do you have a balance with at least 165 microSTX to cover the fee? If not, you may be experiencing the same issue as reported with https://github.com/blockstack/stacks-wallet/issues/649 in which we need to display a more informative error message for those with insufficient balances.

**Comment by liujoshua** [comment]
Does not appear to be a wallet issue, although error messages might help.

It looks like the pool I delegated to did not lock my funds for cycle #3 and locked it for cycle #4.

**Comment by markmhx** [comment]
To be clear about what happened here:

1. You delegated ahead of cycle 3
2. The pool locked your STX for cycle 4
3. You attempted to revoke delegation
4. You saw the error message above

Is that correct?

**Comment by liujoshua** [comment]
Correct. I delegated close to the deadline and pool operator probably committed before I delegated. 

To your earlier point about fees, I delegated more than my balance so I did not have sufficient _unlocked_ funds to cover the fee.

**Comment by markmhx** [comment]
Ah okay, that makes sense then regarding the fee issue. You should be able to revoke even when a certain number of your STX have been committed, but you'll need some unlocked STX to do so.
