### ISSUE TITLE
[4.1.0] Bug: Stacking Completed, Never Received BTC

### ISSUE THREAD

**Issue by pandaring2you** [blockstack/stacks-wallet#687]
Transaction shows stacking was completed, but explorer shows no BTC was sent to the address: 
Stacking: https://explorer.stacks.co/txid/0xba2be03ba9121df13d255bb205518dadab6e915609599800b7ceca479deb8587?utm_source=stacks-wallet&chain=mainnet 

Address: https://www.blockchain.com/btc/address/1BskLPC8rPdKk5TKfmMvnC8aVNg5bPwT2F

Bug found testing Stacks Wallet build undefined, 4.1.0.

**Comment by psq** [comment]
the protocol does not guarantee stacks miners will send commits for all btc blocks.  for example, there were 5 empty blocks in the past 100 btc blocks, which means that for each of these blocks, the 2 stackers that would have been picked will not receive reward for this cycle.

**Comment by kyranjamie** [comment]
Thanks for the explanation @psq 

I'm going to close out this issue as this is a contract-level behaviour. We're looking to ways we can better communicate reward slots in the wallet UI
