### ISSUE TITLE
Link to hiro.so/wallet/install-desktop from "Update Available" message

### ISSUE THREAD

**Issue by jamesberg** [blockstack/stacks-wallet#688]
I see there is an upgrade available.  i signed into Github and clicked on the upgrade version, but no download option appeared.  How do I upgrade?  STX wallet took me to Github.

**Comment by andresgalante** [comment]
Hi @jamesberg Try downloading it from here https://www.hiro.so/wallet/install-desktop

@markmhx @kyranjamie What if the link to download from the wallet points to https://www.hiro.so/wallet/install-desktop instead of the Github page?

**Comment by kyranjamie** [comment]
Yes we should do this to avoid confusion over which file should be downloaded.

**Comment by jamesberg** [comment]
Thank you.  Successful
