### ISSUE TITLE
Mac OSBigSur 11.1 - Apple won't allow this wallet to install/open

### ISSUE THREAD

**Issue by an5on** [blockstack/stacks-wallet#689]
...Can't be opened because Apple cannot check it for malicious software

"This software needs to be updated. Contact the developer for more information."

Any advice?

**Comment by kyranjamie** [comment]
Which version are you using? This should not happen with `4.1.0`

**Comment by an5on** [comment]
3.1.1 - to retrieve unspent btc from the previous wallet as per the instructions on: https://www.hiro.so/wallet 

![hiro](https://user-images.githubusercontent.com/33924698/111072763-eb904a80-84d3-11eb-8cf6-61af83220510.jpg)

**Comment by aulneau** [comment]
> ...Can't be opened because Apple cannot check it for malicious software
> 
> "This software needs to be updated. Contact the developer for more information."
> 
> Any advice?

If you need to, you can right click the app and select "Open". I believe that bypasses the check.

**Comment by an5on** [comment]
Ah, rookie error! Thanks aulneau :)
