### ISSUE TITLE
Add indicator that until-burn-ht has been passed for Stacking delegation

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#691]
@kyranjamie 

I think there is an issue with the burn height PR.

I delegated in the image below and set the burn height to 1 cycle it should have revoked automatically at block 1940070, but it did not as you can see from the image below it is still delegated and I will have to revoke manually. 

Here is the delegation contract call
https://explorer.stacks.co/txid/0x3318a26a5b50c5410382574a691bb0fe395bf311c1cfc2ea25f20ecbbf42aea6?utm_source=stacks-wallet&chain=testnet

<img width="1017" alt="Screen Shot 2021-03-12 at 10 11 44 AM" src="https://user-images.githubusercontent.com/49165468/111171080-f9e57180-857a-11eb-899e-7a7dcd86e352.png">

<img width="1011" alt="Screen Shot 2021-03-13 at 8 53 07 AM" src="https://user-images.githubusercontent.com/49165468/111171100-0073e900-857b-11eb-90bf-23bc5ff53d8a.png">

**Comment by kyranjamie** [comment]
Hey @timstackblock thanks for reporting. 

I think we're good here though. The block height arg doesn't automatically revoke you. What it prevents is a pool from beginning stacking beyond that point.

**Comment by timstackblock** [comment]
I changed this to an enhancement, to add visual information reminding user of burn height entry so they are not conused.
