### ISSUE TITLE
Delegation status query doesn't respect selected node

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#696]
There's an issue where requests to the API are made to **both** the previously selected node, and the current one. 

This is likely an issue with `useSWR`, or the application of it.

**Comment by markmhx** [comment]
@kyranjamie Is there an alternative testnet node available I could use here for testing by chance or should I set up mocknet? And what API calls in particular can I confirm are made to only the newly configured node in comparison to previous builds?

**Comment by kyranjamie** [comment]
@markmhx  Yes, I think you can try using `https://stacks-node-api.xenon.blockstack.org/`
