### ISSUE TITLE
Allow confirm and send by enter key

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#697]
When confirming a transaction in the modal dialog "Confirm and send" it is not possible to continue by pressing the enter key.

After entering the password and pressing the enter key the transaction should be processed. Or is this on purpose? If yes, then the user should get a hint that the enter key does not work.

**Comment by kyranjamie** [comment]
Hey @friedger—thanks for making issue.

This is on our radar, @markmhx logged in https://github.com/blockstack/stacks-wallet/issues/334, so will close this one out. We have some refactoring work queued up, within which this will also be addressed!
