### ISSUE TITLE
[4.1.1] Bug: Errors while upgrading from 4.1.0 to 4.1.1

### ISSUE THREAD

**Issue by thambisrinath** [blockstack/stacks-wallet#701]
Hi,
I had Stack Wallet version 4.1.0. Tried to update to 4.1.1 and got the below errors. Although my wallet version now shows as 4.1.1, I am afraid what caused this issue and if my wallet is bug free?

![image](https://user-images.githubusercontent.com/81196574/112067866-2b43db80-8b3f-11eb-9b14-3fd272c9240c.png)

![image](https://user-images.githubusercontent.com/81196574/112067879-31d25300-8b3f-11eb-85b6-dbd09db9f1cd.png)

**Comment by kyranjamie** [comment]
Hi @thambisrinath, thanks for logging an issue.

I'm not familiar with what might have caused this but I'd suggest the following:

- Restart your computer
- Ensure the previous version of the Stacks Wallet is closed before running the upgrade

Failing that, ensuring you have a backup of your Secret Key, uninstall the current version of the wallet, then running `stacks-wallet.mainnet.v4.1.1.exe`.

**Comment by kyranjamie** [comment]
@thambisrinath Let us know if these instructions help. It could be an issue with Windows, rather than the Stacks Wallet itself. 

If this issue persists, please reopen this issue.

**Comment by thambisrinath** [comment]
Hi, Thanks for the follow up. I don't have any issues with the Wallet as
such. Hopefully it's just to do with Windows.

Thanks,
Sreenath
