### ISSUE TITLE
Potential Stacking Issue

### ISSUE THREAD

**Issue by davidtiezzi** [blockstack/stacks-wallet#707]
Bug found testing Stacks Wallet build undefined, 4.1.1.

**Comment by kyranjamie** [comment]
@davidtiezzi can you elaborate on the issue?

**Comment by davidtiezzi** [comment]
Yes, a couple of issues:
- I locked the original 75K when the minimum was 70K, and since the new minimum is 90K STX does this mean I will not be eligible for rewards this cycle?
- Given the above, if I do indeed need 90K, then there either needs to be a way to lock more STX to get to the 90K prior to the cycle starting (in my example 15K) or I should not be able to lock the 75K STX in the first place.
- for example, If I where to try and lock 15K for cycle 5 (which currently has 70 minimum) the wallet would not let me do this.

Make sense?


On Mar 24, 2021, at 8:35 AM, kyranjamie ***@***.******@***.***>> wrote:



@davidtiezzi<https://github.com/davidtiezzi> can you elaborate on the issue?

**Comment by markmhx** [comment]
The minimum is dynamic in that it changes automatically based on participation in each cycle. As such, if a user locks just the currently displayed minimum, there is always a chance that the minimum will rise before a future cycle and make them ineligible for rewards. It's generally less risky to lock additional STX above the currently displayed minimum to guard against this.

If you do find yourself in the situation of having locked less than the new / current minimum as it's increased, you can follow these instructions that describe how to set up a second address and "top up" your locking commitment using it to become eligible again:

https://www.hiro.so/questions/how-can-i-lock-additional-stx-for-stacking

**Comment by davidtiezzi** [comment]
Thank you Mark, I appreciate the response.  One last question: Is there a “window of time” between when my current locked stacks are unlocked from Cycle #4, enabling them to be locked again prior to the start of next the cycle (cycle #5)?

F

On Mar 25, 2021, at 4:56 AM, Mark Hendrickson ***@***.******@***.***>> wrote:



The minimum is dynamic in that it changes automatically based on participation in each cycle. As such, if a user locks just the currently displayed minimum, there is always a chance that the minimum will rise before a future cycle and make them ineligible for rewards. It's generally less risky to lock additional STX above the currently displayed minimum to guard against this.

If you do find yourself in the situation of having locked less than the new / current minimum as it's increased, you can follow these instructions that describe how to set up a second address and "top up" your locking commitment using it to become eligible again:

https://www.hiro.so/questions/how-can-i-lock-additional-stx-for-stacking

**Comment by markmhx** [comment]
There isn't a window of time unfortunately. If the STX unlock at the end of cycle #4, they can be re-locked but only for #6 onwards with #5 skipped essentially. We're currently looking to make this clearer in the UX with https://github.com/blockstack/stacks-wallet/issues/640.

**Comment by davidtiezzi** [comment]
Thank you Mark, truly appreciate your assistance.

On Mar 26, 2021, at 4:39 AM, Mark Hendrickson ***@***.******@***.***>> wrote:



There isn't a window of time unfortunately. If the STX unlock at the end of cycle #4<https://github.com/blockstack/stacks-wallet/issues/4>, they can be re-locked but only for #6<https://github.com/blockstack/stacks-wallet/issues/6> onwards with #5<https://github.com/blockstack/stacks-wallet/issues/5> skipped essentially. We're currently looking to make this clearer in the UX with #640<https://github.com/blockstack/stacks-wallet/issues/640>.
