### ISSUE TITLE
[4.1.1] Bug: i have receive my stx in my blockchain acc but when i connect it to your app it doesnt have my balance,

### ISSUE THREAD

**Issue by mylifetime02** [blockstack/stacks-wallet#709]
Bug found testing Stacks Wallet build undefined, 4.1.1.

**Comment by kyranjamie** [comment]
Would you mind sharing your STX address for me debug this issue, @mylifetime02 ?

**Comment by mylifetime02** [comment]
SP3RW5AD0JS5V3R3FPVET8QZ4FDNJNAEW2ZDSQQNH

**Comment by mylifetime02** [comment]
This is my blockchain acc. My friends acc are like this too and they have
their stx. But only me dont have

**Comment by kyranjamie** [comment]
Can you elaborate what you mean by your blockchain account? [Look in our blockchain explorer, it appears as this account as no funds.](https://explorer.stacks.co/address/SP3RW5AD0JS5V3R3FPVET8QZ4FDNJNAEW2ZDSQQNH?chain=mainnet)

Originally get your STX?

**Comment by mylifetime02** [comment]
Because its airdrop in blockchain app. Then when we connect it to stack
wallet we get our stx. They get their stx but only me didnt

**Comment by kyranjamie** [comment]
When you say blockchain app, do you mean https://www.blockchain.com? How do they know your address did you give to them?

**Comment by mylifetime02** [comment]
Because its their airdrop program.

**Comment by kyranjamie** [comment]
I understand. This is an issue you must chase up with Blockchain.com. Try contacting their support.

As this is not an error with the Stacks Wallet, I'm going to close this issue.
