### ISSUE TITLE
I forgot my password and I can't restore my password

### ISSUE THREAD

**Issue by nomedik11** [blockstack/stacks-wallet#711]
I forgot my password and I can't restore my password because when registering via blockchain I was not offered 24 words to save them although I am in the account but I can't do anything

**Comment by nomedik11** [comment]
I know most of the password but I don't remember how it ends

**Comment by markmhx** [comment]
Do you have a Ledger or Trezor device that you used to set up the Stacks Wallet originally by chance?

**Comment by nomedik11** [comment]
That was the problem with the distribution of stx from the blockchain and to get them it was necessary to download this wallet and enter 12 words from the blockchain and come up with a password, but at the same time I was not given any 24 words from where to get them, I already downloaded the latest version of the wallet from When I start, my wallet opens and stx I can’t translate because I don’t remember the password except for those 12 words from the blockchain and an authorized account, I don’t have anything

Either it's a bug that they didn't show the words or they shouldn't have shown Ledger or Trezor no used

**Comment by nomedik11** [comment]
When registering a wallet, I just clicked on the bottom field, entered 12 words from the blockchain, came up with a password and was immediately thrown into the wallet where I could use stx, and now when I do not remember exactly the password and I cannot translate or recover since I was not given 24 words to preserve them

**Comment by aulneau** [comment]
if you have the 12 words, you should be able to use those to access your wallet. Are you using the latest version found here? https://www.hiro.so/wallet

**Comment by nomedik11** [comment]
Yes, the latest version from this site, but the problem is that I am already authorized in the account and these 12 words with the blockchain and they were needed only in order to come up with a password, as I understand it, but the fact that 24 words are requested to recover the password is quite other words that I have never seen

**Comment by aulneau** [comment]
> but the fact that 24 words are requested to recover the password is quite other words that I have never seen

I am trying to understand what you mean but I am having a hard time following. 

Seed phrases can be 12 or 24 words. If you have a 12 word phrase, that is a seed phrase, and as such is a wallet. 

You cannot get a 24 word seed phrase from a 12 word phrase. Those would be 2 different wallets.

If you can provide anymore information or very specific information, that would be helpful.

**Comment by aulneau** [comment]
Unfortunately, if you do not have access to a 12 or 24 word seed phrase, and do not remember your password, there is **no way whatsoever** to restore your wallet.

**Comment by nomedik11** [comment]
So I remember these 12 words that I entered, how can I recover the password, because the program asks for 24 words and not 12

**Comment by aulneau** [comment]
I think you're using an older version of the wallet. Please download https://www.hiro.so/wallet (v4.1.1). It can accept both 12 and 24 word seed phrases. If you see an application that has 24 boxes for words, that is v3 of the wallet and is no longer the correct wallet to use.

**Comment by markmhx** [comment]
@nomedik11 Are you referring to a 12-word key given to you by Blockchain.com for the Blockchain.com Wallet by chance?

https://support.blockchain.com/hc/en-us/articles/360000951966-Public-and-private-keys
