### ISSUE TITLE
Support faucet requests with mocknet node

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#716]
This may require a relevant issue in the Stacks Blockchain API repo to resolve, but I'm getting this error when trying to use the faucet with mocknet configured [per the local development documentation](https://docs.blockstack.org/understand-stacks/local-development#accessing-the-services):

Request to http://127.0.0.1:3999/extended/v1/faucets/stx?address=ST1SCZCYS2PPRJWCHFHCBATEXSC4N9NTYN9TZBMT

Response:

> {"error":"Error: Response 400: Bad Request fetching http://mocknet_stacks-node-follower.mocknet:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000000\",\"expected\":\"0x0000000000000000000000001dcd65b4\"},\"txid\":\"748c71e46579b896cebade3dd8a32397c6c5005c9a8449552dd330b31855c679\"}","stack":"Error: Response 400: Bad Request fetching http://mocknet_stacks-node-follower.mocknet:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000000\",\"expected\":\"0x0000000000000000000000001dcd65b4\"},\"txid\":\"748c71e46579b896cebade3dd8a32397c6c5005c9a8449552dd330b31855c679\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:186:37\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)","errorTag":"5768d557-7a77-437e-8337-7240f926615b"}

![image](https://user-images.githubusercontent.com/28991/112645435-c04c1a80-8e46-11eb-8e05-b28468dab743.png)

**Comment by markmhx** [comment]
@zone117x @kyranjamie do I need to somehow generate or deposit funds for the faucet on mocknet here?

**Comment by philipdesmedt** [comment]
@markmhx you can add funds to addresses in the .toml files on mocknet (see files in step 2, very high level: https://github.com/philipdesmedt/arkadiko-dao/blob/master/docs/setup.md, you can modify both the ones with and without .template postfix)

**Comment by kyranjamie** [comment]
Did you change the chain id in the default `.env` file @markmhx? You might've been pointing to mainnet. See https://github.com/blockstack/stacks-blockchain-api/pull/530

**Comment by markmhx** [comment]
I hadn't touched the env files. This is how it appears currently: 

![image](https://user-images.githubusercontent.com/28991/113137260-9b7bec80-9224-11eb-969f-a065e0701222.png)

I'll try changing the value and restarting.

**Comment by markmhx** [comment]
I'm getting the same error having changed this env variable and restarted all docker containers.

**Comment by markmhx** [comment]
@agraebe interested in taking this as a possible fix to the "Local development" documentation and referenced `stacks-local-dev` repository?

I tried debugging this live with @kyranjamie yesterday but he (and others on the UserX team) seem to rely on direct installations of the `stacks-blockchain-api` repo instead of this local development documentation. So it's not altogether clear to me who's relying it these days aside from me and whether anyone else has reported problems?

**Comment by agraebe** [comment]
I think we should update our docs but I'd rely on @wileyj or @CharlieC3 for that :)
