### ISSUE TITLE
BTC Address

### ISSUE THREAD

**Issue by iamgenchi** [blockstack/stacks-wallet#720]
Hi Blockstack Team,

The old Stacks wallet [gave us](https://blog.blockstack.org/transferring-stacks-to-binance-account/) the associated BTC address, not anymore.

How can we obtain the BTC address associated with a STX address?

Regards

**Comment by kyranjamie** [comment]
With Stacks 2.0, BTC is no longer needed to cover transaction fees, so this feature is not built into the new wallet.

If you had BTC left in your previous wallet, you can [follow the instructions on our FAQ page to retrieve it.](https://www.hiro.so/questions/how-can-i-withdraw-the-btc-ive-deposited-into-the-stacks-wallet)

**Comment by markmhx** [comment]
Note that those instructions above can be used to simply obtain the BTC address associated with a STX address as well as withdraw that BTC to elsewhere.
