### ISSUE TITLE
[4.1.1] Hata: <sorunu açıkla

### ISSUE THREAD

**Issue by srknsgr** [blockstack/stacks-wallet#721]
Bug found testing Stacks Wallet build undefined, 4.1.1.
![Adsız](https://user-images.githubusercontent.com/81470444/112719926-96f5c200-8f0c-11eb-9d43-f0f49fc78df3.jpg)

Hello,

The STXs I want to send to my binance account on 26.03.2021 have not yet arrived as of today. Can you help with this?

Best regards

**Comment by kyranjamie** [comment]
@srknsgr it looks like you attempted to send your entire balance 3 times. This is possible in `4.1.1`, in the forthcoming `4.1.2` we're prohibiting it. The latter two should eventually be rejected by the chain.

**Comment by srknsgr** [comment]
Hello, I'm sorry I didn't understand, so I tried it over and over again when the coin was not gone.  will the problem be fixed?  When does the transfer process take place, can I get information?  thank you

**Comment by markmhx** [comment]
@srknsgr Would you mind providing another screenshot of your wallet home screen as it appears today so we can confirm whether any of these pending transactions have settled? And do you mind providing your address as found when clicking the "Receive" button so we can diagnose further as needed?

Feel free to email it to me at mark@hiro.so if you prefer not to post it here.

**Comment by srknsgr** [comment]
it has been 4 days today and the stx transfer I have still done has not taken place. Does Hiro Wallet have someone to help me with this?

**Comment by markmhx** [comment]
I've received your message via email and will follow up there.

**Comment by srknsgr** [comment]
@markmhx 

Thank you for your interest. I'm impatiently waiting for your reply.

**Comment by markmhx** [comment]
I've just followed up by email with some instructions. This appears likely related to https://github.com/blockstack/stacks-wallet/issues/591, which will be fixed in the next release, given that the first attempted and still pending transaction here contains a value greater than the available balance.

**Comment by srknsgr** [comment]
Dear @markmhx 

As you mentioned, I waited until the STX transfer image disappeared from the screen and manually entered the transfer amount (108 STX). However, the result is negative again. The transfer process I want to make is not yet complete.

Can you help me with this?

Best regards
