### ISSUE TITLE
Handle JavaScript error when Ledger updated while connected

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-wallet#723]
This seems to happen when the wallet app is open and a user updates something on their ledger.

![stacks-wallet-errot](https://user-images.githubusercontent.com/11803153/112725123-9d704380-8ee4-11eb-8f3c-ab489cc9c43a.png)

**Comment by aulneau** [comment]
More specifically:

- user opens stacks wallet
- user does NOT sign in
- user opens ledger live
- updates stx app
- closes ledger live
- comes back to stacks app
- tries to auth
- this error happens

**Comment by kyranjamie** [comment]
Addressed in #723. 

I believe issue here was that methods were being called oh `webContent` after it had been destroyed (closing with red circle on macOS).

**Comment by andresgalante** [comment]
closed by https://github.com/blockstack/stacks-wallet/pull/718
