### ISSUE TITLE
Visual for link to stacking guide and blog post image for guide

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#728]
As part of the stacking improvements, we're including a link to a guide that will help people make better decisions. You can read the latest draft here: https://paper.dropbox.com/doc/Stacking-Guide-101--BH7TPz1zJFDxAY1y48hgNn~5Ag-eZvIrGnZZjIIAqSkxVPnj#:uid=988179324040594280229556&h2=V2.

Below the summary card (https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-%F0%9F%92%BF-desktop?node-id=4956%3A3723), there's a link to this guide. We can add a little spot illustration there. Here's the full page for context: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-%F0%9F%92%BF-desktop?node-id=4998%3A34141.

This guide will be posted on the blog (https://blog.stacks.co/), so we'll need a preview image as well.

**Comment by eugeniadigon** [comment]
Icon added to figma https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=4998%3A34141

And here's the blog image
![HiroBlog-StackingGuide101-low](https://user-images.githubusercontent.com/78865845/114150632-8f76e580-991c-11eb-8012-05d30bd0a07a.png)

**Comment by andresgalante** [comment]
Euge sos una zarpada!

**Comment by markmhx** [comment]
@GinaAbrams Want to add the above image to the published guide? https://blog.stacks.co/stacking-strategy
