### ISSUE TITLE
Add software-only wallet support

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#73]
We've heard anecdotal demand for using the wallet to send and receive STX without a hardware wallet available. This issue would entail adding that ability, possibly with the use of a seed phrase for authentication.

**Comment by markmhx** [comment]
@yknl @kantai could I get your thoughts here on what this might take technically to accomplish? I realize we'll probably want to argue the security merits of doing this.

**Comment by yknl** [comment]
To do that we're going to be storing private keys locally and we'll need to add a password to encrypt it like we do in the browser. I think security-wise if it should be fine for a small amount of Stacks, I wouldn't recommend it if you have large holdings though.

**Comment by markmhx** [comment]
General consensus from our team call last week was that doing a software-only wallet would be a bad idea, mainly for security reasons

**Comment by moxiegirl** [comment]
@markmhx so, we should close this as *wont-fix* right?

**Comment by markmhx** [comment]
It seems I spoke too quickly since interest in this has reemerged in Slack within the past 24 hours 🙃.

I'm moving this to the backlog so we can consider it actively.

**Comment by yknl** [comment]
This is complete!
