### ISSUE TITLE
Improve pending Stacking delegation revocation state

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#735]
Right now we still show the revocation status on the right with warning message and a modified (and disabled) "Currently revoking STX" option while showing the pending transaction for revocation:

![image](https://user-images.githubusercontent.com/28991/113550958-35141700-95f4-11eb-8f32-35327846cea7.png)

It seems like we can clean up this experience generally to reduce possible confusion (e.g. we're still instructing the user to revoke even though they already have, and the modified button still shows a pointer cursor on hover / is redundant with the activity item).

**Comment by kyranjamie** [comment]
Updated in 4.3
