### ISSUE TITLE
Resolved - old version

### ISSUE THREAD

**Issue by blax1** [blockstack/stacks-wallet#740]
Resolved - old version

**Comment by kyranjamie** [comment]
@blax1 You're using a pre-mainnet beta release of the Stacks Wallet. 

[Download `4.1.2` here](https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.2)

If I'm not mistaken, the previous version of the wallet displayed funds you have that aren't unlocked.

**Comment by kyranjamie** [comment]
Ninja closed. Thankds
