### ISSUE TITLE
Allow multiple addresses in the same wallet without the need to reset it for each

### ISSUE THREAD

**Issue by shaimo** [blockstack/stacks-wallet#742]
Eg usecase:
Imported old wallet with STX in it. Now I want to send it to my Ledger. Alas I can't connect my Ledger and eg get its address without first resetting the wallet, adding the wallet, getting the address, then resetting it again, adding back the old wallet from the seed, etc, etc. Very frustrating...

**Comment by kyranjamie** [comment]
Thanks for reporting. This is a known issue, tracked here https://github.com/blockstack/stacks-wallet/issues/402

A workaround for the time being is to manually switch the `config.json` in the Stacks Wallet application data folder. Not ideal, but simpler than resetting everytime.

Will close this issue as it's already tracked.
