### ISSUE TITLE
Send max and contract call adjustments 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet#743]
There might be an error where folks are revoking a delegation or doing a contract call of some kind and then trying to send STX, but when clicking "send max" the "max" may not take into account the previous small contract call amounts.

**Comment by markmhx** [comment]
I believe we fixed this in v4.1.2 (the latest release) with https://github.com/blockstack/stacks-wallet/issues/591, though @kyranjamie can confirm.

Do you know if this was reported with this version or an earlier one?

**Comment by kyranjamie** [comment]
Have many people reported this @GinaAbrams, and is it only with contract calls? Links to Discord/TG chats?

Improvements were indeed made in `4.1.2`. Quite possible there are further edge cases though.

Currently we filter the mempool using `?sender_address=SP...` and calculating the spend & fee of all transactions listed there.

**Comment by GinaAbrams** [comment]
> Do you know if this was reported with this version or an earlier one?

Not sure. 

> Have many people reported this @GinaAbrams, and is it only with contract calls? Links to Discord/TG chats?

This was via Front, and there have been a couple, can forward if you'd like. 

> Currently we filter the mempool using ?sender_address=SP... and calculating the spend & fee of all transactions listed there.

Thanks, this makes sense. If we think the issue was fixed then we can close for now and I can reopen if I continue to get similar reports.
