### ISSUE TITLE
Pending withdrawal problem

### ISSUE THREAD

**Issue by Orion5455** [blockstack/stacks-wallet#746]
I tried to withdraw STX from my desktop wallet(to Binance). The first transaction was revoked, while the second was has been pending for 16 hours.

**Comment by kyranjamie** [comment]
Can you share your address so we can investigate?

**Comment by Orion5455** [comment]
Here is it: 
SP319ND5PGEW1T4YYJ5SHWKHBFD3VP1NJ2XQJMCRP
Thx for the response.

**Comment by markmhx** [comment]
The transaction history here doesn't show a recent transaction: 

https://explorer.stacks.co/address/SP3V9N5A0GWACGRV778TSQDQGDHTTQT88JCY1N2XW?chain=mainnet

Mind trying it again and notifying us here when it's pending?

**Comment by Orion5455** [comment]
I think I found the problem. I stacked STX and locked it till 21.april and than I unsatcked them. Could it be possible that funds are unavaible to withdraw because of that?

**Comment by Orion5455** [comment]
Thx for all the help was finally able to withdraw.
