### ISSUE TITLE
Updated Stacks Wallet 3.0 to 4.0 - STX tokens are not showing up in my new wallet

### ISSUE THREAD

**Issue by jp1O1** [blockstack/stacks-wallet#748]
I just updated my Stacks wallet from 3.0 to the latest 4.0.  

I entered my 12 word seed phrase (from when I created the first 3.0 wallet) and created a new password for wallet 4.0.  When I open the new Stacks wallet 4.0, none of my STX tokens are there.

Please advise.

**Comment by kyranjamie** [comment]
The previous version of the Stacks Wallet created 24-word phrases, not 12 word ones. It is a common confusion to mix up your Blockstack Browser 12-word phrase with the 24-word one of the wallet.
