### ISSUE TITLE
Tokens not showing up in wallet

### ISSUE THREAD

**Issue by forexmaxpain** [blockstack/stacks-wallet#750]
I transferred a small amount of stacks from an exchange to my desktop wallet which is up to date.  The transaction is confirmed but tokens have not arrived 

https://explorer.stacks.co/txid/0x49cd08e11ab4982186a751e388bc3a12b12dce93c917a3dca6cbf74a13a75b37?chain=mainnet

**Comment by kyranjamie** [comment]
@forexmaxpain are you using the latest version of the wallet? https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.2

**Comment by forexmaxpain** [comment]
Hi kyranjamie,

Thank you for the reply, yes I am using the latest verison.
