### ISSUE TITLE
The use of Ledger can not transfer the problem

### ISSUE THREAD

**Issue by vovo999** [blockstack/stacks-wallet#753]
Use Ledger to withdraw  appear these prompts"The Stacks Blockchain API you're connected to returned a HTTP error code, preventing this transaction from broadcasting "

**Comment by markmhx** [comment]
Are you still experiencing this problem upon trying again today?

**Comment by vovo999** [comment]
I succeeded in withdrawing money yesterday，so Problem solved,thanks.

**Comment by venustar1228** [comment]
Now I am using Hiro wallet.
And I am facing the same situation.
Can you help please?

**Comment by markmhx** [comment]
cc @314159265359879

**Comment by 314159265359879** [comment]
> Now I am using Hiro wallet. And I am facing the same situation. Can you help please?

@venustar1228 Thanks for reaching out. How would you like to connect so we can go over what is happening? Perhaps you can share a screenshot. 
Do you have an option to try this on another device/internet connection?

Feel free to send a private message via support at hiro.so or on 
Discord: Werner3141#8516
Telegram: @Werner3141

**Comment by venustar1228** [comment]
![photo_2022-11-17_08-02-12](https://user-images.githubusercontent.com/97265571/202453861-1a784070-5648-493c-bbf3-df102c36a298.jpg)
Please refer to this image.
