### ISSUE TITLE
Add support for microblocks

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#754]
We should support microblocks in the UX as they pertain to:

- Initiating transactions
- Pending and confirmed transactions

**Comment by markmhx** [comment]
@jasperjansz The main difference in the UI for sending transactions relates to picking an asset in the web wallet vs. defaulting to just STX for the desktop, yea? Or what else do you have in mind? I'm certainly supportive in principle, though not sure this standardization is top priority atm.

**Comment by jasperjansz** [comment]
I was actually referring to the list of transactions in your activity. I agree it's not a priority.

**Comment by markmhx** [comment]
@kyranjamie mind creating more granular issues for the desktop wallet, adding them to [the relevant milestone](https://github.com/blockstack/stacks-wallet/milestone/52) then closing this general issue out? 🙏

**Comment by kyranjamie** [comment]
@markmhx I did this for the web wallet and explorer, but for the desktop wallet, there is only 1 task, right? 

To show transactions that are in microblocks, in the tx list?

**Comment by markmhx** [comment]
Yea I think that's basically it. @jasperjansz can confirm.

**Comment by jasperjansz** [comment]
confirmed!
