### ISSUE TITLE
[4.1.2] Bug: Stacking progress is frozen 

### ISSUE THREAD

**Issue by spruett1** [blockstack/stacks-wallet#755]
Bug found testing Stacks Wallet build undefined, 4.1.2.

My stacking progress is frozen and my STX do not show up when transferred although the blockchain record states they are transferred.  I can not access the locked STX.  When sent the STX do not show up even through they are deducted from my wallet.  How do i can access to my STX, and or un-stake, and or successfully transfer or re-stake.  Need help with this issue as account is virtually unusable at the moment,  This has been an issue since last year.

**Comment by kyranjamie** [comment]
If you're unable to access your STX because they're locked, it sounds like you're stacked.

Search for your address in the Explorer https://explorer.stacks.co/. Do you see the same as in the wallet?

**Comment by spruett1** [comment]
Thank you

On Apr 22, 2021, at 6:26 AM, kyranjamie ***@***.***> wrote:

﻿

Closed #755<https://github.com/blockstack/stacks-wallet/issues/755>.
