### ISSUE TITLE
Improve nonce calculation

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#759]
Presently, nonce calculation is pendings txs + address nonce.

This can be improve in not incrementing the nonce in the case of transactions where the nonce is < address nonce.

**Comment by markmhx** [comment]
Have we seen examples in the wild of transactions getting broadcast with the wrong nonce as a result of this?

**Comment by kyranjamie** [comment]
@markmhx there was one case.  Unclear if this would've helped though.

**Comment by markmhx** [comment]
This is also getting tackled in the upcoming release, correct? Should we link it to a PR and put on the board?

**Comment by kyranjamie** [comment]
Speaking with @yknl miners are having issues with this issue specifically. Will prioritise for this release.
