### ISSUE TITLE
[4.1.2] Bug: <Cannot 'unlock' STX tokens>

### ISSUE THREAD

**Issue by PaulySavy21** [blockstack/stacks-wallet#761]
Hello,

I recently revoked my STX delegation and I am trying to withdraw my tokens from this wallet, but the tokens remain 'locked' and I cannot withdraw them.  How do I 'unlock' them at this point?

Please help.

Thanks,

Paul

https://explorer.stacks.co/address/SPZW6FEQ9021GRC3MS4WCZQVPE1YK2V7ZKQHYWTP?utm_source=stacks-wallet&chain=mainnet

  Thanks for creating an issue. Please include as much detail as possible,
  including screenshots, operating system, and steps to recreate the problem.

  If you have any questions, ask @kyranjamie on Github, Discord and Twitter.

-->

Bug found testing Stacks Wallet build undefined, 4.1.2.

**Comment by kyranjamie** [comment]
Hi @PaulySavy21

Once you've delegated, and your delegator has stacked on your behalf, you will only be able to access the tokens when all cycles are finishes.

**Comment by PaulySavy21** [comment]
How do I determine when that is?

Paul

**Comment by markmhx** [comment]
It appears you used the Friedger Pool address for three cycles to delegate:

SP3K3ZEQVE1E914TFPFMT3A7M53MNMWZCFVQCQB0H
https://pool.friedger.de/

![image](https://user-images.githubusercontent.com/28991/115027822-75ad4380-9ec4-11eb-97a1-8b42e62c4f5c.png)

So I assume they'll unlock no more than 3 cycles / ~6 weeks from now. But perhaps @friedger can confirm.

**Comment by PaulySavy21** [comment]
Ok, thanks.   I appreciate the help.

Paul

**Comment by PaulySavy21** [comment]
Curious though, will I still receive stake rewards, even though I revoked?

Thanks,

Paul

**Comment by aulneau** [comment]
> Curious though, will I still receive stake rewards, even though I revoked?

Yep, you can think of revocation as removing permission for someone to lock on your behalf. Once you've been locked, it only prevents folks from locking for you again in the future.
