### ISSUE TITLE
[4.1.2] Bug:  Unable to log in to Stacks wallet on Ledger Nano X

### ISSUE THREAD

**Issue by kkditt** [blockstack/stacks-wallet#768]
<Hello, I previously loaded an earlier version of the Blockstacks wallet which utilized the BTC app for working with STX on my Ledger Nano X.  I recently upgraded to the new Stacks wallet and was also able to download the Stacks app on the Ledger just fine, and when I open the wallet  it's able to see the Ledger okay.  When I try and connect the Ledger to the Stacks wallet I get "Pending Ledger Review" as expected, but when I press both buttons on my device, I get kicked off of the wallet all together and then I lose all the lights on the Ledger as if the battery has gone dead.  After several minutes, the lights come back on, but I still can't connect to the wallet.  

  Thanks for creating an issue. Please include as much detail as possible,
  including screenshots, operating system, and steps to recreate the problem.

  If you have any questions, ask @kyranjamie on Github, Discord and Twitter.

-->

Bug found testing Stacks Wallet build undefined, 4.1.2.

**Comment by kyranjamie** [comment]
Sorry to hear this @kkditt. There are issues with the Ledger X freezing on this screen. This issue should be resolved soon in the Ledger Stacks app upgrade.

As a work around, can you try opening your Ledger app on the Stacks app screen, past _Pending Ledger Review_ **before** you open the popup in the Stacks Wallet to sign the transaction? Please let us know if this works.

**Comment by markmhx** [comment]
@kkditt can you try the steps provided by @kyranjamie above to see if they work for you?

**Comment by protajack** [comment]
I'm having a similar issue. First I connect and unlock my ledger nano x on the ledger live manager, then I open the stacks desktop app, click receive, then I open the stacks app on my nano x and then I get kicked off of the ledger live manager and am instructed to once again connect and unlock my device. I've tried repeatedly with the same result each time. I also updated my nano x firmware, updated the stacks desktop app to 4.3.0 and tried turning off my VPN.

@kyranjamie can you clarify these directions:
> As a work around, can you try opening your Ledger app on the Stacks app screen, past _Pending Ledger Review_ **before** you open the popup in the Stacks Wallet to sign the transaction? Please let us know if this works.

**Comment by kyranjamie** [comment]
Ledger Live is only needed to _install_ the Stacks Ledger app. It isn't needed open _while_ you're using it with the Stacks Wallet4. Further, as both pieces of software (Ledger Live & Stacks Wallet) attempt to interface with the Ledger, one of the two will fail to connect, as only one piece of software can use it at once.

I'd suggest you try again,  but while Ledger Live (or any other Ledger using piece of software) is closed.

**Comment by protajack** [comment]
Thank you!
