### ISSUE TITLE
Update Stacking copy, add Stacking guide card, and display amount warning

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#769]
Update copy wherever marked with orange dots here (and _only_ where marked with orange dots!):

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=4992%3A0

Also add card for linking to the Stacking guide and warning for amount entry whenever value entered is less than the current dynamic minimum plus the amount required for one additional reward slot (i.e. the amount for two reward slots in total).

**Comment by jasperjansz** [comment]
fyi the stacking guide is here: https://blog.stacks.co/stacking-strategy
