### ISSUE TITLE
[4.1.1] Bug: Created wallet with my 24 word pass phrase, but it only connects to Testnet

### ISSUE THREAD

**Issue by MichaelSaucier** [blockstack/stacks-wallet#771]
Bug found testing Stacks Wallet build undefined, 4.1.1.
![image](https://user-images.githubusercontent.com/3967907/115800106-89164e00-a39f-11eb-9a6c-e3b6fc6a795e.png)

**Comment by kyranjamie** [comment]
Hi @MichaelSaucier 

There are two flavours of the Stacks Wallet, _Mainnet_ and _Testnet_. They're distinct applications.

You're using the testnet wallet here. Try again with the latest version of the [Stacks Wallet for Windows here.](https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.2). You need the one labelled `stacks-wallet.mainnet.v4.1.2.exe`
