### ISSUE TITLE
issue with wallet showing 0 balance, showed transaction in wallet on Nov 30th from binance completed

### ISSUE THREAD

**Issue by hhodler** [blockstack/stacks-wallet#772]
Today I opened my old stacks wallet to see about upgrading for staking, I saw that my balance was 0, it shows a transfer i made on nov 30 from binance to be invalid even though i believe the coins were posted to the wallet at some point.  I upgraded to the latest wallet and refreshed with my seed phrase and it still shows 0 balance.  Binance shows the transaction as complete.  How do I go about getting my coins in the wallet for staking?

**Comment by markmhx** [comment]
Mind providing more information such as your STX address and a screenshot of the Binance confirmation by sending to wallet@hiro.so? We can help you there.
