### ISSUE TITLE
Show receipt activity item for send-many events instead of fees

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet#776]
This feature request is about the display of fees for contract call transactions in the list of transactions.

Currently, the wallet shows the fees that the tx sender paid even thought the users didn't send the tx. It is shown in the same column as the users stx movements, the amounts shown won't add up to the total balance. 

The fees should be hidden if not paid by the user or shown differently. If paid by the user it should also shown the total transfer. Related to https://github.com/blockstack/explorer/issues/373

**Comment by markmhx** [comment]
This is a screenshot of the current behavior:

![image](https://user-images.githubusercontent.com/28991/116315581-03d0d600-a7b1-11eb-8cd3-691b9fcec170.png)

This shows the amount of fees paid on top ("Contract call"), which should be replaced with an activity item showing the amount of STX received.

We can fix it using the API support provided by https://github.com/blockstack/stacks-blockchain-api/pull/547

**Comment by kyranjamie** [comment]
Reddit users expressing confusion, definitely needs to be addressed

https://www.reddit.com/r/stacks/comments/n9aq2b/i_read_on_my_stacks_wallet_that_there_has_been_a/
https://www.reddit.com/r/stacks/comments/n92k3o/shouldnt_i_be_seeing_my_rewards_in_my_wallet/

**Comment by Eshwari007** [comment]
@kyranjamie Can I we sync up on the ticket in order to get more content of the issue?Thx in ad
