### ISSUE TITLE
[4.1.2] Bug: delegation button doesn't appear for second delegation

### ISSUE THREAD

**Issue by kulwins** [blockstack/stacks-wallet#779]
Hi there,

I'm new to stacks wallet. I'm using windows version and successfully used it for one delegation. However, now I want to delegate more coins for stacking but it doesn't give me an option to select delegation.

Bug found testing Stacks Wallet build undefined, 4.1.2.

**Comment by markmhx** [comment]
This is expected behavior. You will have to revoke the first delegation because only one is possible at a time. You can alternatively set up a second address with STX and delegate additionally from there without having to revoke the first.
