### ISSUE TITLE
[4.2.0] Bug: Ledger app auto-closing

### ISSUE THREAD

**Issue by bhess8** [blockstack/stacks-wallet#789]
Trying to connect Stacks Wallet to Ledger, I downloaded Stacks App, select it on my device, double click pending review, it says stack ready on the device, then quickly says "Expert Mode Disabled" and then the the app closes on the device

**Comment by kyranjamie** [comment]
Thanks for reporting @bhess8 

Can you follow up with:
1. Model of Ledger device
2. Version of Ledger device firmware
3. Version of Stacks app on Ledger device
4. Operating system and version

**Comment by bhess8** [comment]
Model of Ledger Device:  Nano S

Version of Ledger Device Firmware  1.6.1

Version of Stacks App on Ledger Device:  Ver 1.11.0

Operating system – Window 10  64 bit operating system,  Edition Window 10 Pro  Ver 2004  OS build 19041.928

**Comment by kyranjamie** [comment]
@bhess8 Ledger recently released firmware version 2.0 for the Nano S. I'd suggest upgrading to this firmware version, then trying again.

**Comment by bhess8** [comment]
It worked.  Thank you!

**Comment by bhess8** [comment]
Hi, I’m trying to download and set up the Electrum Wallet, using Ledger Live hardware Nano S.  I did update the Firmware to version 2.0

That got the Stacks wallet to connect,

 

But the electrum wallet will not find the device.

Even though I can see it in settings/devices/coneected devices.

 

I tried removing and readding

 

Here is the error code

Debug message

ledger: (error getting device infos)

Exception : Invalid status 6702

 

Model of Ledger Device:  Nano S

Version of Ledger Device Firmware  2.0

Operating system – Window 10  64 bit operating system,  Edition Window 10 Pro  Ver 2004  OS build 19041.928

**Comment by bhess8** [comment]
I rebooted, and the only ledger piece up was electrum

 

 

Ledger live was up.  Device connected and set to bitcoin.

 

Still same error 

 

Here is the error code

Debug message

ledger: (error getting device infos)

Exception : Invalid status 6702

 

Model of Ledger Device:  Nano S

Version of Ledger Device Firmware  2.0

Operating system – Window 10  64 bit operating system,  Edition Window 10 Pro  Ver 2004  OS build 19041.928

 

Thank you.

Barbara Hess
