### ISSUE TITLE
QR Scan code icon in wallet transaction page is confusing

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-wallet#79]
We have a scan code in the explorer and then also show one as an icon in the wallet.  The icon use in the  wallet is just an icon choice --- it doesn't link to a transaction with that QR or anything.  Users familiar with QR codes or their use in our explorer are confused by this icon.

Switch to an icon that doesn't imply functionality or a relationship to the explorer that doesn't exist.

**Comment by timstackblock** [comment]
Thanks for writing this up @moxiegirl

**Comment by markmhx** [comment]
This is getting resolved with the new Stacks Wallet, which omits an icon here entirely.
