### ISSUE TITLE
[4.2.0] Bug: I created a new wallet using ledger Nano S.    Should i have been prompted to set a password?  Should i have been prompted for a Pass phrase? I was not prompted for this.  I know other wallets where I connect via ledger do have recovery phrases and passwords.

### ISSUE THREAD

**Issue by bhess8** [blockstack/stacks-wallet#790]
Bug found testing Stacks Wallet build undefined, 4.2.0.

**Comment by kyranjamie** [comment]
Using a Ledger, your seed phrase is on the device itself, so the wallet doesn't ask for a password. 

As the wallet doesn't know what your seed phrase is, it cannot offer any recovery steps for Ledger. You would have been asked to secure you device's seed when setting it up.
