### ISSUE TITLE
Manage Ledger app version upgrade path

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#798]
The latest [Stacks Ledger app](https://github.com/Zondax/ledger-blockstack/releases/tag/npm_v0.2.0) includes breaking changes to support testnet addresses with the same `m/5757...` derivation path. 

Testing this version out, the behaviour of requesting an address **without specifying the chain id**, as it works now, is a silent failure. No response given from the device.

To avoid an influx of support requests when users upgrade/install their Ledger app and the wallet breaks, I suggest we:
1) **Implement Ledger version support pre-Ledger app release**
Add in a version check, and warning, if a Ledger app version is greater than the current version.
2) **On Stacks Ledger app release in Ledger Live store**
Release a new version of the wallet that only supports the new version and above.

@markmhx @andresgalante

**Comment by andresgalante** [comment]
Thanks Kyran for keeping an eye on the ledger implementation.

@markmhx can you prioritize this vs the other things we have on the backlog, please?

**Comment by markmhx** [comment]
Let's discuss during our kick-off meeting today.

**Comment by andresgalante** [comment]
@markmhx has messaged Ledger and asked them to hold off releasing it therefore we have no immediate action to take, and this issue is not a priority anymore

**Comment by kyranjamie** [comment]
#806 handles step 1, ensuring users are using the most recent **current** version.

Step 2 requires us to upgrade the Ledger js library and have a release ready for when it's merged. This isn't a big task, but needs to be done in a separate release.

**Comment by andresgalante** [comment]
Do we have an issue to track step 2?
