### ISSUE TITLE
[4.1.3] Bug: Importance of memo field in outbound transaction is not clear enough to user

### ISSUE THREAD

**Issue by kcdenman** [blockstack/stacks-wallet#799]
Issue: the memo field is of critical importance but does not provide any guidance to the user regarding its core purpose in securing a transaction.

In the below screenshot, it simply says "Memo"

![image](https://user-images.githubusercontent.com/10832542/117688392-b9733000-b186-11eb-8389-23d6daaf3af4.png)

When I submitted my first ever outbound transaction from my wallet to OKCOIN, I entered "Transfer from Stacks to OKCOIN". This string was accepted and the transfer was initiated.

One could argue this is a "user error", but I would argue it is UX error. If the memo is a critical data element in authenticating the transaction on the receiving exchange/wallet, the description text of Memo in the stacks wallet should say as much - especially if there is not a mechanism to validate the memo value entered corresponds to the memo value at the desintation wallet.

Reference to another thread with screenshots here: https://github.com/blockstack/stacks-wallet/issues/626

Bug found testing Stacks Wallet build undefined, 4.1.3.

**Comment by markmhx** [comment]
Thanks for reporting 🙏 We have a separate issue (https://github.com/blockstack/stacks-wallet/issues/571) already that tracks this improvement, so I'll close this one out. But it will be linked from there for additional context.
