### ISSUE TITLE
Nano ledger shows blank amount screen and "OP_RETURNE" for the address

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#80]
**Describe the bug**
When sending stacks with a wallet that is connected to a Nano Ledger the hardware wallet doesn't recognize the Stacks address or amount but handles it gracefully.  After I select send and I am prompted to confirm the transaction on my nano ledger. The address I am asked to confirm comes in as "OP_RETURNE" and the amount comes up as a blank screen.

**To Reproduce**
1. Connect a nano ledger to the stacks wallet version 3
2. Send a micro stack to a valid stacks address, everything works well in the stacks wallet app.
3. The wallet will ask you to connect your nano ledger and make sure the pin is unlocked, you are on Bitcoin account and you set the Browser option = no
4. Then the Nano ledger ask you to confirm 3 transactions, the first 1 has a blank amount and an address that reads "OP_RETURNE this is the Stacks transaction. The next 2 transactions are for the bitcoin needed to process that send request those have visible addresses and amounts.

**Expected behavior**
The hardware does not recognize our stacks wallet input but it handles it gracefully and does not crash. We just see blanks screens and error messages while sending. I would expect this to show us a valid address and an amount.

**Screenshots**

![20190429_213037](https://user-images.githubusercontent.com/49165468/56962237-0cd82f80-6b24-11e9-8e86-5ea6a86ccf4e.jpg)

![20190429_213033](https://user-images.githubusercontent.com/49165468/56962357-59236f80-6b24-11e9-9559-927ef6a020ae.jpg)

**Desktop (please complete the following information):**
 - OS: [10.14.4 Mojave]

**Hardwallet (nano ledger):**

**Stackswallet Version 3 Alpha release**

**Comment by yknl** [comment]
The first output is the encoded Stacks transaction in the OP_RETURN. The Ledger device can't decode this currently. So this is expected behaviour.

**Comment by markmhx** [comment]
I'm closing this out given @yknl's comment that this is expected behavior.
