### ISSUE TITLE
[4.2.0] Bug: Using Ledger with Stacks wallet

### ISSUE THREAD

**Issue by Phil-Taphouse** [blockstack/stacks-wallet#803]
Bug found testing Stacks Wallet build undefined, 4.2.0.

**Comment by Phil-Taphouse** [comment]
Further, as soon as i select the Stacks app on my ledger, the ledger immediately crashes and loses connection and cannot access the wallet in Ledger Live app.

**Comment by kyranjamie** [comment]
@Phil-Taphouse Can you restart the Stacks Wallet and try again while the Ledger Live app is closed? Two applications using the Ledger at the same time can cause problems.

**Comment by Phil-Taphouse** [comment]
Great - thank you. That worked.
