### ISSUE TITLE
[4.2.0] Bug: Image is broken on the top of STACKING and POOLING page 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#808]
Bug found testing Stacks Wallet build 1dd7ddd, 4.2.0.

After I select the option to stack and I go to the page that gives me the option to select STACKING or POOLING I notice that the image is broken on the top of both of those buttons.

<img width="1018" alt="Screen Shot 2021-05-21 at 11 06 01 AM" src="https://user-images.githubusercontent.com/49165468/119159915-bea56a00-ba25-11eb-9749-d762fc34a22e.png">

**Comment by kyranjamie** [comment]
Thanks @timstackblock—guess there's something up with the image bundling

**Comment by kyranjamie** [comment]
Fixed in 74cd293
