### ISSUE TITLE
[4.2.0] Bug: User can add a BUFFER and select MAX amount of STX which will allow them to stack more STX than they have

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#809]
Bug found testing Stacks Wallet build 1dd7ddd, 4.2.0.

If the user enters an amount of STX to stack and the buffer option appears and they select the button to add the buffer amount of STX. The user can go back and change the amount of STX stacked and the buffer will not be removed. In the video link below I selected the MAX option and the transaction is trying to stack my MAX amount and the added buffer of STX. This will result in a failure because the amount is more than is in the wallet, is it possible top automatically remove the buffer if the stacking amount is changed to stop these edge case scenarios?

LINK TO VIDEO OF THE BUG.
http://somup.com/crhro3qhYW

<img width="1011" alt="Screen Shot 2021-05-21 at 11 11 58 AM" src="https://user-images.githubusercontent.com/49165468/119161225-11335600-ba27-11eb-88c5-3107f953bdb1.png">

**Comment by kyranjamie** [comment]
As discussed on [#userx discord](https://discord.com/channels/621759717756370964/745197302255321108/845350919809531934), this is expected behaviour
