### ISSUE TITLE
Connecting the Nano Ledger back to Ledger Live Manager after the stacks wallet causes "Unrecognized Input" error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#81]
**Describe the bug**
After I discovered a blank screen and an error message while sending stacks I wanted to see how the Ledger Live software handles our Stacks Wallet. The hardware handles errors gracefully as shown in Issue #80 it does not stop the transactions from processing even when it doesn't recognize the input (address or amount). But the Ledger Live software does not handle unrecognized input gracefully. It will not allow me into Manager once I have added a Stacks wallet. 

Once I get to the "Allow Ledger Manager on your device" step on the Ledger manager, I get the error message "Unrecognized input". 

(this is not shown in the screenshot ran into another issue before I could screenshot the error message and that locked my ledger)

**To Reproduce**
1. After you have connected your nano ledger to your Stacks Wallet, open the Ledger Live app
2. Click on 'Manager' in the left nav, you will be prompted to "connect and unlock your device", the next step prompts you to "Navigate to the Dashboard"
3. The third step is where we get the error message. When the user gets to the "Allow Ledger Manager on your device" step. Click yes to allow Ledger Manager on your ledger nano device. After you have selected yes on your device the Ledger Live screen on your mac will then give you an "unrecognized input" error message

**Expected behavior**
The Ledger Live software should not break when users attempt to manage their Nano Ledger accounts after connecting the Nano Ledger to the Stacks wallet.

Real world example: If I have an Ether account on the same Nano Ledger I should still be able to access ledger live Manager.

**Screenshots**
<img width="748" alt="Screen Shot 2019-04-30 at 9 18 18 AM" src="https://user-images.githubusercontent.com/49165468/56965336-0d27f900-6b2b-11e9-9fb4-92792cf31ff0.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by markmhx** [comment]
@yknl any ideas?

**Comment by yknl** [comment]
This is an issue with the Ledger device. closing
