### ISSUE TITLE
Stacks revoked but still locked.

### ISSUE THREAD

**Issue by unclemantis** [blockstack/stacks-wallet#812]
![image](https://user-images.githubusercontent.com/718701/119225419-b30f7d00-bad1-11eb-974f-7de9d105b9a4.png)

Using 4.2.0

**Comment by kyranjamie** [comment]
Expected behaviour. Your STX will be unlocked at the end of your chosen delegation period.

**Comment by unclemantis** [comment]
I was not sure if I locked one or 3 cycles.  Thank you.
