### ISSUE TITLE
[4.2.0] Bug: Attempting to send token and returning back from Preview screen throws validation error

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet#815]
Bug found testing Stacks Wallet build e4f41fb, 4.2.0.

https://user-images.githubusercontent.com/38872890/119408853-659f3580-bcb4-11eb-82a3-16f29706b6e4.mov

**Comment by kyranjamie** [comment]
Good find @Eshwari007. Let's use this issue as a guide of the best flow for issue handling. While ideally this issue should be fixed _for_ `release/4.3`, it isn't fixed _by_ that branch.

Typically what I'll do in this scenario is create another PR with a commit referencing #815. This can merge into `release/4.3`.

**Comment by Eshwari007** [comment]
@kyranjamie Test passed for the bug above as well
