### ISSUE TITLE
[4.2.0] Bug: Settings>Theme>Use system color node setting isn't working

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet#817]
Bug found testing Stacks Wallet build e4f41fb, 4.2.0.

Environment:Test net

Actual scenario:
Selecting the use system color mode  under theme section in settings isn't working

Expected scenario:

All the selection under settings should work
<img width="712" alt="settings" src="https://user-images.githubusercontent.com/38872890/119412119-6be3e080-bcb9-11eb-8c9b-803b4504170a.png">

**Comment by markmhx** [comment]
Mind describing the behavior you're seeing here exactly? Does the wallet not apply the system color from the start or does it get out of sync later?

**Comment by Eshwari007** [comment]
No behavior at all.I tried selecting the system color and it isnt working from the start

**Comment by kyranjamie** [comment]
What colour mode is your Mac in, @Eshwari007? If your Mac is in light more, as is your Stacks Wallet, clicking this will do nothing.

**Comment by Eshwari007** [comment]
Yes,it was in light mode.Will re test in dark mode.Do we know why it wont in light mode?Shouldnt it detect light mode and change to dark as its doing vice versa for the dark mode to light upon selection?

**Comment by kyranjamie** [comment]
@Eshwari007 Clicking this button should set the theme to the same as your system, set here 
![image](https://user-images.githubusercontent.com/1618764/119617929-9ab99e00-be02-11eb-9be3-d21fa0aa222d.png)

Say if your Mac is in dark mode, but the wallet is in light mode, clicking this button should set it to dark mode.

**Comment by markmhx** [comment]
This seems to be a case where it's functioning properly but since there's no affordance when no change occurs, the user is left wondering if it worked as intended. @jasperjansz thoughts on how we could handle this more clearly?

**Comment by kyranjamie** [comment]
Yes, indeed. The button should be disabled when it's already on system preference.
