### ISSUE TITLE
[4.2.0] Bug:No error message is displayed for excess amount of STX inputted beyond the max 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet#819]
Bug found testing Stacks Wallet build e4f41fb, 4.2.0.
  Environment:Test Net

Actual scenario:
User notice the issue is intermittent ,it was reproducible on first instance and couldn't second attempt
User inputted the STX amount beyond that the max amount 
No error messages were thrown
Second try, error message were thrown
Is there a way to limit the numeric values entered  beyond the max amount?

Expected scenario:
Error message should be consistent 
<img width="620" alt="correct error message" src="https://user-images.githubusercontent.com/38872890/119418352-d69b1900-bcc5-11eb-824c-440c9508773c.png">
<img width="1440" alt="correct error message 2" src="https://user-images.githubusercontent.com/38872890/119418354-d69b1900-bcc5-11eb-8adc-df7a5cd67204.png">
<img width="1326" alt="disable user to enter more than the  max" src="https://user-images.githubusercontent.com/38872890/119418364-da2ea000-bcc5-11eb-8c4b-a2b9dea5d1b8.png">
<img width="1341" alt="no error message for excessive token" src="https://user-images.githubusercontent.com/38872890/119418365-dac73680-bcc5-11eb-89b7-f6901765ed44.png">

Attaching screenshot for perusal

**Comment by markmhx** [comment]
Mind providing a screenshot?

**Comment by Eshwari007** [comment]
@markmhx Seems like the snapshots were truncated between the lines.All fixed now.Will fix the rest of the screenshots of teh bug(s) as well

**Comment by Eshwari007** [comment]
@kyranjamie Test passed for the bug above as well.
