### ISSUE TITLE
Updating firmware on Nano ledger after connecting to Stackswallet freezes ledger on Bootloader screen

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#82]
**Describe the bug**
After uploading firmware, my nano is currently locked on the Bootloader screen. I was prompted to download the latest Firmware for my nano. A prompt appeared that stated, "Please uninstall all apps, but address and balances will not be affected". This made me think the stacks address would be ok, but after some thought, this is not a standard bitcoin address and may not be recognized as just an address and may cause issues with firmware updates.

I updated the firmware and was prompted to disconnect my nano and hold down the left most button for 5 second while reconnecting it and the "Processing" screen would appear. The "Bootloader" message appeared and the nano is now locked on that screen and is unusable.

**To Reproduce**
1. Go to ledger live you will be prompted to update the firmware
2. Click on the update button
3. You will be told to disconnect and reconnect you nano ledger and hold down the left most button for 5 seconds until the "processing" screen appears
4. The nano is stuck in Bootloader mode

**Expected behavior**
The firmware should continue to be updated normally after interacting with the stacks wallet

**Screenshots**
![20190430_095807](https://user-images.githubusercontent.com/49165468/56967493-50846680-6b2f-11e9-8eab-b64364a81c20.jpg)

**Desktop (please complete the following information):**
 - OS: [10.14.4]

**Additional context**

**Comment by timstackblock** [comment]
@wileyj

**Comment by markmhx** [comment]
@yknl any ideas?

**Comment by b4nky** [comment]
Hello.
I am using 10.13.6.  and gone through the exact same procedure and have the same result.

**Comment by timstackblock** [comment]
This is a nano ledger problem, this issue will be closed.
