### ISSUE TITLE
Wallet displays unlocked amount as total balance

### ISSUE THREAD

**Issue by cuevasm** [blockstack/stacks-wallet#829]
Total balance shows available, instead of total.

![Should show total here, only shows available, can't see total wo going to explorer, scared me haha!](https://user-images.githubusercontent.com/6131188/120708061-ee199500-c46f-11eb-8528-a8832a781a43.png)

Bug found testing Stacks Wallet build undefined, 4.2.0.

**Comment by kyranjamie** [comment]
Thanks for reporting Mitchell. I thought this'd been fixed already—apparently not.

**Comment by cuevasm** [comment]
New build fixed it!
