### ISSUE TITLE
Adding a long note while sending stacks stops the transaction from going through, loading button freezes

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#83]
**Describe the bug**
Attempt to send stacks and enter a long note you will notice that the transaction does not go through and the "loading..." button displays indefinitely. I have a video link below please watch the recorded video to reproduce. 

**To Reproduce**

_Here is a screen record of the issue:_ http://somup.com/cqhVIynx0E

1. Go to your wallet and attempt to send stacks
2. Click on enter a NOTE that has multiple words as shown in the video link above
3. Press CONTINUE
4. The button will state "loading..." but nothing happens

**Expected behavior**
Stacks are sent when I do not add a note, the note may be breaking the sending of stacks action

**Screenshots**
<img width="957" alt="Screen Shot 2019-05-01 at 9 39 59 AM" src="https://user-images.githubusercontent.com/49165468/57019677-2bf2c200-6bf5-11e9-971e-62f24d3c57d8.png">

**Desktop (please complete the following information):**
 - OS: [10.14.4 iOS]

**Smartphone (please complete the following information):**

**Comment by yknl** [comment]
Resolved in latest commit on software wallet branch
