### ISSUE TITLE
[4.3.0] Bug: STX wont show up in my wallet

### ISSUE THREAD

**Issue by doeboy1** [blockstack/stacks-wallet#835]
I recently sent STX over to my wallet but it has said its pending for over 12 hours now.

Bug found testing Stacks Wallet build undefined, 4.3.0.

**Comment by markmhx** [comment]
I'm closing this issue since it's unlikely due to a problem with the Stacks Wallet itself. 

If your transaction hasn't settled yet, please inquire about it in the support channel on Discord: http://stacks.chat/
