### ISSUE TITLE
User can send stacks to an address while the balance is pending causing a negative wallet balance

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#84]
**Describe the bug**
There is a small time frame/window where I can send stacks from my wallet when I do not have enough to cover the transaction if I do it very fast after the previous transaction. If I have .000001 stacks in my wallet and I send out .000001 stack I now have a wallet with a pending balance of 0 and a balance of .000001 stacks. 

It seems to take the "send pop-up screen" and the "amount to send" field a little while to realize it should be using the new pending balance.  For the first few seconds while this amount is pending I can continue to send .000001 stacks out of the wallet causing a scenario where I send stacks I do not have. The pending balance will go into the negative and I have sent out more stacks then I had in my wallet.

**_SCREEN RECORD OF BUG IN THE LINK BELOW_**
http://somup.com/cqhVqmnxxC

**To Reproduce**
1. Log in to a wallet with only .000001 stacks
2. Send .000001 stacks out of the wallet
3. Very quickly close out of the confirmation window 
4. Attempt to send .000001 stacks out of the wallet right after the previous transaction
5. The wallet will allow this and go into the negative

**Expected behavior**
The wallet should use the Pending balance right after a transaction to avoid allowing a user to send more stacks than they have 

**Screenshots**

### **_NOTICE THE NEGATIVE PENDING BALANCE_**

<img width="836" alt="Screen Shot 2019-05-01 at 3 46 59 PM" src="https://user-images.githubusercontent.com/49165468/57038872-ff589d80-6c28-11e9-8f78-b2e1310a78dc.png">

**Desktop (please complete the following information):**

StacksWallet 3.00 Alpha4

**Comment by timstackblock** [comment]
Here is a screenshot of the wallet receiving the micro stacks from the transaction above. They seem to have moved to this address and are pending.


<img width="837" alt="Screen Shot 2019-05-01 at 4 15 08 PM" src="https://user-images.githubusercontent.com/49165468/57040121-82c7be00-6c2c-11e9-9005-661fa8310fd2.png">

**Comment by markmhx** [comment]
I'm closing this out given conversation with @timstackblock in which we expect to test for this behavior and ensure it doesn't happen in the new wallet.
