### ISSUE TITLE
[4.3.1] Bug: <describe issue> Totally confused and my own fault! 

### ISSUE THREAD

**Issue by along26** [blockstack/stacks-wallet#846]
So I'm hurting for $ and decided to sell my STX to get some needed funds. I assumed all I needed to do to send money from my STX wallet to my OKCoin account was to simply send my STX to the same address (It's like SP3...etc) that I have received all my STX from. However, obviously, that is not how to transfer STX's to OKCoin.

Is there anyway for me to get this resovled? It was only like $250 worth of STX, but I need it! 

STX WALLET

**Comment by kyranjamie** [comment]
Sorry to hear this. You'll have to speak to Okcoin if you deposited to the wrong address. Get in touch with their support.
