### ISSUE TITLE
[4.3.1] Bug: Issue sending to Ledger Nano X

### ISSUE THREAD

**Issue by baryaj** [blockstack/stacks-wallet#853]
Bug found testing Stacks Wallet build undefined, 4.3.1.

cannot send STX from STACKS wallet to Ledger Nano X - all software is at latest revisions on the Ledger device and Ledger Live and Stacks wallet is at latest release - have tried many times and have run with both Ledger AND Stacks written instructions - every time get STOPPED with this message "Must be a valid Stacks Address" - I have used and verified each time the 'receive' address generated by the Ledger device - this has been going on for over 6 months - even tried using a different and new Ledger device - same result - do not have any similar problems with the Ledger so it is my assumption that the STACKS software is the problem - thank you, Barry

**Comment by kyranjamie** [comment]
Hi Barry

Can you share the address you're trying to send to?

**Comment by baryaj** [comment]
Jamie Kyran

The address is 0x407f081E4176E5Be6B9e68e36F0cdde24079aE1F as given by the Ledger Nano X 

This is the same address all ETH coins go to. The Ledger tracks them eventhough it does not fully support all of them.

I have sent most of my ERC-20 coins to the Ledger this way

Barry

**Comment by kyranjamie** [comment]
@baryaj `0x407f081E4176E5Be6B9e68e36F0cdde24079aE1F` is not a stacks address. Stacks addresses typically start with `SP`. It isn't hexadecimal.

I think you're trying to use the ETH app. Stacks isn't an ERC-20 token. It's its own blockchain.

You need to download the Stacks app for your Ledger. [See instructions here.](https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet)

**Comment by baryaj** [comment]
so, I followed your written instructions below (see notes beside for what happened) bottom line, I was not able to send/receive the STX coins

PLEASE HELP!

To begin with, I deleted the STACKS app on my Ledger Nano X and reinstalled it according to your instructions. The app installed successfully and is verified (see print screen)



Then I deleted the Stacks wallet on my Mac Pro and reinstalled it (latest version)
So the following is what happens: in red

Receive STX with Ledger device
Open the Stacks Wallet wallet opened (see print screen view  
Select "I already have a wallet” as you can see, I do not get this “I already have a wallet” prompt
Select "Continue with Ledger"
Connect your Ledger and enter its PIN on the device I connected ok
Open the Stacks app on your Ledger device  I get pending review message - I accepted i (double click) and the Ledger says Stack Ready
Select "Continue" to view the receive address on your Ledger device the STACKS  app/coin does not appear as an option in the list of coins THIS IS WHERE I AM STOPPED ….. NO COIN IN THE LIST AND THEREFORE NO RECEIVING ADDRESS!!!
Select "Approve" on your Ledger device never get this far
Select "Receive" at the top of the window under your total balance
Copy the address shown or scan the displayed QR code to another wallet to receive STX from it

**Comment by markmhx** [comment]
>  the STACKS  app/coin does not appear as an option in the list of coins

@baryaj If the Stacks app is open upon arriving at this step, the Ledger device should simply ask you to confirm on the device. There shouldn't be any Stacks app or coin option per se.

Are you looking at your Ledger device at this step or your computer screen?

**Comment by baryaj** [comment]
When I click on ‘Receive’ in Ledger Live, Ledger Live (on my Mac Pro laptop) brings me the page shown to select the coin I want to receive. With all other coins, when I click on a coin, it then displays the receiving address for the coin selected and I go through the verification process. The problem is that Ledger Live does not see the STACKS app installed on my Ledger Nano X even though the app is installed and ready (on the Ledger Nano X read out.

When I log into the STACKS app, it never asks of suggest doing anything with my Ledger. It always takes me to the page shown in the screen print shown in my earlier email.

I look forward to a resolution.

Thank you.

Barry

**Comment by markmhx** [comment]
@baryaj There's no need to click on "Receive" in Ledger Live. You won't find Stacks listed there, as you've encountered.

Once you've installed the Stacks app on your Ledger device, you can quit Ledger Live completely before proceeding to sign into the Stacks Wallet on your computer with your Ledger device (and the Stacks app open on it).

 Once you click "Continue with Ledger" in the Stacks Wallet and "Continue" on the modal that appears, you should see a message on your Ledger device asking you to confirm your address. Do you see that message?

**Comment by baryaj** [comment]
Mark,

OK

Here is what happens:

1. opened STACKS wallet and click on ’send’ - ’send’ screen opens and asks for address to send it to - screen shot below - 

2. the STACKS app is open on my ledger Nano X - 

No address is shown on Ledger to verify and/or copy/paste into the STACKS send screen

I have tried disconnecting Ledger from computer and reconnecting …… quitting STACKS app on Ledger and reopening it 

Don’t know what else to do/try?

Barry

**Comment by baryaj** [comment]
here is screen shot sorry

**Comment by markmhx** [comment]
@baryaj Mind trying to attach your screenshot again? I don't see it.

**Comment by baryaj** [comment]
Hi Mark.

Attached:



Barry

PS: would it be a good idea to create a new STACKS wallet, transfer from old wallet into it, and then try send to Ledger. It’s about the only thing I haven’t tried (I think)

**Comment by markmhx** [comment]
@baryaj Sorry but the screenshot isn't appearing for me still. Could you email it to me instead at mark@hiro.so?

**Comment by markmhx** [comment]
Here is the screenshot provided by @baryaj:

![D2475F06-0E4F-4781-9C6C-10E0B8F4D020](https://user-images.githubusercontent.com/28991/126475658-d0ebaf45-4a30-4b70-bb1c-4281f5d98588.png)

It appears you need to submit the "Send STX" form above before your Ledger device will prompt you to confirm the transaction.

What happens when you enter an address in "Send to" and an amount in "Amount", check the "I confirm" box and submit the form then submit the following screen that previews your transaction? Your Ledger should prompt you at that point to confirm.

**Comment by baryaj** [comment]
Good morning,

I have STX in a Hiro wallet. I also have the STX app installed on my Ledger Nano X wallet.

I have never been able to export my coins to my Ledger wallet. I gave up a long time ago.

Today, I wanted to renew my effort but find a new wallet (Leather) out there. I am running from a Mac Os system and see the download but have concern for its authenticity and question whether or not to download it.

1. If I download the Leather wallet will my STX be automatically transferred from my Hiro wallet into it?

2. I still would like my STX in my Ledger Nano and need instruction(s) as to how to accomplish this.

	a. can I do it from my Hiro wallet or must I convert to the Leather wallet then export the STX from the Hiro wallet into it (the Leather wallet) and then transfer it it to my Ledger?

Any help/instructiona will be greatly appreciated.

Thank you.

Barry
