### ISSUE TITLE
[4.3.1] Bug: Tx issue

### ISSUE THREAD

**Issue by danst88** [blockstack/stacks-wallet#855]
I can't withdraw from my stx wallet.  I put in all the info including memo and essentially it just resets and does not recognize the transaction.  This is my address SP3NFEPWTADA059VBQZDM63E3N8A5T9RJDM27WC05

I also installed the newest version last night v4.3.1, but was having this issue before the install and now after.

Bug found testing Stacks Wallet build undefined, 4.3.1.

**Comment by kyranjamie** [comment]
Hi @danst88

Software or Ledger wallet? What do you mean by it "just resets and does not recognize the transaction"?
