### ISSUE TITLE
Nonce is stuck at 0 causes errors on multiple transactions

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#874]
Nonce is stuck at 0 causes errors on multiple transactions

<img width="744" alt="Screen Shot 2021-07-20 at 12 19 07 PM" src="https://user-images.githubusercontent.com/49165468/126361209-3858cc0d-d106-44b1-96a0-e85c1ff129f0.png">

<img width="745" alt="Screen Shot 2021-07-20 at 12 18 38 PM" src="https://user-images.githubusercontent.com/49165468/126361215-d0d2ebd0-2df0-4e19-b9ce-fc4517c9c626.png">

**Comment by markmhx** [comment]
@beguene would you be able to look into this one?

**Comment by beguene** [comment]
@markmhx I am on it

**Comment by beguene** [comment]
@timstackblock This is fixed now you can try.
