### ISSUE TITLE
Time stamp doesn't display for microblocks until I close wallet and reopen

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#877]
As you can see the time stamp is in the explorer and the microblocks transaction has been confirmed in the next anchorblock.

<img width="837" alt="Screen Shot 2021-07-22 at 10 24 23 AM" src="https://user-images.githubusercontent.com/49165468/126665094-7f8c8011-94d3-4162-b986-ba7b479b4eb5.png">

But the wallet doesnt refresh until I close it an open it, maybe we need to refresh the wallet every anchorblock to pull in timestamps

<img width="745" alt="Screen Shot 2021-07-22 at 10 23 10 AM" src="https://user-images.githubusercontent.com/49165468/126665126-b2e18821-cf90-42f1-a938-3c7908699824.png">

**Comment by beguene** [comment]
Not an issue as per @kyranjamie 
"The logic currently is to replace date with "in microblock". Refreshing is in place, I gather it was added to anchor block when it closed/reopened."

**Comment by markmhx** [comment]
@timstackblock want to retest / confirm whether the desktop wallet continued showing "in microblock" sans refresh after the explorer had already updated to anchor block?

**Comment by markmhx** [comment]
I just found in my QA as well that the desktop wallet didn't update automatically to show anchor block inclusion instead of microblock, at least until I did a hard refresh.

**Comment by beguene** [comment]
@timstackblock It's working fine for me now. Can you check again ? It could be caused by the lag of the api.

**Comment by timstackblock** [comment]
looks good

:shipit:
