### ISSUE TITLE
Show better error message for "not enough funds" due to microblocks balance 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#880]
We sopke about how the microblocks PR now create these not enough funds errors due to microblocks balance and users being able to send funds they currently do not have resulting in errors in the wallet.

@jasperjansz is working on changing the UI to handle this problem. This is an enhancement ticket to keep it on our radar. 

<img width="753" alt="Screen Shot 2021-07-27 at 10 02 28 AM" src="https://user-images.githubusercontent.com/49165468/127168269-de15d9f5-9e89-4f16-bd4c-932718aa46cb.png">

**Comment by markmhx** [comment]
I'm closing this since https://github.com/blockstack/stacks-blockchain/issues/2774 will hopefully resolve the underlying issue soon on the API side. We can reopen meanwhile if we hear user reports that suggest we need a better message.
