### ISSUE TITLE
Test faucet does not work with the microblocks API

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#881]
Test faucet does not work with the microblocks API

Failed to load resource: the server responded with a status of 500 ()

<img width="1026" alt="Screen Shot 2021-07-28 at 11 14 43 AM" src="https://user-images.githubusercontent.com/49165468/127348360-8efe7d30-8283-4bef-95e6-06a98ef4e769.png">
<img width="1031" alt="Screen Shot 2021-07-28 at 11 14 33 AM" src="https://user-images.githubusercontent.com/49165468/127348366-f40658e9-adfb-44a3-b161-b5692bb9be71.png">

**Comment by zone117x** [comment]
Faucet logic hasn't changed in microblocks API code. Likely the microblocks testnet deployment isn't configured for faucet, or there's some other testnet bug.

**Comment by markmhx** [comment]
@timstackblock want to open a related issue in the API repo given Matt's note above?

**Comment by timstackblock** [comment]
Its been fixed

<img width="749" alt="Screen Shot 2021-08-04 at 10 28 34 AM" src="https://user-images.githubusercontent.com/49165468/128199046-b698e6c0-7714-43c0-9fc3-b02a0fedc406.png">
