### ISSUE TITLE
400 errors in console when attempting to send STX with the desktop wallet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#883]
Please take a look at this stability issue. The microblocks API throws intermittent 400 errors when trying to send a transaction. The transaction goes through after several tries. 

<img width="1042" alt="Screen Shot 2021-07-29 at 2 16 43 PM" src="https://user-images.githubusercontent.com/49165468/127675842-013c548b-2983-4772-b4ce-5e8e6297c969.png">

**Comment by markmhx** [comment]
@timstackblock reports that there was also quite a bit of slowness in addition to the console errors

404s are generally expected. This could have been affected by network instability issues, which we could handle better here. We should probably prevent user from hitting the button more than once, and not even show the home screen / close the send modal until it's been submitted entirely.

**Comment by kyranjamie** [comment]
@timstackblock We poll the API to see if a newly-created tx is in the mempool yet. If it isn't, the api 404s and the error is caught. Despite catching the error, 400 errors are always output to console.

Is this the only issue, or was there a funky behaiviour, too? Can close if it's just the console errors.

**Comment by kyranjamie** [comment]
404s are expected, also made a small change to improve this fetching logic in microblocks PR
