### ISSUE TITLE
Web wallet does not recognize space character between the 24 words secret key 

### ISSUE THREAD

**Issue by TenaAnies** [blockstack/stacks-wallet#884]
The web wallet, Chrome plugin, did not recognize the space character when I was trying to set up a new wallet on a secondary device using my 24 words secret key. I was able to write the 24 words but without any space between them. I had to type the 24 words secret key on a text editor and paste them on the web wallet in order to be ablet to set it up.

I was using Chrome 92.0.4515.107 (Build officiel) (x86_64) on macOS 11.5.1 and Hiro web wallet v2.12.4. The Mac has a French keyboard.

**Comment by beguene** [comment]
Same as https://github.com/blockstack/stacks-wallet-web/issues/1508

**Comment by markmhx** [comment]
Thanks for reporting. I'm closing this issue in favor of the one linked above by @beguene to keep things tracked in one place.
