### ISSUE TITLE
Windows wallet shows pending balance .000002 stx reduction when only .000001 sent

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#89]
**Describe the bug**
Using the Windows wallet I sent .000001 stx  and the shows pending balancewent from .100002  to .100000. It should have only decreased by .000001 this is a bug.

**To Reproduce**
1. Go to a stacks wallet on windows send a micro stack 
2. Click on confirm to send the .000001 stx
3. Look at the balance in the wallet notice the pending balance will have decreased by 2 times as much

**Expected behavior**
Pending balance should have only decreased by .000001 and should have been .100001 and NOT .100002

**Screenshots**

SENDING WALLET  
<img width="765" alt="Screen Shot 2019-05-23 at 10 41 01 AM" src="https://user-images.githubusercontent.com/49165468/58265040-ee450d00-7d4c-11e9-9d98-b6b759b856ad.png">

RECIEVING WALLET
<img width="878" alt="Screen Shot 2019-05-23 at 11 08 06 AM" src="https://user-images.githubusercontent.com/49165468/58265042-ee450d00-7d4c-11e9-9af6-02d1b3f7582f.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version latest stacks wallet V3

**Comment by yknl** [comment]
This has been fixed in v3.0
