### ISSUE TITLE
Ensure newly sent transaction appears immediately in activity

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#892]
Currently there is sometimes a delay before the transaction appears in the activity list.

**Comment by markmhx** [comment]
Related issue for web wallet: https://github.com/blockstack/stacks-wallet-web/issues/1560

**Comment by kyranjamie** [comment]
Addressed this in #859. The transaction broadcast can feel quite slow, but the tx appears immediately.
