### ISSUE TITLE
Hash shows SHA512 while it is SHA256

### ISSUE THREAD

**Issue by misko9** [blockstack/stacks-wallet#911]
$ sha512sum stacks-wallet.mainnet.v4.5.2.deb 
5218e62b4360798373a1c51b17c1f40b4a2cea9543e13db10753067c4ded29b39314b388a50d46b97dd3bdd9afa2209f3631a2bc2c90bb019f23176b9b125d13  stacks-wallet.mainnet.v4.5.2.deb

$ sha256sum stacks-wallet.mainnet.v4.5.2.deb 
27a55a0975aa27c93a059ef311e87cd65f25d7c2db030e14f68b40d6b461bd7c  stacks-wallet.mainnet.v4.5.2.deb

**Comment by kyranjamie** [comment]
Appreciate this is confusing. The hashes are 256, but the hash of the signature is 512.

**Comment by misko9** [comment]
Thank you for clarifying!
