### ISSUE TITLE
Link in Ledger live is broken

### ISSUE THREAD

**Issue by cuevasm** [blockstack/stacks-wallet#913]
The learn more ends up at a broken URL - this is the 'Learn More' link provided right after someone installs for the first time and pictured below next to 'Installed'. 
![image](https://user-images.githubusercontent.com/6131188/133025958-d2abdb9c-7382-4932-b925-a40aabb2f742.png)

**Comment by markmhx** [comment]
I've inquired with Ledger about this over Slack:

![image](https://user-images.githubusercontent.com/28991/133606836-6f3de6f7-5c4b-4600-a6cc-576dd4c737b7.png)
