### ISSUE TITLE
New wallet

### ISSUE THREAD

**Issue by cryptojoe9** [blockstack/stacks-wallet#92]
Hello am very new to blockstacks I recently created a new wallet to participate in the token offering but according to the website you need to test the wallet after downloading. But my test came out to be different from what on the website.
![Screenshot (2)](https://user-images.githubusercontent.com/33847475/59981984-bb0acd80-95d9-11e9-8157-51f2d1a1f709.png)

**Comment by markmhx** [comment]
I'm not familiar with that specific command but it appears you have too many arguments, so you're seeing the command's instructions. Want to double check your syntax there?

**Comment by yknl** [comment]
Looks like you've copy & pasted extra characters after the command
