### ISSUE TITLE
[4.5.3] Bug: 24 letter key not working

### ISSUE THREAD

**Issue by latishpk** [blockstack/stacks-wallet#924]
Hello Team, I have tried logging into my hiro wallet in chrome extension with the 24 work phrase. But it says it is incorrect. I did try it earlier and it worked fine but today it doesn't seem to log me in. I am logged through my Hiro wallet in desktop. What can we do to get this fixed. I have the 24 word phrase as well as the "encryptedMnemonic" key with me. 

There seems a problem with the 24 word key, I created a new account copied the entire 24 words and then logged out and copy pasted the letters and it still doesn't recognize and this is like not even a minute and I copied in clipboard to ensure it was not my mistake. Can someone from the support team look at this bug.

Bug found testing Hiro Wallet build undefined, 4.5.3.

**Comment by markmhx** [comment]
I'm sorry you're running into difficulties here. To be clear: you've found this problem with one particular 24-word Secret Key, or with multiple when trying with separate keys?

**Comment by kyranjamie** [comment]
If I'm not mistaken, the same user has their issue resolved on Discord
https://discord.com/channels/621759717756370964/625538774230892545/889548579864191026
