### ISSUE TITLE
Seed phrase covers button

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/stacks-wallet#93]
**Describe the bug**
Seed phrase sits atop the "I've written down my seed phrase" button.

**To Reproduce**
1. Install StacksWallet on Windows 10 Pro
2. Chose software wallet only
3. Get to Seed Phrase page

**Expected behavior**
Seed phrase should not cover any buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/52256509/60205334-4f1da480-9827-11e9-832a-ab1b539f1ae3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - resolution: 1366x768

**Comment by markmhx** [comment]
This will be resolved with the new wallet.
