### ISSUE TITLE
[4.5.3] Bug: <Balance shows 0 STx>

### ISSUE THREAD

**Issue by crismat90** [blockstack/stacks-wallet#939]
Hi, is there a Hiro glitch?  My father staked 390,000 STX in March for 12 cycles using Hiro.  SP3NEKS3PNMSAGMX6HJ4WWW4ZRFNHYTPCGWZ44FX9 is his address.  When accessing his Hiro wallet with his seed phrase, it says he has 0 STX.  It also shows 0 STX transactions

He received the BTC stacking rewards until mid-September in his Binance account, and obviously those stopped once the 12th cycle stopped.  What’s odd is that no transactions at all are shown in his Hiro wallet, as if it never existed.  He has been holding stacks since it was at 0.07.  

Thanks!

Bug found testing Hiro Wallet build undefined, 4.5.3.

**Comment by markmhx** [comment]
Thanks for the report, and I'm sorry to hear about these troubles.

I'm trying to look up his address but can't seem to find it:  

![image](https://user-images.githubusercontent.com/28991/136706891-5340cedb-97d8-48c6-9c11-5359ada7546c.png)

Can you confirm this is the exact same address value?

**Comment by kyranjamie** [comment]
Same user messaged on twitter, they used wrong seed phrase
