### ISSUE TITLE
Add support option to settings modal

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#94]
**Is your feature request related to a problem? Please describe.**

Add a generic support option to the wallet's setting modal so users can contact us more easily if they encounter problems with any part of the wallet UX.

**Describe the solution you'd like**

Add the following section to the settings modal below all existing sections. Choosing "Email Us" triggers the operating system's default email program to load a compose with our support address pre-filled as the "to" value.

**Describe alternatives you've considered**

This idea originally sprung from a consideration of subsidizing BTC fees for users to remove the friction of making transactions. We discovered, however, that we couldn't implement such a subsidy without inordinate costs and abuse potential. So we decided to implement this simple support option instead as a way to hear from users who encounter problems with BTC fees and help them individually.

**Additional context**

<img width="815" alt="Screen Shot 2019-07-01 at 17 06 15" src="https://user-images.githubusercontent.com/28991/60448030-0c900980-9c25-11e9-925b-98fc6369f697.png">

**Comment by markmhx** [comment]
@moxiegirl Want to review this copy and general UX?

**Comment by moxiegirl** [comment]
@markmhx I think it is about help or asking a question:

![image](https://user-images.githubusercontent.com/1347209/60539389-7231d380-9cc1-11e9-87cb-f346946eacd5.png)

So, will this open Gmail or a client or what? Not clear.

**Comment by markmhx** [comment]
Those copy modifications look good to me. The idea is that this will open up whatever email client has been configured to handle the "mailto:" protocol on the user's machine. That could be Gmail or a client depending on that configuration.
