### ISSUE TITLE
My Stacks wallet is still showing invalid and Binance says there's nothing they can do because it has left their wallet.

### ISSUE THREAD

**Issue by hingst101** [blockstack/stacks-wallet#947]
It appears people had this problem about 10 months ago however I needed to transfer my Stacks to the new Hiro wallet about a month ago and I was unable to do it because it showed my deposit from Binance was Invalid.  I contacted Binance and asked them to resend the tokens but they said they can't do anything because the tokens had left their wallet and there was no way for them to re-send.  What do I need to do to get my STX tokens?  Thanks.
![STX wallet invalid picture](https://user-images.githubusercontent.com/92645529/137597192-2a31ff0a-fc8b-4a4e-b0b3-4f3e4e026178.jpg)

**Comment by kyranjamie** [comment]
This is a very old wallet version, from Stacks v1.

Install the latest Stacks Wallet, restore it with your seed phrase, and you'll be able to access your funds.

**Comment by kyranjamie** [comment]
Yes, I did. The wallet of this Github project. I've replied in your other issue with a link to information about Trezor users.
