### ISSUE TITLE
Fix support for Trezor Model T

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#97]
**Describe the bug**
Could not send tokens from Stacks wallet with Trezor model T

Place holder for support ticket reported Sept 20th

**Additional context**
Could not send tokens from Stacks wallet with Trezor 
Support

This is the first time tooney123 has posted — let’s welcome them to our community!

tooney123
3 
3h
Hi,

I could not send tokens from Stacks wallet with Trezor model T. I have the latest Trezor bridge and Trezor Firmware. The sign transaction page is permanently stuck in a loading screen.

I tried re-install Stacks wallet, tried to Reset wallet, tried to restart my computer: nothing works. Can you please help me solve this problem?

Thanks.

Edit:

In early June, I read on reddit that STX token is traded on the TOKOK exchange and I bought some STX there. I can successfully withdraw the tokens to my Trezor + Stacks wallet in June. And I confirm that the available balance in my wallet is not zero, and the associated BTC address has enough BTC to fund the transaction.

After buying STX token, I just left them there. In August, I found out that Blockstack tokensale on Coinlist is live, because I already own some tokens, I did not participate in it. I did, however, joined the telegram channel, and only then did I realize that TOKOK exchange is not recommended by the blockstack team, but it is too late, as I have already bought the tokens.

Now I wish to sell them before the hardfork and before the token release to the Coinlist token buyers. But I found out that I could not send tokens out of my Stacks wallet: the sign transaction page is stuck permanently on loading.

Edit2:
@ yukan @ jude Hi. I read your replies in another support thread and I guess you might be able to help me… I took the liberty to @ you here. Thanks.

**Comment by tooneywyq** [comment]
Hi. tooney here. If you need more information, let me know on the forum. Cheers.

**Comment by timstackblock** [comment]
Hello @tooneywyq I have a brand new Model T Trevor and I am trying to reproduce your issue now, I will share videos shortly.

**Comment by timstackblock** [comment]
I was able to replicate this issue on MacOS Mojave and Windows 10

Trezor Model T
Trezor firmware 2.1.4 
Trezor Bridge. Your version 2.0.27

The Trezor loading screen appears when a user attempts to send stacks with a Model T Hardware wallet. The screen freezes here and the transaction never goes through. On a mac you will see the following screen.

<img width="947" alt="Screen Shot 2019-09-30 at 11 45 33 AM" src="https://user-images.githubusercontent.com/49165468/65915588-be181580-e3a1-11e9-93e6-c3126a8aed6c.png">
<img width="947" alt="Screen Shot 2019-09-30 at 11 46 00 AM" src="https://user-images.githubusercontent.com/49165468/65915589-be181580-e3a1-11e9-857a-859ed1132ed6.png">
<img width="949" alt="Screen Shot 2019-09-30 at 11 46 15 AM" src="https://user-images.githubusercontent.com/49165468/65915590-be181580-e3a1-11e9-875c-c155a4745ff0.png">

On a windows 10 machine you get the same result but Trezor screen displays "signing message and it begins to process a loading bar but freezes about 15% through.

![20190930_132858](https://user-images.githubusercontent.com/49165468/65915828-367ed680-e3a2-11e9-8a79-fe528af82e3e.jpg)

**Comment by larrysalibra** [comment]
I have the exact same problem - signing transaction freezes at 15%. Interestingly the trezor model T didn't even prompt me to review the outputs/op_return content and skipped directly to signing.

macOS Cataline 10.15.1
Trezor firmware: 2.1.8
stacks wallet: 3.0.0

**Comment by tooneywyq** [comment]
> I have the exact same problem - signing transaction freezes at 15%. Interestingly the trezor model T didn't even prompt me to review the outputs/op_return content and skipped directly to signing.
> 
> macOS Catalina: 10.15.1
> Trezor firmware: 2.1.8
> stacks wallet: 3.0.0

Then... is there a way to send STX from the wallet?

**Comment by diwakergupta** [comment]
I believe @yknl is investigating, Ken do you have an update / ETA?

**Comment by yknl** [comment]
It looks like we're not able to support the model T. Supporting it requires a newer version of `TrezorConnect`, which do not work in an Electron app at the moment.

**Comment by tooneywyq** [comment]
> It looks like we're not able to support the model T. Supporting it requires a newer version of `TrezorConnect`, which do not work in an Electron app at the moment. The solution in the mean time is to use a Trezor One, with the same seed phrase on the model T.

Thanks.

**Comment by tooneywyq** [comment]
> It looks like we're not able to support the model T. Supporting it requires a newer version of `TrezorConnect`, which do not work in an Electron app at the moment. The solution in the mean time is to use a Trezor One, with the same seed phrase on the model T.

Can I recover the Model T's seed phrase on a ledger NANO s, and get access to STX?

**Comment by tooneywyq** [comment]
> It looks like we're not able to support the model T. Supporting it requires a newer version of `TrezorConnect`, which do not work in an Electron app at the moment. The solution in the mean time is to use a Trezor One, with the same seed phrase on the model T.

Hi. I got a trezor one. I still cannot send STX.  

1. when I recover the trezor model T seed on trezor one, the STX token does not appear on stacks wallet.

2. after using model T to recover a wallet on stacks wallet, still cannot use trezor one to send.

**Comment by ryanarndtcm** [comment]
Hi Tooney, @yknl would be best to answer this.

**Comment by markmhx** [comment]
@yknl Mind checking if the needed version of TrezorConnect works for Electron now and we could possibly patch this?

**Comment by yknl** [comment]
> @yknl Mind checking if the needed version of TrezorConnect works for Electron now and we could possibly patch this?

It does not, I would push for native support on Trezor in Stacks 2.0 at this point.

**Comment by swillinger** [comment]
@yknl which version of TrezorConnect works on the model one?  (thanks!)

**Comment by yknl** [comment]
> @yknl which version of TrezorConnect works on the model one? (thanks!)

Version 4

**Comment by ryanarndtcm** [comment]
Coming in from support

"I used Trezor support and they have a procedure to downgrade.  It turns
out I did not need that since I had a backup of the TREZOR Bridge which
I  use for the one successful STX transaction on October 27, 2019.   I
was not on Catalina at that time.  The backup was the same TREZOR Bridge
version 2.0.27 and produced the same STX transaction result as you
pointed out in the ticket below.

I also retested my keys with MEW and the bridge worked for that.

-t

macOS Catalina: 10.15.4
Trezor One firmware: 1.9.2
Trezor Bridge: 2.0.27
stacks wallet: 3.0.0"

**Comment by swillinger** [comment]
Ok, I just attempted to match all software versions (other than OS) as above and am still getting the same result (input tx into Stacks Wallet, confirm OP_RETURN address and multiple BTC txs on Trezor One, then Trezor bridge window closes on last confirm, but no tx takes place and am left on "Connect your Trezor" screen in Stacks Wallet).  

Windows 10 pro version 1909, OS build 18363.1016
Trezor One Firmware 1.9.2
Trezor Bridge: 2.0.27 (also tried 2.0.19)
Stacks Wallet 3.0.0
