### ISSUE TITLE
How can we port this to iOS / Android?

### ISSUE THREAD

**Issue by Sydney-o9** [blockstack/stacks-wallet#98]
Would a React Native solution make sense for iOS / Android? Just wondering if you need a bit of support to build it or if you have decided not to build it on purpose?

Happy to help if you want.

**Comment by yknl** [comment]
Hey @Sydney-o9, there are currently no plans for Blockstack to release a react-native port of the Stacks wallet for mobile. It would be great if there's a mobile version though. I'm happy to assist if you want to take a stab at it.
